$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0
$quote "
$set MS_QUOTA

NOQUOTAONSYS	"There are no quotas on this system\n"
USE1		"Usage: quota [-guqv]"
USE2		"\tquota [-qv] -u username ..."
USE3		"\tquota [-qv] -g groupname ..."
NOACC		"(no account)"
PERDENU		"quota: %s (uid %d): permission denied\n"
UNKUSR		"quota: %s: unknown user\n"
NOENT		"(no entry)"
GETGR		"quota: getgroups"
PERDENG		"quota: %s (gid %d): permission denied\n"
UNKGRP		"quota: %s: unknown group\n"
FLIMIT		"File limit reached on"
FGRACE		"In file grace period on"
FQUOTA		"Over file quota on"
BLIMIT		"Block limit reached on"
BGRACE		"In block grace period on"
BQUOTA		"Over block quota on"
NONE		"none"
HEAD		"Disk quotas for %s %s (%cid %d): %s\n"
MSGFS		"Filesystem"
MSGB		"blocks"
MSGQ		"quota"
MSGL		"limit"
MSGG		"grace"
MSGF		"files"
DAYS		"days"
NOMEM		"quota: out of memory\n"
RDERR		"quota: read error"
