#!/bin/sh -
# 
# *****************************************************************
# *                                                               *
# *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
# *                                                               *
# *   All Rights Reserved.  Unpublished rights  reserved  under   *
# *   the copyright laws of the United States.                    *
# *                                                               *
# *   The software contained on this media  is  proprietary  to   *
# *   and  embodies  the  confidential  technology  of  Digital   *
# *   Equipment Corporation.  Possession, use,  duplication  or   *
# *   dissemination of the software and media is authorized only  *
# *   pursuant to a valid written license from Digital Equipment  *
# *   Corporation.                                                *
# *                                                               *
# *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
# *   by the U.S. Government is subject to restrictions  as  set  *
# *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
# *   or  in  FAR 52.227-19, as applicable.                       *
# *                                                               *
# *****************************************************************
#
# HISTORY
# 
# @(#)$RCSfile: mkwhatis.sh,v $ $Revision: 4.3.3.10 $ (DEC) $Date: 1992/12/07 11:24:42 $
#
# (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
# ALL RIGHTS RESERVED
#
#
# OSF/1 Release 1.0
#
#
# COMPONENT_NAME: (CMDMAN) commands that allow users to read online 
# documentation
#
# FUNCTIONS: 
#
# ORIGINS: 26, 27
#
# (C) COPYRIGHT International Business Machines Corp. 1989
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Copyright (c) 1980 Regents of the University of California.
# All rights reserved.  The Berkeley software License Agreement
# specifies the terms and conditions for redistribution.
#
# mkwhatis.sh	1.5  com/cmd/man,3.1,9021 4/12/90 18:09:13
#
#
# Maintenance History
#
# 001	gws
#	added removal of "\*L" and "\*O" strings from getNAME data
#
# 002	gws
#	replaced "/usr/lbin/getNAME *.*" with pipe filtering via xargs
#	so getNAME doesn't blow up with "arg list too long" when man?
#	directories have large numbers of files.  Pipe is limited in size
#	by $LIMIT variable and xargs -s[length] default maximum argsize length.
#
# 003	gws 02-Dec-1991 (OSF_QAR 1787)
#	changes made to make it possible for apropos and whatis to find
#	manpages with hyphenated names, such as mh-alias.  The changes
#	consists of translating hyphens with trailing spaces into "@", so that
#	hyphens contained in manpage names survive the rewriting of the .TH
#	data into "whatis" entries.  Any leftover @'s are translated back to
#	hyphen<blank> later.  Changes are derived from ULTRIX V4.2.
#
#	comments are also added to describe all sed steps.
#
# 004	gws 03-Dec-1991 (OSF_QAR 1788)
#	replace \(em with hyphens, so manpages with \(em name/description
#	separators will have proper entries in the "whatis" database, so they
#	can be found by the whatis(1) command.
#
# 005	gws 03-Dec-1991 (OSF_QAR 2284)
#	change list of manpages directories to be same as the man(1) command
#	actually supports: CLFnlpo1-809
#	NOTE: if list of sections supported by man(1) should change in the
#	      future, the "for i ...." loop will need to be changed.
#
# 006	gws 04-Dec-1991 (OSF_QAR 2290)
#	added font stripping for the special case where a inlin fontcall was
#	the first line of the NAME section, preceeding the line containing
#	the manpage name.  getNAME inserts blanks when joining lines, so:
#	   .TH manpage section [fields]...
#	   .SH NAME
#	   \fB
#	   manpage\fP - description
#	  .SH ...
#	gets converted to:
#	   manpage section [fields]...<tab>\fB<blank>manpage\fP - description
#	When the getNAME data gets translated and reformated, the blank remains
#	in front of "manpage", so whatis(1) can't find "manpage".
#

trap "rm -f /tmp/whatisx.$$ /tmp/whatis$$; exit 1" 1 2 13 15
MANDIR=${1-/usr/share/man}
#
LIMIT=200		# number of files to process at a time		# 002
			# (big enough to accomdate maximum argument	# 002
			# size of 470 bytes. see xargs(1) -s[length] )	# 002
#
rm -f /tmp/whatisx.$$ /tmp/whatis$$
if test ! -d $MANDIR ; then exit 0 ; fi
cd $MANDIR
top=`pwd`

for i in man[CLFnlpo1-809]						# 005
do
	if [ -d $i ] ; then
		cd $i
	 	if test "`echo *.*`" != "*.*" ; then
			ls | xargs -n$LIMIT /usr/lbin/getNAME		# 002
		fi
		cd $top
	fi
done >/tmp/whatisx.$$

#								    start 003
#
# editing the output generated by getNAME
#
# getNAME returns lines that have the general syntax:			007
#  .TH name section [fields]... <tab>name[, name2[, name3 ...]..] $ description
# where $ = a separator string.  Valid separator strings are:
#       <blank>-<blank>
#       <blank>\-<blank>
# 	<blank>\(em<blank>
# section and [fields]... may be enclosed in double quotes (")
#
# sed performs the following operations on each line of output from getNAME:
#	o replaces \(em		with - (hyphen)				004
#	o replaces \(hy		with - (hyphen)			  added 008
#	o replaces \(mi		with - (hyphen)		          added 008
#       o replaces <blank>\-<blank> with <blank>@                 added 012
#	o replaces \-<blank>	with @					003
#	o replaces <blank><blank>*-<blank> with <blank>@		007
#	o replaces -<blank>	with @					003
#	o removes " VAX-11"
#	o removes .iX.* and .IX.* macro calls                   changed 010
#       o removes all characters between .cS and .cE              added 011
#	o removes .PP<blank>* macro calls
#	o removes .B<blank>* macro calls
#	o removes .rS<blank>* macro calls
#	o removes .gL<blank>* macro calls
#	o removes .br<blank>* roff commands
#       o removes .nL<blank>* macro calls                         added 012
#	o removes roff \& (zero-width) characters constructs
#	o removes ""<blank>[<blank>...]
#	o removes .UC macro calls
#	o removes double quotes from quoted numeric strings
#	o replaces "LOCAL"	with LOCAL
#	o removes all remaining double quotes				007
#	o replaces <tab><inline font calls for fonts PRIB0-3><blank>*	006
#	  			with <tab>				006
#	o removes inline font calls for fonts P, R, I, B, 0-3
#	o removes inline point size change calls (\s[+-]<number>)
#	o removes rsml inline font strings \*L and \*O		    001 003
#       o replaced \/             with / (slash)                  added 009
#	o translates						    003 007
# .TH name section [fields]... <tab>name[, name2[, name3 ...]..]@description@
#          into
# name[, name2[, name3 ...]..](section)<tab>-<blank>description@
#	o translates any remaining "@"'s back into "-<blank>"		003
#	o replaces <tab><blank> with <tab> 
#
#								    end 003
sed  </tmp/whatisx.$$ >/tmp/whatis$$ \
	-e 's/\\(em/-/'		\
	-e 's/\\(hy/-/'		\
	-e 's/\\(mi/-/'		\
	-e 's/ \\- / @/'        \
	-e 's/\\- /@/'		\
	-e 's/  *- / @/'	\
	-e 's/- /@/'		\
	-e 's/ VAX-11//'	\
	-e 's/\.[iI]X *"[^"]*" *"[^"]*" *"[^"]*" *"[^"]*" *//g' \
	-e 's/\.[iI]X *"[^"]*" *"[^"]*" *"[^"]*" *//g'          \
	-e 's/\.[iI]X *"[^"]*" *"[^"]*" *//g'                   \
	-e 's/\.[iI]X *"[^"]*" *//g'                            \
	-e 's/\.cS .*\.cE//'    \
	-e 's/\.PP *//g'	\
	-e 's/\.B *//g'		\
	-e 's/\.rS *//g'	\
	-e 's/\.gL *".*"//g'	\
	-e 's/\.br *//g'	\
	-e 's/\.nL *//g'        \
	-e 's/\\&//g'		\
	-e 's/"" *//g'		\
	-e 's/\.UC [0-9]//g'	\
	-e 's/"\([0-9]*\)"/\1/g' \
	-e 's/"LOCAL"/LOCAL/g'	\
	-e 's/"//g'		\
	-e 's/	\\f[PRIB0123] */	/g' \
	-e 's/\\f[PRIB0123]//g'	\
	-e 's/\\s[-+0-9]*//g'	\
	-e 's/\\\*[LO]//g'	\
	-e 's/\\\//\//g'	\
	-e 's/.TH *[^ ][^ ]* \([^ 	]*\).*	\([^@]*\)@/\2(\1)	- /' \
	-e 's/@/- /'		\
	-e 's/	 /	/g'
/usr/bin/expand -24,28,32,36,40,44,48,52,56,60,64,68,72,76,80,84,88,92,96,100 \
	/tmp/whatis$$ > /tmp/whatis.$$.s
 sort /tmp/whatis.$$.s | /usr/bin/unexpand -a > whatis
chmod 664 whatis >/dev/null 2>&1
rm -f /tmp/whatisx.$$ /tmp/whatis$$ /tmp/whatis.$$.s
exit 0
