#
# *****************************************************************
# *                                                               *
# *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
# *                                                               *
# *   All Rights Reserved.  Unpublished rights  reserved  under   *
# *   the copyright laws of the United States.                    *
# *                                                               *
# *   The software contained on this media  is  proprietary  to   *
# *   and  embodies  the  confidential  technology  of  Digital   *
# *   Equipment Corporation.  Possession, use,  duplication  or   *
# *   dissemination of the software and media is authorized only  *
# *   pursuant to a valid written license from Digital Equipment  *
# *   Corporation.                                                *
# *                                                               *
# *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
# *   by the U.S. Government is subject to restrictions  as  set  *
# *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
# *   or  in  FAR 52.227-19, as applicable.                       *
# *                                                               *
# *****************************************************************
#
#
# HISTORY
#
#
#	@(#)$RCSfile: Makefile,v $ $Revision: 4.2 $ (DEC) $Date: 1991/09/19 22:21:07 $
# (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
# ALL RIGHTS RESERVED
#
#
# OSF/1 Release 1.0

VPATH			= ${MAKETOP}/kernel/mmax

DATAFILES		= DEFAULT.h FEATURES.h apcdefs.h addrconf.h \
			  ast_types.h boot.h boot_info.h \
			  boot_info_types.h cfg.h clock.h cpu.h \
			  cpudefs.h dpcdefs.h duart.h endian.h \
			  fpu.h icu.h inline_lock.h machlimits.h \
			  machparam.h machtime.h mlmacros.h mmax_ptrace.h \
			  mmu.h mtpr.h panic.h panic_ns32k.h pcb.h \
			  pmap.h psl.h pte.h reg.h scc_attns.h \
			  sccdefs.h sched_param.h thread.h timer.h \
			  timer_macros.h toy.h trap.h tse.h \
			  vm_tuning.h vmparam.h xpcdefs.h xpr.h

include ${MAKEFILEPATH}/standard.mk
include ${MAKEFILEPATH}/datafiles.mk
