#! /usr/bin/ksh
 

	OPTIONS="d"
	PWD=${PWD:=$(/bin/pwd)}		# Can't use environment variable 

test ${DEBUG} && { 			# Test to see if environment 
	 PS4='$LINENO+ '		# debugging turned on.
	 set -x
}


test ${WORKON} || {			# Since this program depends on 

	test ${SOURCEBASE} || {
	    print -u2 "error: SOURCEBASE not defined in environment"
	exit 1
	}

	WORKON=1
	BACKED_SOURCEDIR=${SOURCEBASE}
	export WORKON BACKED_SOURCEDIR
}


set -- $(getopt $OPTIONS $*)
if [ $? != 0 ]
then
	print -u2 "genloc [-d] files"
	exit 2
fi

for i in $*
do
	case $i in
		-d ) DIR_ONLY=1; shift ;;
		--) shift; break;;
	esac
done

test $# || {				# Check to see if there were any

	print -u2 "Usage: genloc [-d] files"
	exit
}
FILES="$*"
for FILE in ${FILES}
do
	case ${FILE} in 
		\/*)
			SB_DIR=$(dirname ${FILE})
			CSD=${SB_DIR##*$(dirname ${SOURCEBASE})}	
			FILE=$(basename ${FILE})
			;;

		*)	# No path given assume they want to find the file in
			case ${PWD} in
				*src*) CSD=${PWD##*$(dirname ${SOURCEBASE})}
				;;
				
				*) CSD=/src${MAKEDIR##*$(dirname ${SOURCEBASE})}
				;;
			esac
			;;
	esac


	SEARCH_PATH=$(print "${BACKED_SOURCEDIR}" | \
		sed -e 's+:+ +'g | \
		sed -e 's+/src+'${CSD}' +'g )

	for DIR in ${SEARCH_PATH}
	do
		if [[ -r ${DIR}/${FILE} ]]
		then
			if [[ ${DIR_ONLY:=0} -eq 1 ]]
			then
				dirname ${DIR}/${FILE}
			else
				print ${DIR}/${FILE}
			fi
			break
		fi
	done
done
