.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: ap.8,v $ $Revision: 3.2.2.2 $ (DEC) $Date: 1992/05/27 13:32:18 $
.\"
.TH ap 8
.SH NAME
ap \- parse addresses RFC 822-style
.SH SYNOPSIS
.PP
.B /usr/lib/mh/ap
[
.B "\-form"
\*Vfile\*O
] [
.B "\-format"
\*Vstring\*O
] [
.B "\-help"
] [
.B "\-[no]normalize"
] [
.B "\-width"
\*Vcolumns\*O
]
\*Vaddrs ...\*O
.\"
.\"
.\"
.\"
.SH DESCRIPTION
.PP
.iX "ap program"
.iX "RFC 822" "address parsing by MH system"
The \*Lap\*O program parses addresses according to the ARPA Internet standard.
It also understands many non-standard formats.
It is useful for seeing how MH will interpret an address.
.PP
The \*Lap\*O program treats each argument as one or more addresses,
and prints those addresses in the official RFC 822 format.
Hence, it is usually best to enclose each argument in
double quotes (") for the shell.
.PP
In addition to the standard escapes, \*L scan also
recognizes the additional escape  \*Lerror\*O,
which is a diagnostic that is returned if the parse failed.
.\"
.\"
.\"
.\"
.SH FLAGS
.PP
.IP "\-form \f2file\f3" 10
Overrides the default output format of \*Lap\*O.
The output is formatted according to the instructions
in the specified file.
This must be a format file; see \*Lmh-format\*O(4).
.\"
.IP "\-format \f2string\f3" 10
Overrides the default output format of \*Lap\*O.
The output is formatted according to the instructions
in the specified string.
This must be a format string; see \*Lmh-format\*O(4).
.IP
The argument to the
.B \-format
option must be interpreted as a single token
by the shell that invokes \*Lap\*O.
Therefore, you should usually place the argument to this
option inside double quotes (").
.\"
.IP "\-help" 10
Prints a list of the valid options to this command.
.\"
.IP "\-normalize" 10
.PD 0
.IP "\-nonormalize" 10
.PD
Tells \*Lap\*O to try to find the official host name of the address.
This is the default behavior.
It can be suppressed using the
.B \-nonormalize
option.
.\"
.IP "\-width \f2columns\f3" 10
Specifies the width of the screen in columns.
.\"
.\"
.PP
The defaults for this command are as follows:
.IP
.B \-normalize
.br
.B \-width
defaults to the width of the terminal
.\"
.\"
.\"
.\"
.SH RESTRICTIONS
.PP
On systems where MH is configured with the BERK option,
address parsing is not enabled.
.\"
.\"
.\"
.\"
.SH EXAMPLES
.PP
This is the default format string used by \*Lap\*O:
.oS
%<{error}%{error}: %{text}%|%(proper{text})%>
.oE
If an error was detected,
this string instructs \*Lap\*O
to print the error, a colon (\*L:\*O),
and the address that is in error.
Otherwise, output the proper RFC 822 format of the address.
.\"
.\"
.\"
.\"
.\"
.SH FILES
.PP
.TP 10
\*L$HOME/.mh_profile\*O
User profile.
.TP 10
\*L/usr/lib/mh/mtstailor\*O
System customization file.
.\"
.\"
.\"
.\"
.SH RELATED INFORMATION
.PP
\*Lmh-format\*O(4), \*Ldp\*O(8)
.br
\*VStandard for the Format of ARPA Internet Text Messages\*O
(RFC 822)
.EQ
delim off
.EN
