.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: popaka.8,v $ $Revision: 3.2.6.3 $ (DEC) $Date: 1994/01/20 00:56:32 $
.\" 
.TH popaka 8
.SH NAME
.PP
\*Lpopaka\*O \- Generates POP entries for the \*LSendMail\*O or \*LMMDF-II\*O aliases file
.SH SYNOPSIS
.PP
.sS
\*L/usr/local/lib/mh/popaka\*O
.sE
.SH DESCRIPTION
.PP
.iX "popaka command"
The \*Lpopaka\*O program reads the Post Office Protocol (POP) database and
produces on its standard output an alias string suitable for inclusion in the
\*L/usr/adm/sendmail/aliases\*O file.  The contents of this alias
diverts mail for POP subscribers to the POP channel.
.SH FILES
.PP
.VL 11m
.LI "\*L/usr/spool/pop/POP\*O"
Specifies the POP database.
.LE
.SH RELATED INFORMATION
.PP
Files: \*Lpop\*O(4)
.EQ
delim off
.EN
