.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: rc3.8,v $ $Revision: 3.2.2.2 $ (DEC) $Date: 1992/05/21 12:37:49 $
.\"
.\" 
.\" (c) Copyright 1991, OPEN SOFTWARE FOUNDATION, INC.
.\" ALL RIGHTS RESERVED
.\" 
.TH rc3 8
.SH NAME
\*Lrc3\*O \- Run command script executed when entering a multiuser run level
.SH SYNOPSIS 
.sS 
\*Lrc3\*O
.sE 
.SH DESCRIPTION
.iX "rc3 command"
.PP 
The \*Lrc3\*O
script contains run commands that enable initialization of the system
to a multiuser state; run level 3.
In addition to commands listed within the script itself,
\*Lrc3\*O contains instructions to run certain commands found in the
\*L/sbin/rc3.d\*O directory.
The script defines the conditions under which the commands execute; 
some commands run if the system is booting, other commands execute if 
the system is changing run levels.
.PP 
By convention, files in the \*Lrc3.d\*O
directory begin with either the letter "S" or the letter "K" and are
followed by a two-digit number and a filename; for example:
.oS
S00inet     S55inetd     S70mount     S65lpd
.oE 
.PP 
In general, the system starts commands that begin with the
letter "S" and stops commands that begin with the letter "K."
Commands that begin with the letter "K" run only when the system is
changing run levels from a higher to a lower level.  Commands
that begin with the letter "S" run in all cases.
The numbering of commands in the \*L/sbin/rc3.d\*O
directory is important since the numbers are sorted and the commands
are run in ascending order.  Files in the \*L/sbin/rc3.d\*O
directory are normally links to files in the \*L/etc/init.d\*O directory.
.PP 
An entry in the \*Linittab\*O file causes the system to execute the \*Lrc3\*O
run commands, for example:
.oS
s3:3:wait:/sbin/rc3 < /dev/console > /dev/console 2>&1
.oE 
.PP 
The following operations are typical of those that result from executing the
\*Lrc3\*O script and the commands located in the \*L/sbin/rc3.d\*O
directory.  The operation depends on which state the system is entering
or exiting.
.ML
.LI
Setting the time zone
.LI
Checking the current run level
.LI
Starting network services and daemons
.LI
Starting (or stopping) system services and daemons
.LI
Mounting file systems
.LE 
.PP 
Setting the TIMEZONE variable is one of the first operations completed by the
\*Lrc3\*O script.  This action provides the default time zone for 
subsequent commands.
.SH FILES
.VL
.LI "\*L/sbin/rc3\*O"
Specifies the command path
.LI "\*L/sbin/rc3.d\*O"
Specifies the directory of commands that correspond to the run level
.LE 
.SH RELATED INFORMATION
.PP 
Commands:  \*Linit\*O(8), \*Lrc0\*O(8), \*Lrc2\*O(8)
.iX "rc3 command"
.EQ
delim off
.EN
