.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: rpc.rstatd.8,v $ $Revision: 1.1.2.3 $ (DEC) $Date: 1993/07/28 19:28:14 $
.\"
.TH rpc.rstatd 8
.SH NAME
.PP
\*Lrpc.rstatd\*O, \*Lrstatd\*O \- Kernel statistics server
.SH SYNOPSIS
.PP
\*L/usr/lib/netsvc/rstat/rpc.rstatd\*O
.SH DESCRIPTION
.PP
.iX "rpc.rstatd"
.iX "rstatd"
The \*Lrpc.rstatd\*O daemon is a server that returns performance statistics
obtained from the kernel.  The \*Lrup\*O(1) command uses the \*Lrpc.rstatd\*O
to collect the uptime information that it displays.
.PP
The \*Lrpc.rstatd\*O daemon is an RPC service. The \*Lrstatd\*O daemon is
normally invoked by \*Linetd\*O(8) by removing the comment character (#) at the
beginning of the \*Lrstatd\*O entry in the \*L/etc/inetd.conf\*O file.
.SH "RELATED INFORMATION"
.PP
Commands: \*Lrup\*O(1), \*Linetd\*O(8), \*Lservices\*O(4)
.EQ
delim off
.EN
