.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: udelta.8,v $ $Revision: 3.2.2.4 $ (DEC) $Date: 1992/09/15 18:56:43 $
.\"
.\" SCCSID: @(#)udelta.8 3.1 of 3/13/92
.TH udelta 8
.SH NAME
.PP
\*Ludelta\*O - print differences between two subset inventories
.SH SYNOPSIS
.PP
\*L/usr/lbin/udelta\*O \*Vinv1\*O \*Vinv2\*O
.SH DESCRIPTION
.PP
The
\*Ludelta\*O
command reads records from sorted inventory files
\*Vinv1\*O
and
\*Vinv2\*O.
Records from each file are compared by file name.  Each record from
\*Vinv1\*O
which does not have a corresponding record in
\*Vinv2\*O
is written to the standard output.
.SH RELATED INFORMATION
.PP
File formats:  stl_inv(4)
.EQ
delim off
.EN
