.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: zdump.8,v $ $Revision: 3.2.2.2 $ (DEC) $Date: 1992/05/27 15:00:55 $
.\"
.TH zdump 8
.SH NAME
zdump \- time zone dumper
.SH SYNOPSIS
.B zdump
[
.B \-c
.I cutoffyear 
] [
.B \-v
] 
.I zonename ...
.SH DESCRIPTION
The 
.PN zdump
command prints the current time in each
.I zonename
named on the command line.
.SH FLAGS
.IP "\-c \f2cutoffyear\fP"
Cut off the verbose output near the start of the \f2cutoffyear\fP.
.IP \-v
For each
.I zonename
on the command line,
prints the current time,
the time at the lowest possible time value,
the time one day after the lowest possible time value,
the times both one second before and exactly at
each time at which the rules for computing local time change,
the time at the highest possible time value,
and the time at one day less than the highest possible time value.
Each line ends with
isdst=1
if the given time is Daylight Saving Time or
isdst=0
otherwise.
.SH FILES
.TP 13
.PN /etc/zoneinfo
Standard zone information directory
.SH RELATED INFORMATION
ctime(3), tzfile(5), zic(8)
.EQ
delim off
.EN
