/*
 * *****************************************************************
 * *                                                               *
 * *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
 * *                                                               *
 * *   All Rights Reserved.  Unpublished rights  reserved  under   *
 * *   the copyright laws of the United States.                    *
 * *                                                               *
 * *   The software contained on this media  is  proprietary  to   *
 * *   and  embodies  the  confidential  technology  of  Digital   *
 * *   Equipment Corporation.  Possession, use,  duplication  or   *
 * *   dissemination of the software and media is authorized only  *
 * *   pursuant to a valid written license from Digital Equipment  *
 * *   Corporation.                                                *
 * *                                                               *
 * *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
 * *   by the U.S. Government is subject to restrictions  as  set  *
 * *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
 * *   or  in  FAR 52.227-19, as applicable.                       *
 * *                                                               *
 * *****************************************************************
 */
/*
 * HISTORY
 */
/*
** Generated by ODL Version X0.1 on Tue Jul 14 18:32:27 1992
*/

/*
** COPYRIGHT (c) 1989 BY
** DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.
** ALL RIGHTS RESERVED.
**
** THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED
** ONLY  IN  ACCORDANCE  OF  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE
** INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER
** COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
** OTHER PERSON.  NO TITLE TO AND  OWNERSHIP OF THE  SOFTWARE IS  HEREBY
** TRANSFERRED.
**
** THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE
** AND  SHOULD  NOT  BE  CONSTRUED  AS A COMMITMENT BY DIGITAL EQUIPMENT
** CORPORATION.
**
** DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS
** SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
*/

/*
** Private Type Definitions for the Linknet Object
*/

/*
** Abstract Type Definitions for subtypes of Object
*/

typedef _Object _List, _PtrTo _ListPtr;
typedef _Object _Set, _PtrTo _SetPtr;
typedef _Object _Property, _PtrTo _PropertyPtr;
typedef _Object _ObjectId, _PtrTo _ObjectIdPtr;
typedef _Object _ObjectDesc, _PtrTo _ObjectDescPtr;
typedef _Object _Ui, _PtrTo _UiPtr;
typedef _Object _DXmUi, _PtrTo _DXmUiPtr;
typedef _Object _DXmEnvState, _PtrTo _DXmEnvStatePtr;
typedef _Object _Persistent, _PtrTo _PersistentPtr;
typedef _Object _Surrogate, _PtrTo _SurrogatePtr;
typedef _Object _Link, _PtrTo _LinkPtr;
typedef _Object _CompLinknet, _PtrTo _CompLinknetPtr;
typedef _Object _Step, _PtrTo _StepPtr;
typedef _Object _Path, _PtrTo _PathPtr;
typedef _Object _CompPath, _PtrTo _CompPathPtr;
typedef _Object _Linkbase, _PtrTo _LinkbasePtr;

/*
** Linknet Instance Structure Definition
*/

typedef struct __Linknet {
        _Type type;
        _Linkbase linkbase;
        _Integer identifier;
        _DDIFString description;
        _DDIFString author;
        _Date creation_date;
        _Set_of(_DDIFString) keywords;
        _Set_of(_Property) properties;
        _StateFlags flags;
        _DDIFString name;
        _Set_of(_Link) links;
        _Set_of(_Surrogate) surrogates;
    } _LinknetInstance, _PtrTo _Linknet, _PtrTo _PtrTo _LinknetPtr;

/*
** Linknet Property Name Table Index Definitions
*/

#define _NameIndex 0
#define _LinksIndex 1
#define _SurrogatesIndex 2

/*
** Linknet Property Name Table Definition
*/

#define _LinknetPropertyNameTable \
    _PropertyNameTableEntry _Constant LinknetPropertyNameTable[] = { \
        {_P_Name, _NameIndex, _True}, \
        {_P_Links, _LinksIndex, _True}, \
        {_P_Surrogates, _SurrogatesIndex, _True}, \
        {(_String) 0, 0, _False} \
    }

/*
** Linknet Property Accessor Definitions
*/

#define _Name_of(Obj) ((_Linknet) _Reference(Obj))->name
#define _Links_of(Obj) ((_Linknet) _Reference(Obj))->links
#define _Surrogates_of(Obj) ((_Linknet) _Reference(Obj))->surrogates

/*
** Include Generic Operation Support
*/

#include "lwk_operation_prototypes.h"

/*
** Linknet Method Declarations
*/

_DeclareFunction(void LwkOpObjIllOp, (_in _Object object));
_DeclareFunction(_Linknet LwkOpObjCopy, (_in _Linknet object, _in _Boolean aggreate));
_DeclareFunction(_Linknet LwkOpObjCreate, (_in _Type type));
_DeclareFunction(void LwkOpLnetDecode, (_inout _Linknet persistent,
    _in _DDIShandle handle, _in _Boolean keys_only,
    _inout _SetPtr properties));
_DeclareFunction(void LwkOpLnetDrop, (_inout _Linknet linknet));
_DeclareFunction(void LwkOpLnetEncode, (_in _Linknet persistent,
    _in _Boolean aggregate, _in _DDIShandle handle));
_DeclareFunction(_Set LwkOpLnetEnumProps, (_in _Linknet object));
_DeclareFunction(_Integer LwkOpPersistExport, (_in _Linknet persistent,
    _in _Boolean aggregate, _out _VaryingStringPtr encoding));
_DeclareFunction(void LwkOpObjExpunge, (_inout _Linknet object));
_DeclareFunction(void LwkOpLnetFree, (_inout _Linknet object));
_DeclareFunction(_Domain LwkOpObjGetDomain, (_in _Linknet object));
_DeclareFunction(_ObjectDesc LwkOpPersistGetObjectDesc, (
    _in _Linknet persistent));
_DeclareFunction(_ObjectId LwkOpPersistGetObjectId, (
    _in _Linknet persistent));
_DeclareFunction(void LwkOpLnetGetValue, (_in _Linknet object,
    _in _String property_name, _in _Domain domain,
    _in _AnyPtr value));
_DeclareFunction(_Domain LwkOpLnetGetValueDomain, (_in _Linknet object,
    _in _String property_name));
_DeclareFunction(_List LwkOpLnetGetValueList, (_in _Linknet object,
    _in _String property_name));
_DeclareFunction(_Linknet LwkOpPersistImport, (_in _Type type,
    _in _VaryingString encoding));
_DeclareFunction(void LwkOpPersistImportKeyProperties, (
    _in _Type type, _in _VaryingString encoding,
    _inout _SetPtr properties));
_DeclareFunction(void LwkOpLnetInitialize, (_inout _Linknet object,
    _in _Linknet proto_object, _Boolean aggregate));
_DeclareFunction(_Boolean LwkOpLnetIsMultiValued, (_in _Linknet object,
    _in _String property_name));
_DeclareFunction(_Boolean LwkOpObjIsType, (_in _Linknet object,
    _in _Type type));
_DeclareFunction(_Termination LwkOpLnetIterate, (_in _Linknet linknet,
    _in _Domain domain, _in _Closure closure,
    _in _Callback routine));
_DeclareFunction(_Termination LwkOpLnetQuery, (_in _Linknet linknet,
    _in _Domain domain, _in _QueryExpression expression,
    _in _Closure closure, _in _Callback routine));
_DeclareFunction(_Boolean LwkOpPersistSetState, (_inout _Linknet persistent,
    _in _PersistentState state, _in _StateOperation operation));
_DeclareFunction(void LwkOpLnetSetValue, (_inout _Linknet object,
    _in _String property_name, _in _Domain domain,
    _in _AnyPtr value, _in _SetFlag flag));
_DeclareFunction(void LwkOpLnetSetValueList, (_inout _Linknet object,
    _in _String property_name, _in _List_of(_Domain) value_list,
    _in _SetFlag flag));
_DeclareFunction(void LwkOpLnetStore, (_inout _Linknet linknet,
    _inout _Linkbase linkbase));

/*
** Linknet Type Instance Definition
*/

#define _LinknetTypeInstance \
    _TypeInstance _Constant LWK__LinknetTypeInstance = { \
        &LWK__PersistentTypeInstance, \
        sizeof(_LinknetInstance), \
        { \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjCopy, \
        (_Method) LwkOpObjCreate, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpLnetDecode, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpLnetDrop, \
        (_Method) LwkOpLnetEncode, \
        (_Method) LwkOpLnetEnumProps, \
        (_Method) LwkOpPersistExport, \
        (_Method) LwkOpObjExpunge, \
        (_Method) LwkOpLnetFree, \
        (_Method) LwkOpObjGetDomain, \
        (_Method) LwkOpPersistGetObjectDesc, \
        (_Method) LwkOpPersistGetObjectId, \
        (_Method) LwkOpLnetGetValue, \
        (_Method) LwkOpLnetGetValueDomain, \
        (_Method) LwkOpLnetGetValueList, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpPersistImport, \
        (_Method) LwkOpPersistImportKeyProperties, \
        (_Method) LwkOpLnetInitialize, \
        (_Method) LwkOpLnetIsMultiValued, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIsType, \
        (_Method) LwkOpLnetIterate, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpLnetQuery, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpPersistSetState, \
        (_Method) LwkOpLnetSetValue, \
        (_Method) LwkOpLnetSetValueList, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpLnetStore, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp \
        } \
    }

#define _LinknetType \
    _Type _Constant LWK__LinknetType = &LWK__LinknetTypeInstance
