/*
 * *****************************************************************
 * *                                                               *
 * *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
 * *                                                               *
 * *   All Rights Reserved.  Unpublished rights  reserved  under   *
 * *   the copyright laws of the United States.                    *
 * *                                                               *
 * *   The software contained on this media  is  proprietary  to   *
 * *   and  embodies  the  confidential  technology  of  Digital   *
 * *   Equipment Corporation.  Possession, use,  duplication  or   *
 * *   dissemination of the software and media is authorized only  *
 * *   pursuant to a valid written license from Digital Equipment  *
 * *   Corporation.                                                *
 * *                                                               *
 * *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
 * *   by the U.S. Government is subject to restrictions  as  set  *
 * *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
 * *   or  in  FAR 52.227-19, as applicable.                       *
 * *                                                               *
 * *****************************************************************
 */
/*
 * HISTORY
 */
/*
** Generated by ODL Version X0.1 on Tue Jul 14 18:32:24 1992
*/

/*
** COPYRIGHT (c) 1989 BY
** DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.
** ALL RIGHTS RESERVED.
**
** THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED
** ONLY  IN  ACCORDANCE  OF  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE
** INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER
** COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
** OTHER PERSON.  NO TITLE TO AND  OWNERSHIP OF THE  SOFTWARE IS  HEREBY
** TRANSFERRED.
**
** THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE
** AND  SHOULD  NOT  BE  CONSTRUED  AS A COMMITMENT BY DIGITAL EQUIPMENT
** CORPORATION.
**
** DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS
** SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
*/

/*
** Private Type Definitions for the DXmEnvState Object
*/

/*
** Abstract Type Definitions for subtypes of Object
*/

typedef _Object _List, _PtrTo _ListPtr;
typedef _Object _Set, _PtrTo _SetPtr;
typedef _Object _Property, _PtrTo _PropertyPtr;
typedef _Object _ObjectId, _PtrTo _ObjectIdPtr;
typedef _Object _ObjectDesc, _PtrTo _ObjectDescPtr;
typedef _Object _Ui, _PtrTo _UiPtr;
typedef _Object _DXmUi, _PtrTo _DXmUiPtr;
typedef _Object _Persistent, _PtrTo _PersistentPtr;
typedef _Object _Surrogate, _PtrTo _SurrogatePtr;
typedef _Object _Link, _PtrTo _LinkPtr;
typedef _Object _Linknet, _PtrTo _LinknetPtr;
typedef _Object _CompLinknet, _PtrTo _CompLinknetPtr;
typedef _Object _Step, _PtrTo _StepPtr;
typedef _Object _Path, _PtrTo _PathPtr;
typedef _Object _CompPath, _PtrTo _CompPathPtr;
typedef _Object _Linkbase, _PtrTo _LinkbasePtr;

/*
** DXmEnvState Instance Structure Definition
*/

typedef struct __DXmEnvState {
        _Type type;
        _Widget main_widget;
        _Integer address;
        _Set_of(_String) notifications;
        _Callback message_cb;
        _Callback notification_cb;
        _Closure user_data;
        struct __DXmEnvState *next;
        _Widget message_widget;
        _Atom message_type;
        _Atom validation_property;
        _Set_of(_Property) known_atoms;
        _Set_of(_Property) notification_atoms;
        _Transaction state;
    } _DXmEnvStateInstance, _PtrTo _DXmEnvState, _PtrTo _PtrTo _DXmEnvStatePtr;

/*
** DXmEnvState Property Name Table Index Definitions
*/

#define _MainWidgetIndex 0
#define _AddressIndex 1
#define _NotificationsIndex 2
#define _MessageCbIndex 3
#define _NotificationCbIndex 4
#define _UserDataIndex 5
#define _P_Next "$Next"
#define _NextIndex 6
#define _P_MessageWidget "$MessageWidget"
#define _MessageWidgetIndex 7
#define _P_CurrencyMessageType "$CurrencyMessageType"
#define _CurrencyMessageTypeIndex 8
#define _P_ValidationProperty "$ValidationProperty"
#define _ValidationPropertyIndex 9
#define _P_KnownAtoms "$KnownAtoms"
#define _KnownAtomsIndex 10
#define _P_NotificationAtoms "$NotificationAtoms"
#define _NotificationAtomsIndex 11
#define _P_TransactionState "$TransactionState"
#define _TransactionStateIndex 12

/*
** DXmEnvState Property Name Table Definition
*/

#define _DXmEnvStatePropertyNameTable \
    _PropertyNameTableEntry _Constant DXmEnvStatePropertyNameTable[] = { \
        {_P_MainWidget, _MainWidgetIndex, _True}, \
        {_P_Address, _AddressIndex, _True}, \
        {_P_Notifications, _NotificationsIndex, _True}, \
        {_P_MessageCb, _MessageCbIndex, _True}, \
        {_P_NotificationCb, _NotificationCbIndex, _True}, \
        {_P_UserData, _UserDataIndex, _True}, \
        {_P_Next, _NextIndex, _False}, \
        {_P_MessageWidget, _MessageWidgetIndex, _False}, \
        {_P_CurrencyMessageType, _CurrencyMessageTypeIndex, _False}, \
        {_P_ValidationProperty, _ValidationPropertyIndex, _False}, \
        {_P_KnownAtoms, _KnownAtomsIndex, _False}, \
        {_P_NotificationAtoms, _NotificationAtomsIndex, _False}, \
        {_P_TransactionState, _TransactionStateIndex, _False}, \
        {(_String) 0, 0, _False} \
    }

/*
** DXmEnvState Property Accessor Definitions
*/

#define _MainWidget_of(Obj) ((_DXmEnvState) _Reference(Obj))->main_widget
#define _Address_of(Obj) ((_DXmEnvState) _Reference(Obj))->address
#define _Notifications_of(Obj) ((_DXmEnvState) _Reference(Obj))->notifications
#define _MessageCb_of(Obj) ((_DXmEnvState) _Reference(Obj))->message_cb
#define _NotificationCb_of(Obj) ((_DXmEnvState) _Reference(Obj))->notification_cb
#define _UserData_of(Obj) ((_DXmEnvState) _Reference(Obj))->user_data
#define _Next_of(Obj) ((_DXmEnvState) _Reference(Obj))->next
#define _MessageWidget_of(Obj) ((_DXmEnvState) _Reference(Obj))->message_widget
#define _CurrencyMessageType_of(Obj) ((_DXmEnvState) _Reference(Obj))->message_type
#define _ValidationProperty_of(Obj) ((_DXmEnvState) _Reference(Obj))->validation_property
#define _KnownAtoms_of(Obj) ((_DXmEnvState) _Reference(Obj))->known_atoms
#define _NotificationAtoms_of(Obj) ((_DXmEnvState) _Reference(Obj))->notification_atoms
#define _TransactionState_of(Obj) ((_DXmEnvState) _Reference(Obj))->state

/*
** Include Generic Operation Support
*/

#include "lwk_operation_prototypes.h"

/*
** DXmEnvState Method Declarations
*/

_DeclareFunction(void LwkOpObjIllOp, (_in _Object object));
_DeclareFunction(_DXmEnvState LwkOpObjCopy, (_in _DXmEnvState object, _in _Boolean aggreate));
_DeclareFunction(_DXmEnvState LwkOpObjCreate, (_in _Type type));
_DeclareFunction(_Set LwkOpDXmStateEnumProps, (_in _DXmEnvState object));
_DeclareFunction(void LwkOpObjExpunge, (_inout _DXmEnvState object));
_DeclareFunction(void LwkOpDXmStateFree, (_inout _DXmEnvState object));
_DeclareFunction(_Domain LwkOpObjGetDomain, (_in _DXmEnvState object));
_DeclareFunction(void LwkOpDXmStateGetValue, (_in _DXmEnvState object,
    _in _String property_name, _in _Domain domain,
    _in _AnyPtr value));
_DeclareFunction(_Domain LwkOpDXmStateGetValueDomain, (_in _DXmEnvState object,
    _in _String property_name));
_DeclareFunction(_List LwkOpDXmStateGetValueList, (_in _DXmEnvState object,
    _in _String property_name));
_DeclareFunction(void LwkOpDXmStateInitialize, (_inout _DXmEnvState object,
    _in _DXmEnvState proto_object, _Boolean aggregate));
_DeclareFunction(_Boolean LwkOpDXmStateIsMultiValued, (_in _DXmEnvState object,
    _in _String property_name));
_DeclareFunction(_Boolean LwkOpObjIsType, (_in _DXmEnvState object,
    _in _Type type));
_DeclareFunction(void LwkOpDXmStateSendMessage, (_in _DXmEnvState object,
    _in _Integer address, _in _Integer size, _in _AnyPtr message));
_DeclareFunction(void LwkOpDXmStateSetValue, (_inout _DXmEnvState object,
    _in _String property_name, _in _Domain domain,
    _in _AnyPtr value, _in _SetFlag flag));
_DeclareFunction(void LwkOpDXmStateSetValueList, (_inout _DXmEnvState object,
    _in _String property_name, _in _List_of(_Domain) value_list,
    _in _SetFlag flag));
_DeclareFunction(_Transaction LwkOpDXmStateTransact, (_inout _DXmEnvState object,
    _in _Transaction transaction));

/*
** DXmEnvState Type Instance Definition
*/

#define _DXmEnvStateTypeInstance \
    _TypeInstance _Constant LWK__DXmEnvStateTypeInstance = { \
        &LWK__ObjectTypeInstance, \
        sizeof(_DXmEnvStateInstance), \
        { \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjCopy, \
        (_Method) LwkOpObjCreate, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpDXmStateEnumProps, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjExpunge, \
        (_Method) LwkOpDXmStateFree, \
        (_Method) LwkOpObjGetDomain, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpDXmStateGetValue, \
        (_Method) LwkOpDXmStateGetValueDomain, \
        (_Method) LwkOpDXmStateGetValueList, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpDXmStateInitialize, \
        (_Method) LwkOpDXmStateIsMultiValued, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIsType, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpDXmStateSendMessage, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpDXmStateSetValue, \
        (_Method) LwkOpDXmStateSetValueList, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpDXmStateTransact, \
        (_Method) LwkOpObjIllOp \
        } \
    }

#define _DXmEnvStateType \
    _Type _Constant LWK__DXmEnvStateType = &LWK__DXmEnvStateTypeInstance
