/*
 * *****************************************************************
 * *                                                               *
 * *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
 * *                                                               *
 * *   All Rights Reserved.  Unpublished rights  reserved  under   *
 * *   the copyright laws of the United States.                    *
 * *                                                               *
 * *   The software contained on this media  is  proprietary  to   *
 * *   and  embodies  the  confidential  technology  of  Digital   *
 * *   Equipment Corporation.  Possession, use,  duplication  or   *
 * *   dissemination of the software and media is authorized only  *
 * *   pursuant to a valid written license from Digital Equipment  *
 * *   Corporation.                                                *
 * *                                                               *
 * *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
 * *   by the U.S. Government is subject to restrictions  as  set  *
 * *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
 * *   or  in  FAR 52.227-19, as applicable.                       *
 * *                                                               *
 * *****************************************************************
 */
/*
 * HISTORY
 */
/*
** Generated by ODL Version X0.1 on Tue Jul 14 18:32:25 1992
*/

/*
** COPYRIGHT (c) 1989 BY
** DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.
** ALL RIGHTS RESERVED.
**
** THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED
** ONLY  IN  ACCORDANCE  OF  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE
** INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER
** COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
** OTHER PERSON.  NO TITLE TO AND  OWNERSHIP OF THE  SOFTWARE IS  HEREBY
** TRANSFERRED.
**
** THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE
** AND  SHOULD  NOT  BE  CONSTRUED  AS A COMMITMENT BY DIGITAL EQUIPMENT
** CORPORATION.
**
** DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS
** SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
*/

/*
** Private Type Definitions for the Persistent Object
*/

/*
** Abstract Type Definitions for subtypes of Object
*/

typedef _Object _List, _PtrTo _ListPtr;
typedef _Object _Set, _PtrTo _SetPtr;
typedef _Object _Property, _PtrTo _PropertyPtr;
typedef _Object _ObjectId, _PtrTo _ObjectIdPtr;
typedef _Object _ObjectDesc, _PtrTo _ObjectDescPtr;
typedef _Object _Ui, _PtrTo _UiPtr;
typedef _Object _DXmUi, _PtrTo _DXmUiPtr;
typedef _Object _DXmEnvState, _PtrTo _DXmEnvStatePtr;
typedef _Object _Surrogate, _PtrTo _SurrogatePtr;
typedef _Object _Link, _PtrTo _LinkPtr;
typedef _Object _Linknet, _PtrTo _LinknetPtr;
typedef _Object _CompLinknet, _PtrTo _CompLinknetPtr;
typedef _Object _Step, _PtrTo _StepPtr;
typedef _Object _Path, _PtrTo _PathPtr;
typedef _Object _CompPath, _PtrTo _CompPathPtr;
typedef _Object _Linkbase, _PtrTo _LinkbasePtr;

/*
** Persistent Instance Structure Definition
*/

typedef struct __Persistent {
        _Type type;
        _Linkbase linkbase;
        _Integer identifier;
        _DDIFString description;
        _DDIFString author;
        _Date creation_date;
        _Set_of(_DDIFString) keywords;
        _Set_of(_Property) properties;
        _StateFlags flags;
    } _PersistentInstance, _PtrTo _Persistent, _PtrTo _PtrTo _PersistentPtr;

/*
** Persistent Property Name Table Index Definitions
*/

#define _LinkbaseIndex 0
#define _IdentifierIndex 1
#define _DescriptionIndex 2
#define _AuthorIndex 3
#define _CreationDateIndex 4
#define _KeywordsIndex 5
#define _P_Properties "$Properties"
#define _PropertiesIndex 6
#define _P_StateFlags "$StateFlags"
#define _StateFlagsIndex 7

/*
** Persistent Property Name Table Definition
*/

#define _PersistentPropertyNameTable \
    _PropertyNameTableEntry _Constant PersistentPropertyNameTable[] = { \
        {_P_Linkbase, _LinkbaseIndex, _True}, \
        {_P_Identifier, _IdentifierIndex, _True}, \
        {_P_Description, _DescriptionIndex, _True}, \
        {_P_Author, _AuthorIndex, _True}, \
        {_P_CreationDate, _CreationDateIndex, _True}, \
        {_P_Keywords, _KeywordsIndex, _True}, \
        {_P_Properties, _PropertiesIndex, _False}, \
        {_P_StateFlags, _StateFlagsIndex, _False}, \
        {(_String) 0, 0, _False} \
    }

/*
** Persistent Property Accessor Definitions
*/

#define _Linkbase_of(Obj) ((_Persistent) _Reference(Obj))->linkbase
#define _Identifier_of(Obj) ((_Persistent) _Reference(Obj))->identifier
#define _Description_of(Obj) ((_Persistent) _Reference(Obj))->description
#define _Author_of(Obj) ((_Persistent) _Reference(Obj))->author
#define _CreationDate_of(Obj) ((_Persistent) _Reference(Obj))->creation_date
#define _Keywords_of(Obj) ((_Persistent) _Reference(Obj))->keywords
#define _Properties_of(Obj) ((_Persistent) _Reference(Obj))->properties
#define _StateFlags_of(Obj) ((_Persistent) _Reference(Obj))->flags

/*
** Include Generic Operation Support
*/

#include "lwk_operation_prototypes.h"

/*
** Persistent Method Declarations
*/

_DeclareFunction(void LwkOpObjIllOp, (_in _Object object));
_DeclareFunction(_Persistent LwkOpObjCopy, (_in _Persistent object, _in _Boolean aggreate));
_DeclareFunction(_Persistent LwkOpObjCreate, (_in _Type type));
_DeclareFunction(void LwkOpPersistDecode, (_inout _Persistent persistent,
    _in _DDIShandle handle, _in _Boolean keys_only,
    _inout _SetPtr properties));
_DeclareFunction(void LwkOpPersistEncode, (_in _Persistent persistent,
    _in _Boolean aggregate, _in _DDIShandle handle));
_DeclareFunction(_Set LwkOpPersistEnumProps, (_in _Persistent object));
_DeclareFunction(_Integer LwkOpPersistExport, (_in _Persistent persistent,
    _in _Boolean aggregate, _out _VaryingStringPtr encoding));
_DeclareFunction(void LwkOpObjExpunge, (_inout _Persistent object));
_DeclareFunction(void LwkOpPersistFree, (_inout _Persistent object));
_DeclareFunction(_Domain LwkOpObjGetDomain, (_in _Persistent object));
_DeclareFunction(_ObjectDesc LwkOpPersistGetObjectDesc, (
    _in _Persistent persistent));
_DeclareFunction(_ObjectId LwkOpPersistGetObjectId, (
    _in _Persistent persistent));
_DeclareFunction(void LwkOpPersistGetValue, (_in _Persistent object,
    _in _String property_name, _in _Domain domain,
    _in _AnyPtr value));
_DeclareFunction(_Domain LwkOpPersistGetValueDomain, (_in _Persistent object,
    _in _String property_name));
_DeclareFunction(_List LwkOpPersistGetValueList, (_in _Persistent object,
    _in _String property_name));
_DeclareFunction(_Persistent LwkOpPersistImport, (_in _Type type,
    _in _VaryingString encoding));
_DeclareFunction(void LwkOpPersistImportKeyProperties, (
    _in _Type type, _in _VaryingString encoding,
    _inout _SetPtr properties));
_DeclareFunction(void LwkOpPersistInitialize, (_inout _Persistent object,
    _in _Persistent proto_object, _Boolean aggregate));
_DeclareFunction(_Boolean LwkOpPersistIsMultiValued, (_in _Persistent object,
    _in _String property_name));
_DeclareFunction(_Boolean LwkOpObjIsType, (_in _Persistent object,
    _in _Type type));
_DeclareFunction(_Boolean LwkOpPersistSetState, (_inout _Persistent persistent,
    _in _PersistentState state, _in _StateOperation operation));
_DeclareFunction(void LwkOpPersistSetValue, (_inout _Persistent object,
    _in _String property_name, _in _Domain domain,
    _in _AnyPtr value, _in _SetFlag flag));
_DeclareFunction(void LwkOpPersistSetValueList, (_inout _Persistent object,
    _in _String property_name, _in _List_of(_Domain) value_list,
    _in _SetFlag flag));

/*
** Persistent Type Instance Definition
*/

#define _PersistentTypeInstance \
    _TypeInstance _Constant LWK__PersistentTypeInstance = { \
        &LWK__ObjectTypeInstance, \
        0, \
        { \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjCopy, \
        (_Method) LwkOpObjCreate, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpPersistDecode, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpPersistEncode, \
        (_Method) LwkOpPersistEnumProps, \
        (_Method) LwkOpPersistExport, \
        (_Method) LwkOpObjExpunge, \
        (_Method) LwkOpPersistFree, \
        (_Method) LwkOpObjGetDomain, \
        (_Method) LwkOpPersistGetObjectDesc, \
        (_Method) LwkOpPersistGetObjectId, \
        (_Method) LwkOpPersistGetValue, \
        (_Method) LwkOpPersistGetValueDomain, \
        (_Method) LwkOpPersistGetValueList, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpPersistImport, \
        (_Method) LwkOpPersistImportKeyProperties, \
        (_Method) LwkOpPersistInitialize, \
        (_Method) LwkOpPersistIsMultiValued, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIsType, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpPersistSetState, \
        (_Method) LwkOpPersistSetValue, \
        (_Method) LwkOpPersistSetValueList, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp \
        } \
    }

#define _PersistentType \
    _Type _Constant LWK__PersistentType = &LWK__PersistentTypeInstance
