/*
 * *****************************************************************
 * *                                                               *
 * *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
 * *                                                               *
 * *   All Rights Reserved.  Unpublished rights  reserved  under   *
 * *   the copyright laws of the United States.                    *
 * *                                                               *
 * *   The software contained on this media  is  proprietary  to   *
 * *   and  embodies  the  confidential  technology  of  Digital   *
 * *   Equipment Corporation.  Possession, use,  duplication  or   *
 * *   dissemination of the software and media is authorized only  *
 * *   pursuant to a valid written license from Digital Equipment  *
 * *   Corporation.                                                *
 * *                                                               *
 * *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
 * *   by the U.S. Government is subject to restrictions  as  set  *
 * *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
 * *   or  in  FAR 52.227-19, as applicable.                       *
 * *                                                               *
 * *****************************************************************
 */
/*
 * HISTORY
 */
/*
** Generated by ODL Version X0.1 on Tue Jul 14 18:32:23 1992
*/

/*
** COPYRIGHT (c) 1989 BY
** DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.
** ALL RIGHTS RESERVED.
**
** THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED
** ONLY  IN  ACCORDANCE  OF  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE
** INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER
** COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
** OTHER PERSON.  NO TITLE TO AND  OWNERSHIP OF THE  SOFTWARE IS  HEREBY
** TRANSFERRED.
**
** THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE
** AND  SHOULD  NOT  BE  CONSTRUED  AS A COMMITMENT BY DIGITAL EQUIPMENT
** CORPORATION.
**
** DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS
** SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
*/

/*
** Private Type Definitions for the DXmUi Object
*/

/*
** Abstract Type Definitions for subtypes of Object
*/

typedef _Object _List, _PtrTo _ListPtr;
typedef _Object _Set, _PtrTo _SetPtr;
typedef _Object _Property, _PtrTo _PropertyPtr;
typedef _Object _ObjectId, _PtrTo _ObjectIdPtr;
typedef _Object _ObjectDesc, _PtrTo _ObjectDescPtr;
typedef _Object _Ui, _PtrTo _UiPtr;
typedef _Object _DXmEnvState, _PtrTo _DXmEnvStatePtr;
typedef _Object _Persistent, _PtrTo _PersistentPtr;
typedef _Object _Surrogate, _PtrTo _SurrogatePtr;
typedef _Object _Link, _PtrTo _LinkPtr;
typedef _Object _Linknet, _PtrTo _LinknetPtr;
typedef _Object _CompLinknet, _PtrTo _CompLinknetPtr;
typedef _Object _Step, _PtrTo _StepPtr;
typedef _Object _Path, _PtrTo _PathPtr;
typedef _Object _CompPath, _PtrTo _CompPathPtr;
typedef _Object _Linkbase, _PtrTo _LinkbasePtr;

/*
** DXmUi Instance Structure Definition
*/

typedef struct __DXmUi {
        _Type type;
        _Set_of(_String) surrogate_types;
        _Set_of(_String) operations;
        _String default_operation;
        _HighlightFlags default_highlight;
        _DDIFString default_relationship;
        _Boolean default_retain_source;
        _Boolean default_retain_target;
        _ObjectId active_clinknet;
        _ObjectId active_cpath;
        _ObjectId recording_linknet;
        _ObjectId active_path;
        _Integer active_path_index;
        _ObjectId recording_path;
        _ObjectId new_link;
        _ObjectId followed_link;
        _ObjectId followed_step;
        _ObjectId pending_source;
        _ObjectId pending_target;
        _ObjectId follow_destination;
        _HighlightFlags appl_highlight;
        _Boolean retain_source;
        _Boolean retain_target;
        _Closure user_data;
        _Callback get_surrogate_cb;
        _Callback create_surrogate_cb;
        _Callback close_view_cb;
        _Callback apply_cb;
        _Callback complete_link_cb;
        _Callback environment_change_cb;
        _DXmEnvState environment_state;
        _Boolean environment_manager;
        _AnyPtr client_list;
        _Path history;
        _Integer step_destination;
        _Link pending_link;
        _Integer pending_source_owner;
        _Integer pending_target_owner;
        _AnyPtr private_data;
    } _DXmUiInstance, _PtrTo _DXmUi, _PtrTo _PtrTo _DXmUiPtr;

/*
** DXmUi Property Name Table Index Definitions
*/

#define _P_PrivateData "$PrivateData"
#define _PrivateDataIndex 0

/*
** DXmUi Property Name Table Definition
*/

#define _DXmUiPropertyNameTable \
    _PropertyNameTableEntry _Constant DXmUiPropertyNameTable[] = { \
        {_P_PrivateData, _PrivateDataIndex, _False}, \
        {(_String) 0, 0, _False} \
    }

/*
** DXmUi Property Accessor Definitions
*/

#define _PrivateData_of(Obj) ((_DXmUi) _Reference(Obj))->private_data

/*
** Include Generic Operation Support
*/

#include "lwk_operation_prototypes.h"

/*
** DXmUi Method Declarations
*/

_DeclareFunction(void LwkOpObjIllOp, (_in _Object object));
_DeclareFunction(void LwkOpUiNavApply, (_in _DXmUi ui, _in _String operation,
    _in _Surrogate surrogate));
_DeclareFunction(void LwkOpDXmUiCompleteLink, (_inout _DXmUi dxmui,
    _in _Link link, _in _Boolean iff_visible,
    _Closure closure));
_DeclareFunction(void LwkOpUiNavConfirmApply, (
    _in _DXmUi ui, _in _Surrogate surrogate));
_DeclareFunction(void LwkOpUiNavConfirmLink, (
    _in _DXmUi ui, _in _Boolean confirmed,
    _in _Boolean retain_source, _in _Boolean retain_target));
_DeclareFunction(_DXmUi LwkOpObjCopy, (_in _DXmUi object, _in _Boolean aggreate));
_DeclareFunction(_DXmUi LwkOpObjCreate, (_in _Type type));
_DeclareFunction(_DXmUi LwkOpDXmUiCreate, (_in _Type type,
    _in _CString appl_name, _in _Boolean create_menu,
    _in _Boolean default_accelerators, _in _Widget main_window,
    _in _Widget link_menu));
_DeclareFunction(void LwkOpDXmUiDisplayMessage, (_in _DXmUi dxmui,
    _in _StatusPtr status, _in _Integer count));
_DeclareFunction(_Set LwkOpDXmUiEnumProps, (_in _DXmUi object));
_DeclareFunction(void LwkOpObjExpunge, (_inout _DXmUi object));
_DeclareFunction(void LwkOpDXmUiFree, (_inout _DXmUi object));
_DeclareFunction(_Domain LwkOpObjGetDomain, (_in _DXmUi object));
_DeclareFunction(void LwkOpDXmUiGetValue, (_in _DXmUi object,
    _in _String property_name, _in _Domain domain,
    _in _AnyPtr value));
_DeclareFunction(_Domain LwkOpDXmUiGetValueDomain, (_in _DXmUi object,
    _in _String property_name));
_DeclareFunction(_List LwkOpDXmUiGetValueList, (_in _DXmUi object,
    _in _String property_name));
_DeclareFunction(void LwkOpDXmUiHighlight, (_inout _DXmUi dxmui));
_DeclareFunction(void LwkOpDXmUiInitialize, (_inout _DXmUi object,
    _in _DXmUi proto_object, _Boolean aggregate));
_DeclareFunction(_Boolean LwkOpDXmUiIsMultiValued, (_in _DXmUi object,
    _in _String property_name));
_DeclareFunction(_Boolean LwkOpObjIsType, (_in _DXmUi object,
    _in _Type type));
_DeclareFunction(void LwkOpUiNavNavigate, (_in _DXmUi ui,
    _in _Link link, _in _Surrogate origin,
    _in _Surrogate destination, _in _String Operation,
    _in _FollowType follow_type));
_DeclareFunction(void LwkOpUiNavSelectMenu, (_inout _DXmUi ui,
    _in _Menu menu, _in _Closure closure));
_DeclareFunction(void LwkOpDXmUiSetValue, (_inout _DXmUi object,
    _in _String property_name, _in _Domain domain,
    _in _AnyPtr value, _in _SetFlag flag));
_DeclareFunction(void LwkOpDXmUiSetValueList, (_inout _DXmUi object,
    _in _String property_name, _in _List_of(_Domain) value_list,
    _in _SetFlag flag));
_DeclareFunction(void LwkOpDXmUiShowHistory, (_inout _DXmUi dxmui,
    _in _List_of(_Step) steps,
    _in _List_of(_List_of(_String)) origin_opr_ids,
    _in _List_of(_List_of(_DDIFString)) origin_opr_names,
    _in _List_of(_List_of(_String)) dest_opr_ids,
    _in _List_of(_List_of(_DDIFString)) dest_opr_names,
    _in _Boolean iff_visible, _Closure closure));
_DeclareFunction(void LwkOpDXmUiShowLinks, (_inout _DXmUi dxmui,
    _in _List_of(_Link) links,
    _in _List_of(_List_of(_String)) opr_ids,
    _in _List_of(_List_of(_DDIFString)) opr_names,
    _in _List_of(_Boolean) outgoing, _in _FollowType follow_type,
    _in _Boolean iff_visible, _in _Boolean update, 
    _in _Closure closure));
_DeclareFunction(_Boolean LwkOpUiNavSurrIsHighlighted, (
    _in _DXmUi ui, _in _Surrogate surrogate));

/*
** DXmUi Type Instance Definition
*/

#define _DXmUiTypeInstance \
    _TypeInstance _Constant LWK__DXmUiTypeInstance = { \
        &LWK__UiTypeInstance, \
        sizeof(_DXmUiInstance), \
        { \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpUiNavApply, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpDXmUiCompleteLink, \
        (_Method) LwkOpUiNavConfirmApply, \
        (_Method) LwkOpUiNavConfirmLink, \
        (_Method) LwkOpObjCopy, \
        (_Method) LwkOpObjCreate, \
        (_Method) LwkOpDXmUiCreate, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpDXmUiDisplayMessage, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpDXmUiEnumProps, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjExpunge, \
        (_Method) LwkOpDXmUiFree, \
        (_Method) LwkOpObjGetDomain, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpDXmUiGetValue, \
        (_Method) LwkOpDXmUiGetValueDomain, \
        (_Method) LwkOpDXmUiGetValueList, \
        (_Method) LwkOpDXmUiHighlight, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpDXmUiInitialize, \
        (_Method) LwkOpDXmUiIsMultiValued, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIsType, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpUiNavNavigate, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpUiNavSelectMenu, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpDXmUiSetValue, \
        (_Method) LwkOpDXmUiSetValueList, \
        (_Method) LwkOpDXmUiShowHistory, \
        (_Method) LwkOpDXmUiShowLinks, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpUiNavSurrIsHighlighted, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp \
        } \
    }

#define _DXmUiType \
    _Type _Constant LWK__DXmUiType = &LWK__DXmUiTypeInstance
