/*
 * *****************************************************************
 * *                                                               *
 * *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
 * *                                                               *
 * *   All Rights Reserved.  Unpublished rights  reserved  under   *
 * *   the copyright laws of the United States.                    *
 * *                                                               *
 * *   The software contained on this media  is  proprietary  to   *
 * *   and  embodies  the  confidential  technology  of  Digital   *
 * *   Equipment Corporation.  Possession, use,  duplication  or   *
 * *   dissemination of the software and media is authorized only  *
 * *   pursuant to a valid written license from Digital Equipment  *
 * *   Corporation.                                                *
 * *                                                               *
 * *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
 * *   by the U.S. Government is subject to restrictions  as  set  *
 * *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
 * *   or  in  FAR 52.227-19, as applicable.                       *
 * *                                                               *
 * *****************************************************************
 */
/*
 * HISTORY
 */
/*
** Generated by ODL Version X0.1 on Tue Jul 14 18:32:28 1992
*/

/*
** COPYRIGHT (c) 1989 BY
** DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.
** ALL RIGHTS RESERVED.
**
** THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED
** ONLY  IN  ACCORDANCE  OF  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE
** INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER
** COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
** OTHER PERSON.  NO TITLE TO AND  OWNERSHIP OF THE  SOFTWARE IS  HEREBY
** TRANSFERRED.
**
** THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE
** AND  SHOULD  NOT  BE  CONSTRUED  AS A COMMITMENT BY DIGITAL EQUIPMENT
** CORPORATION.
**
** DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS
** SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
*/

/*
** Private Type Definitions for the CompLinknet Object
*/

/*
** Abstract Type Definitions for subtypes of Object
*/

typedef _Object _List, _PtrTo _ListPtr;
typedef _Object _Set, _PtrTo _SetPtr;
typedef _Object _Property, _PtrTo _PropertyPtr;
typedef _Object _ObjectId, _PtrTo _ObjectIdPtr;
typedef _Object _ObjectDesc, _PtrTo _ObjectDescPtr;
typedef _Object _Ui, _PtrTo _UiPtr;
typedef _Object _DXmUi, _PtrTo _DXmUiPtr;
typedef _Object _DXmEnvState, _PtrTo _DXmEnvStatePtr;
typedef _Object _Persistent, _PtrTo _PersistentPtr;
typedef _Object _Surrogate, _PtrTo _SurrogatePtr;
typedef _Object _Link, _PtrTo _LinkPtr;
typedef _Object _Linknet, _PtrTo _LinknetPtr;
typedef _Object _Step, _PtrTo _StepPtr;
typedef _Object _Path, _PtrTo _PathPtr;
typedef _Object _CompPath, _PtrTo _CompPathPtr;
typedef _Object _Linkbase, _PtrTo _LinkbasePtr;

/*
** CompLinknet Instance Structure Definition
*/

typedef struct __CompLinknet {
        _Type type;
        _Linkbase linkbase;
        _Integer identifier;
        _DDIFString description;
        _DDIFString author;
        _Date creation_date;
        _Set_of(_DDIFString) keywords;
        _Set_of(_Property) properties;
        _StateFlags flags;
        _DDIFString name;
        _Set_of(_ObjectDesc) linknets;
    } _CompLinknetInstance, _PtrTo _CompLinknet, _PtrTo _PtrTo _CompLinknetPtr;

/*
** CompLinknet Property Name Table Index Definitions
*/

#define _NameIndex 0
#define _LinknetsIndex 1

/*
** CompLinknet Property Name Table Definition
*/

#define _CompLinknetPropertyNameTable \
    _PropertyNameTableEntry _Constant CompLinknetPropertyNameTable[] = { \
        {_P_Name, _NameIndex, _True}, \
        {_P_Linknets, _LinknetsIndex, _True}, \
        {(_String) 0, 0, _False} \
    }

/*
** CompLinknet Property Accessor Definitions
*/

#define _Name_of(Obj) ((_CompLinknet) _Reference(Obj))->name
#define _Linknets_of(Obj) ((_CompLinknet) _Reference(Obj))->linknets

/*
** Include Generic Operation Support
*/

#include "lwk_operation_prototypes.h"

/*
** CompLinknet Method Declarations
*/

_DeclareFunction(void LwkOpObjIllOp, (_in _Object object));
_DeclareFunction(_CompLinknet LwkOpObjCopy, (_in _CompLinknet object, _in _Boolean aggreate));
_DeclareFunction(_CompLinknet LwkOpObjCreate, (_in _Type type));
_DeclareFunction(void LwkOpCLnetDecode, (_inout _CompLinknet persistent,
    _in _DDIShandle handle, _in _Boolean keys_only,
    _inout _SetPtr properties));
_DeclareFunction(void LwkOpCLnetDrop, (_inout _CompLinknet composite_linknet));
_DeclareFunction(void LwkOpCLnetEncode, (_in _CompLinknet persistent,
    _in _Boolean aggregate, _in _DDIShandle handle));
_DeclareFunction(_Set LwkOpCLnetEnumProps, (_in _CompLinknet object));
_DeclareFunction(_Integer LwkOpPersistExport, (_in _CompLinknet persistent,
    _in _Boolean aggregate, _out _VaryingStringPtr encoding));
_DeclareFunction(void LwkOpObjExpunge, (_inout _CompLinknet object));
_DeclareFunction(void LwkOpCLnetFree, (_inout _CompLinknet object));
_DeclareFunction(_Domain LwkOpObjGetDomain, (_in _CompLinknet object));
_DeclareFunction(_ObjectDesc LwkOpPersistGetObjectDesc, (
    _in _CompLinknet persistent));
_DeclareFunction(_ObjectId LwkOpPersistGetObjectId, (
    _in _CompLinknet persistent));
_DeclareFunction(void LwkOpCLnetGetValue, (_in _CompLinknet object,
    _in _String property_name, _in _Domain domain,
    _in _AnyPtr value));
_DeclareFunction(_Domain LwkOpCLnetGetValueDomain, (_in _CompLinknet object,
    _in _String property_name));
_DeclareFunction(_List LwkOpCLnetGetValueList, (_in _CompLinknet object,
    _in _String property_name));
_DeclareFunction(_CompLinknet LwkOpPersistImport, (_in _Type type,
    _in _VaryingString encoding));
_DeclareFunction(void LwkOpPersistImportKeyProperties, (
    _in _Type type, _in _VaryingString encoding,
    _inout _SetPtr properties));
_DeclareFunction(void LwkOpCLnetInitialize, (_inout _CompLinknet object,
    _in _CompLinknet proto_object, _Boolean aggregate));
_DeclareFunction(_Boolean LwkOpCLnetIsMultiValued, (_in _CompLinknet object,
    _in _String property_name));
_DeclareFunction(_Boolean LwkOpObjIsType, (_in _CompLinknet object,
    _in _Type type));
_DeclareFunction(_Termination LwkOpCLnetIterate, (_in _CompLinknet composite_linknet,
    _in _Domain domain, _in _Closure closure,
    _in _Callback routine));
_DeclareFunction(_Termination LwkOpCLnetQuery, (_in _CompLinknet composite_linknet,
    _in _Domain domain, _in _QueryExpression expression,
    _in _Closure closure, _in _Callback routine));
_DeclareFunction(_Boolean LwkOpPersistSetState, (_inout _CompLinknet persistent,
    _in _PersistentState state, _in _StateOperation operation));
_DeclareFunction(void LwkOpCLnetSetValue, (_inout _CompLinknet object,
    _in _String property_name, _in _Domain domain,
    _in _AnyPtr value, _in _SetFlag flag));
_DeclareFunction(void LwkOpCLnetSetValueList, (_inout _CompLinknet object,
    _in _String property_name, _in _List_of(_Domain) value_list,
    _in _SetFlag flag));
_DeclareFunction(void LwkOpCLnetStore, (_inout _CompLinknet composite_linknet,
    _inout _Linkbase linkbase));

/*
** CompLinknet Type Instance Definition
*/

#define _CompLinknetTypeInstance \
    _TypeInstance _Constant LWK__CompLinknetTypeInstance = { \
        &LWK__PersistentTypeInstance, \
        sizeof(_CompLinknetInstance), \
        { \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjCopy, \
        (_Method) LwkOpObjCreate, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpCLnetDecode, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpCLnetDrop, \
        (_Method) LwkOpCLnetEncode, \
        (_Method) LwkOpCLnetEnumProps, \
        (_Method) LwkOpPersistExport, \
        (_Method) LwkOpObjExpunge, \
        (_Method) LwkOpCLnetFree, \
        (_Method) LwkOpObjGetDomain, \
        (_Method) LwkOpPersistGetObjectDesc, \
        (_Method) LwkOpPersistGetObjectId, \
        (_Method) LwkOpCLnetGetValue, \
        (_Method) LwkOpCLnetGetValueDomain, \
        (_Method) LwkOpCLnetGetValueList, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpPersistImport, \
        (_Method) LwkOpPersistImportKeyProperties, \
        (_Method) LwkOpCLnetInitialize, \
        (_Method) LwkOpCLnetIsMultiValued, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIsType, \
        (_Method) LwkOpCLnetIterate, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpCLnetQuery, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpPersistSetState, \
        (_Method) LwkOpCLnetSetValue, \
        (_Method) LwkOpCLnetSetValueList, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpCLnetStore, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp, \
        (_Method) LwkOpObjIllOp \
        } \
    }

#define _CompLinknetType \
    _Type _Constant LWK__CompLinknetType = &LWK__CompLinknetTypeInstance
