/*
 * *****************************************************************
 * *                                                               *
 * *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
 * *                                                               *
 * *   All Rights Reserved.  Unpublished rights  reserved  under   *
 * *   the copyright laws of the United States.                    *
 * *                                                               *
 * *   The software contained on this media  is  proprietary  to   *
 * *   and  embodies  the  confidential  technology  of  Digital   *
 * *   Equipment Corporation.  Possession, use,  duplication  or   *
 * *   dissemination of the software and media is authorized only  *
 * *   pursuant to a valid written license from Digital Equipment  *
 * *   Corporation.                                                *
 * *                                                               *
 * *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
 * *   by the U.S. Government is subject to restrictions  as  set  *
 * *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
 * *   or  in  FAR 52.227-19, as applicable.                       *
 * *                                                               *
 * *****************************************************************
 */
/*
 * HISTORY
 */
#ifndef lint
static char *rcsid = "@(#)$RCSfile: ffbgenffb.c,v $ $Revision: 1.1.2.2 $ (DEC) $Date: 1993/11/19 21:10:31 $";
#endif
/*
 */

#include <stdio.h>
#include "ffb.h"
#include "ffbblt.h"

CommandWord RightBitMask(i)
    int i;
{
    CommandWord mask;

    /* Start mask as 0000...1111, with FFBCOPYPIXELALIGNMENT 1's. */
    mask = FFBCOPYALL1 >> (FFBCOPYBITS - FFBCOPYPIXELALIGNMENT);
    /* Shift to get desired pattern in lowest FFBCOPYPIXELALIGNMENT bits. */
    mask >>= ((-(i+1)) & FFBCOPYPIXELALIGNMASK);
    /* Or in 1's in high bits. */
    mask |= (FFBCOPYALL1 << FFBCOPYPIXELALIGNMENT);
    /* Shift left FFBCOPYPIXELALIGNMENT bits if needed. */
    mask <<= ((FFBCOPYPIXELALIGNMASK-i) & ~FFBCOPYPIXELALIGNMASK);
    /* Junk any high bits that got turned on. */
    mask &= FFBCOPYALL1;
    return mask;
} /* RightBitMask */

#define SHIFTMASK   (~FFBCOPYPIXELALIGNMASK & FFBCOPYBITSMASK)

CommandWord LeftBitMask(i)
    int i;
{
    CommandWord mask;
    int shift;

    /* Start mask as 0000...1111, where there are FFBCOPYPIXELALIGNMENT 1's. */
    mask = FFBCOPYALL1 >> (FFBCOPYBITS - FFBCOPYPIXELALIGNMENT);
    /* Shift to get desired pattern in lowest FFBCOPYPIXELALIGNMENT bits. */
    shift = -i & FFBCOPYPIXELALIGNMASK;
    mask = (mask >> shift) << shift;
    /* Shift left as needed */
    mask <<= (i-1) & SHIFTMASK;
    /* Or in 1's in low bits. */
    mask |= (FFBCOPYALL1 >> (-i & SHIFTMASK)) >> FFBCOPYPIXELALIGNMENT;
    /* Junk any high bits */
    mask &= FFBCOPYALL1;
    return mask;
} /* LeftBitMask */


main() {
    int i;

    printf("/* DO NOT MODIFY.  AUTOMATICALLY GENERATED BY ffbgenffb.c */\n");
    printf("\n");
    printf("#include \"ffb.h\"\n");
    printf("#include \"ffbblt.h\"\n");
    printf("#include \"ffbdma.h\"\n");
    printf("\n");

    printf("/* By assigning a global variable, we can actually get these */\n");
    printf("/* values into registers.  Compiler otherwise keeps loading */\n");
    printf("/* them again and again. */\n");
    printf("CommandWord ffbBusAll1 = FFBBUSALL1;\n");
    printf("CommandWord ffbOnesDMA = FFBDMAREAD_ONES;\n");
    printf("CommandWord ffbStippleAll1 = FFBSTIPPLEALL1;\n");
    printf("CommandWord ffbCopyAll1 = FFBCOPYALL1;\n");
    printf("CommandWord ffbSimpleAll1 = FFBSIMPLEALL1;\n");
    printf("\n");

    printf("CommandWord ffbBackRightMask[2*FFBCOPYPIXELALIGNMENT] = {\n");
    for (i = -FFBCOPYPIXELALIGNMENT; i < FFBCOPYPIXELALIGNMENT; i++) {
	printf("    /* %3d */  0x%08lx,\n", i, RightBitMask(i));
    }
    printf("}; /* ffbBackRightMask */\n");
    printf("\n");
    printf("CommandWord ffbBackLeftMask[FFBCOPYBITS] = {\n");
    for (i = 0; i < FFBCOPYBITS; i++) {
	printf("    /* %3d */  0x%08lx,\n", i, LeftBitMask(i));
    }
    printf("}; /* ffbBackLeftMask */\n");
    printf("\n");
}

/*
 * HISTORY
 */
