 
$ *****************************************************************
$ *                                                               *
$ *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
$ *                                                               *
$ *   All Rights Reserved.  Unpublished rights  reserved  under   *
$ *   the copyright laws of the United States.                    *
$ *                                                               *
$ *   The software contained on this media  is  proprietary  to   *
$ *   and  embodies  the  confidential  technology  of  Digital   *
$ *   Equipment Corporation.  Possession, use,  duplication  or   *
$ *   dissemination of the software and media is authorized only  *
$ *   pursuant to a valid written license from Digital Equipment  *
$ *   Corporation.                                                *
$ *                                                               *
$ *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
$ *   by the U.S. Government is subject to restrictions  as  set  *
$ *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
$ *   or  in  FAR 52.227-19, as applicable.                       *
$ *                                                               *
$ *****************************************************************
$
$ HISTORY
 
$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0

$
$ @(#)$RCSfile: pw.msg,v $ $Revision: 4.2 $ (DEC) $Date: 1991/09/20 02:42:51 $
$ COMPONENT_NAME: (LIBPW) Programmers Workbench Library
$
$ FUNCTIONS: 
$
$ ORIGINS: 27 
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$ OBJECT CODE ONLY SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

$set MS_PW
$quote "
STOVFL "regex: stack overflow\n"
XNODIR "directory `%s' does not exist (ut1)"
XNOLINK "cannot link `%s' to `%s' (ut%d)"
XTABFULL "file table full (ut3)"
XNOFILE "`%s' does not exist (ut4)"
XNODWRT "directory `%s' unwritable (ut2)"
XNOSPC "no space! (ut10)"
XTOOBIG "file too big (ut8)"
XERRNO "errno = %d"
XFUNC "%s, function = `%s' (ut11)"
XNORD "`%s' unreadable (ut5)"
XNOWRT "`%s' unwritable (ut6)"
XNORDWRT "`%s' unreadable or unwritable (ut7)"
ERROR "ERROR"
