$ *****************************************************************
$ *                                                               *
$ *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
$ *                                                               *
$ *   All Rights Reserved.  Unpublished rights  reserved  under   *
$ *   the copyright laws of the United States.                    *
$ *                                                               *
$ *   The software contained on this media  is  proprietary  to   *
$ *   and  embodies  the  confidential  technology  of  Digital   *
$ *   Equipment Corporation.  Possession, use,  duplication  or   *
$ *   dissemination of the software and media is authorized only  *
$ *   pursuant to a valid written license from Digital Equipment  *
$ *   Corporation.                                                *
$ *                                                               *
$ *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
$ *   by the U.S. Government is subject to restrictions  as  set  *
$ *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
$ *   or  in  FAR 52.227-19, as applicable.                       *
$ *                                                               *
$ *****************************************************************
$ 
$ HISTORY
$
$
$ Copyright (c) 1988-91 SecureWare, Inc.
$   All rights reserved.
$
$ @(#)lsacl.msg	1.2 17:02:43 9/3/91 SecureWare
$
$quote "
$set MS_LSACL

LSUSAGE		"Usage: lsacl [ -d ] filenames.\n"
READERR		"%s: Error reading acl of \"%s\""
DEFREADERR	"%s: \"%s\" does not have a default acl.\n"
STATERR		"%s: Failed stat of \"%s\".\n"
MALLOCERR	"%s: Memory allocation error.\n"

