$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0
$quote "
$set MS_MKPROTO

USAGE		"usage: mkproto filsys proto\n"
BADOCT		"%c/%s: bad octal mode digit\n"
CANNOTOP	"%s: cannot open\n"
BADMODE		"%c/%s: bad mode\n"
BADNUM		"%s: bad number\n"
UNXEOF		"Unexpected EOF\n"
DIRLARG		"directory too large\n"
INDBLKFULL	"indirect block full\n"
BADMOD2		"bad mode %o\n"
MAGICNUM	"cg %d: bad magic number\n"
NOSPACE		"ran out of space\n"
CYL		"internal error: can't find block in cyl %d\n"
FSINIT		"fsinit: inode value out of range (%lu).\n"
SEEK		"seek error: %d\n"
RDFS		"rdfs"
READ		"read error: %d\n"
WTFS		"wtfs"
WRITE		"write error: %d\n"
ISBLOCK		"isblock bad fs_frag %ld\n"
CLRBLOCK	"clrblock bad fs_frag %ld\n"
