$ 
$ *****************************************************************
$ *                                                               *
$ *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
$ *                                                               *
$ *   All Rights Reserved.  Unpublished rights  reserved  under   *
$ *   the copyright laws of the United States.                    *
$ *                                                               *
$ *   The software contained on this media  is  proprietary  to   *
$ *   and  embodies  the  confidential  technology  of  Digital   *
$ *   Equipment Corporation.  Possession, use,  duplication  or   *
$ *   dissemination of the software and media is authorized only  *
$ *   pursuant to a valid written license from Digital Equipment  *
$ *   Corporation.                                                *
$ *                                                               *
$ *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
$ *   by the U.S. Government is subject to restrictions  as  set  *
$ *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
$ *   or  in  FAR 52.227-19, as applicable.                       *
$ *                                                               *
$ *****************************************************************
$
$ HISTORY
$ 
$ @(#)$RCSfile: xpg4demo_ja_JP.SJIS.msg,v $ $Revision: 1.1.2.2 $ (DEC) $Date: 1993/06/25 22:04:26 $
$ 
$ /*
$  * XPG4 demo program message catalogue
$  *
$  */

$quote "

$set MSGError

E_COM_EXISTBADGE	"ŽÐˆõ”Ô† %ld ‚ÍŠù‚É‘¶Ý‚µ‚Ü‚·"
E_COM_FINDBADGE		"ŽÐˆõ”Ô† %ld ‚ªŒ©‚Â‚©‚è‚Ü‚¹‚ñ"
E_COM_INPUT		"“ü—Í‚Å‚«‚Ü‚¹‚ñ"
E_COM_MODIFY		"•ÏX‚·‚éƒGƒ“ƒgƒŠ‚ª‘¶Ý‚µ‚Ü‚¹‚ñ"
E_COM_NOENT		"ƒGƒ“ƒgƒŠ‚ª‘¶Ý‚µ‚Ü‚¹‚ñ"
E_COM_NOTDEL		"íœ‚·‚éƒGƒ“ƒgƒŠ‚ª‘¶Ý‚µ‚Ü‚¹‚ñ"
E_COM_UNKNOWN		"–¢’è‹`ƒRƒ}ƒ“ƒh‚Å‚·"
E_DB_NOMEMORY		"ŽÐˆõƒf[ƒ^"
E_DB_WRITEOPEN		"o—Íƒtƒ@ƒCƒ‹ %s ‚ªƒI[ƒvƒ“‚Å‚«‚Ü‚¹‚ñ"
E_MES_ABORT		". ‹­§I—¹‚µ‚Ü‚·B\n"
E_MES_FATAL2		". ˆÙíI—¹‚µ‚Ü‚·\n"
E_MES_NOMEMORY		"%s —pƒƒ‚ƒŠ‚ª‚ ‚è‚Ü‚¹‚ñ"
E_SCR_INV_BADGE		"ŽÐˆõ”Ô†‚ª³‚µ‚­‚ ‚è‚Ü‚¹‚ñ"
E_SCR_INV_CC		"ƒRƒXƒgƒZƒ“ƒ^[‚ª³‚µ‚­‚ ‚è‚Ü‚¹‚ñ"
E_SCR_INV_JOD		"“ú•t‚ª³‚µ‚­‚ ‚è‚Ü‚¹‚ñ"
E_SCR_2LONG_1STNM	"–¼‘O‚ª’·‚·‚¬‚Ü‚·"
E_SCR_NOMEMORY		"ƒXƒNƒŠ[ƒ“\‘¢‘Ì"
E_SCR_2LONG_SURNM	"©–¼‚ª’·‚·‚¬‚Ü‚·"
E_SCR_UNKOWN_TERM	"ƒ^[ƒ~ƒiƒ‹–¼‚ª•ª‚©‚è‚Ü‚¹‚ñ. \"ansi\" ‚Ås‚¢‚Ü‚·"
E_SCR_TERMCAP_OPEN	"termcap/terminfo ƒf[ƒ^ƒx[ƒX‚ªƒI[ƒvƒ“‚Å‚«‚Ü‚¹‚ñ"
E_SCR_TERMNOMEM		"termcap ƒoƒbƒtƒ@"
E_SCR_UNDEFTERM		"ƒ^[ƒ~ƒiƒ‹Eƒ^ƒCƒv %s ‚ª’è‹`‚³‚ê‚Ä‚¢‚Ü‚¹‚ñ"
E_UTL_NOMEMORY		"ƒƒbƒZ[ƒWEƒf[ƒ^"
E_XPG_DBREAD		"ƒf[ƒ^ƒx[ƒX‚Í“Ç‚ÝŽæ‚èê—p‚Å‚·Bo—Íƒtƒ@ƒCƒ‹‚Íì‚ê‚Ü‚¹‚ñ"
E_XPG_INIT_COM		"ƒRƒ}ƒ“ƒhŠÂ‹«‚ð‰Šú‰»‚Å‚«‚Ü‚¹‚ñ"
E_XPG_INIT_SCR		"ƒXƒNƒŠ[ƒ“‚Ì‰Šú‰»‚ª‚Å‚«‚Ü‚¹‚ñ"
E_XPG_NEWFILE		"V‹Kƒtƒ@ƒCƒ‹"
E_XPG_NOMEMORY		"ƒƒ‚ƒŠ‚ª‘«‚è‚Ü‚¹‚ñ"
E_XPG_READ		"ŽÐˆõƒf[ƒ^ƒx[ƒX %s ‚ª“Ç‚ß‚Ü‚¹‚ñ"
E_XPG_USAGE		"Žg—p•û–@F %s [ŽÐˆõƒf[ƒ^ƒx[ƒX–¼]\n"
E_XPG_WRITE		"ƒf[ƒ^ƒx[ƒX‚É‘‚«ž‚Þ‚±‚Æ‚ª‚Å‚«‚Ü‚¹‚ñ‚Å‚µ‚½"

$set MSGInfo

I_COM_NEWEMP		"V‹K“o˜^"
I_COM_YN_DELETE		"•\Ž¦’†‚Ìƒf[ƒ^‚ðíœ‚µ‚Ü‚·‚©H"
I_COM_YN_MODIFY		"•\Ž¦’†‚Ìƒf[ƒ^‚ð•ÏX‚µ‚Ü‚·‚©H"
I_COM_YN_REPLACE	"•\Ž¦’†‚Ìƒf[ƒ^‚É•ÏX‚µ‚Ü‚·‚©H"
I_COM_ASK_MOD_FMT	"•ÏX‚·‚éƒf[ƒ^‚Ì%s‚ð“ü—Í‚µ‚Ä‚­‚¾‚³‚¢B[È—ªŽž %ld]: "
I_COM_ASK_DEL_FMT	"íœ‚·‚éƒf[ƒ^‚Ì%s‚ð“ü—Í‚µ‚Ä‚­‚¾‚³‚¢B[È—ªŽž %ld]: "
I_COM_DISP_LIST_FMT	"%1$7ld  %3$30S %2$-20S  %4$3S  %5$10s\n"
$ I_COM_MOD_BADGE_FMT	""
I_DB_SURNAME1ST		"y"
I_MES_YN		" (y/n) [y]: "
I_XPG_CONTINUE		"Return ƒL[‚ð‰Ÿ‚µ‚Ä‚­‚¾‚³‚¢"
I_SCR_PROMPT_BADGE_DEF	"%s [È—ªŽž %ld]? "
I_SCR_PROMPT_BADGE	"%s? "
I_SCR_PROMPT_NAME_DEF	"%s [È—ªŽž %S]? "
I_SCR_PROMPT_NAME	"%s? "
I_SCR_PROMPT_CC_DEF	"%s [È—ªŽž %S]? "
I_SCR_PROMPT_CC		"%s? "
I_SCR_PROMPT_DOJ_DEF	"%s [È—ªŽž %s]? "
I_SCR_PROMPT_DOJ	"%s? "
I_SCR_IN_DATE_FMT	"%1$d/%2$d/%3$d"

$set MSGString

S_COM_CREATE		"c"
S_COM_DELETE		"d"
S_COM_EXIT		"e"
S_COM_LIST		"l"
S_COM_MODIFY		"m"
S_COM_LIST_TITLE	"ŽÐˆõ”Ô†               ©(–¼Žš)           –¼‘O              NºN½NÄN¾NÝN    “üŽÐ“ú\n"
S_COM_LIST_LINE		"„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ„Ÿ\n"
S_SCR_BADGE		"ŽÐˆõ”Ô†"
S_SCR_CC		"ƒRƒXƒgƒZƒ“ƒ^["
S_SCR_DOJ		"“üŽÐ“ú"
S_SCR_DOJ_FMT		"“üŽÐ“ú (”N/ŒŽ/“ú)"
S_SCR_MENU		"1-•ÏX(M) 2-V‹K“o˜^(C) 3-íœ(D) 4-ˆê——(L) 5-I—¹(E) :",
S_SCR_NAME		"–¼‘O"
S_SCR_SNAME1ST		"y"
S_SCR_SURNAME		"©(–¼Žš)"
S_SCR_PROMPT		""
S_DATE_FMT		"%x"
S_SCR_DATE_FMT		"%x"
