/*
 * *****************************************************************
 * *                                                               *
 * *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
 * *                                                               *
 * *   All Rights Reserved.  Unpublished rights  reserved  under   *
 * *   the copyright laws of the United States.                    *
 * *                                                               *
 * *   The software contained on this media  is  proprietary  to   *
 * *   and  embodies  the  confidential  technology  of  Digital   *
 * *   Equipment Corporation.  Possession, use,  duplication  or   *
 * *   dissemination of the software and media is authorized only  *
 * *   pursuant to a valid written license from Digital Equipment  *
 * *   Corporation.                                                *
 * *                                                               *
 * *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
 * *   by the U.S. Government is subject to restrictions  as  set  *
 * *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
 * *   or  in  FAR 52.227-19, as applicable.                       *
 * *                                                               *
 * *****************************************************************
 */
/*
 * HISTORY
 */
/*
** Generated by ODL Version X0.1 on Tue Jul 14 11:01:30 1992
*/

/*
** COPYRIGHT (c) 1989 BY
** DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.
** ALL RIGHTS RESERVED.
**
** THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED
** ONLY  IN  ACCORDANCE  OF  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE
** INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER
** COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
** OTHER PERSON.  NO TITLE TO AND  OWNERSHIP OF THE  SOFTWARE IS  HEREBY
** TRANSFERRED.
**
** THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE
** AND  SHOULD  NOT  BE  CONSTRUED  AS A COMMITMENT BY DIGITAL EQUIPMENT
** CORPORATION.
**
** DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS
** SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
*/

/*
** Operation Prototype Definitions
*/

#ifdef _Prototypes
typedef _Void (*_AddElement_P)(_inout _Object list,
    _in _Domain domain, _in _AnyPtr element, _in _Boolean copy);
typedef _Void (*_AppendElements_P)(_in _Object list,
    _in _Object append);
typedef _Void (*_Clear_P)(_inout _Object window);
typedef _Void (*_Close_P)(_inout _Object window,
    _in _Boolean recycle);
typedef _Void (*_Collapse_P)(_in _Object window,
    _in _AnyPtr user_data);
typedef _Object (*_Copy_P)(_in _Object object);
typedef _Object (*_Create_P)(_in _Type type);
typedef _Object (*_CreateEnvWindow_P)(_in _Type type,
    _in _Widget parent, _in _EnvContext env_context);
typedef _Object (*_CreateHsObject_P)(_in _Type type,
    _in _Integer his_type, _in lwk_object his_obj);
typedef _Object (*_CreateLbWindow_P)(
    _in _Type type, _in _Cardinal width, _in _Cardinal height,
    _in _Position x, _in _Position y, _in _Widget parent);
typedef _Object (*_CreateList_P)(_in _Type type,
    _in _Domain domain, _in _Integer estimated_count);
typedef _Object (*_CreateWindow_P)(_in _Type type);
typedef _Void (*_DeleteElement_P)(_inout _Object list,
    _in _Domain domain, _in _AnyPtr element);
typedef _Void (*_DeleteObj_P)(_inout _Object object);
typedef _Void (*_Display_P)(_inout _Object window,
    _in _EnvContext environment_context);
typedef _Void (*_DisplayMessage_P)(_in _Object window,
    _Status *status, _Integer count);
typedef _Void (*_DisplayProperties_P)(
    _in _Object hs_object, _in _AnyPtr display_data,
    _in _Boolean new_object);
typedef _Void (*_Expand_P)(_in _Object window,
    _in _AnyPtr user_data);
typedef _Void (*_Free_P)(_inout _Object object);
typedef _Void (*_GetAttribute_P)(_in _Object object,
    _in _Attribute attribute, _in _AnyPtr *value);
typedef _Void (*_GetCSProperty_P)(_in _Object hs_object,
    _in _String property_name, _out _CString *cs_string);
typedef _EnvWindow (*_GetEnvWindow_P)(_in _Object window);
typedef _Boolean (*_GetLinkbase_P)(_in _Object hs_object,
    _inout _CString *linkbase_name,
    _inout _String *linkbase_id);
typedef _Void (*_GetProperty_P)(_in _Object hs_object,
    _in lwk_domain domain, _in _String property_name,
    _inout _AnyPtr *value);
typedef _Boolean (*_GetSelection_P)(
    _in _Object window, _in _GetSelectOperation operation,
    _inout _AnyPtr user_data);
typedef _Void (*_GetValue_P)(_in _Object object,
    _in _String property_name, _in _Domain domain,
    _in _AnyPtr value);
typedef _Void (*_Highlight_P)(_in _Object window,
    _in _HsObject hs_object);
typedef _Void (*_Initialize_P)(_inout _Object object,
    _in _Object proto_object);
typedef _Boolean (*_IsType_P)(_in _Object object, _in _Type type);
typedef _Closure (*_Iterate_P)(_in _Object list,
    _in _Domain domain, _in _Closure closure,
    _in _Callback routine);
typedef _Boolean (*_LbInWindow_P)(_out _Object *window,
    _in lwk_linkbase linkbase);
typedef _Void (*_LoadDefaultAttributes_P)(
    _in _Object object);
typedef _Object (*_Open_P)(_in _Type type, _in _Cardinal width,
    _in _Cardinal height, _in _Position x, _in _Position y,
    _in _Widget parent);
typedef _Object (*_OpenEnv_P)(_in _Type type,
    _in _Widget parent, _in _EnvContext env_context, 
    _in _Boolean new_ctxt);
typedef _Void (*_PositionWindow_P)(_in _Object window);
typedef _Void (*_RaiseWindow_P)(_in _Object window);
typedef _Void (*_RemoveCopyright_P)(
    _in _Object window, _in _String title_id);
typedef _Void (*_RemoveElement_P)(_inout _Object list,
    _in _Domain domain, _in _AnyPtr element);
typedef _Void (*_ResetAttributes_P)(_in _Object object);
typedef _Void (*_ResetDefaultAttribute_P)(
    _in _Object object);
typedef _Object (*_Retrieve_P)(_in _Type type,
    _inout _Boolean *new_ctxt, _in _Boolean create_lb);
typedef _Void (*_Save_P)(_inout _Object hs_object,
    _in _Object hs_linkbase, _in _SaveOperation operation);
typedef _Void (*_SaveAttributes_P)(_in _Object object);
typedef _Void (*_SaveComposite_P)(_inout _Object container,
    _in _Object hs_object, _in _SaveOperation operation);
typedef _Void (*_SaveList_P)(_in _Object env_ctxt,
    lwk_domain domain, _AnyPtr head);
typedef _Void (*_Select_P)(_in _Object window,
    _in _HsObject hs_object);
typedef _Void (*_SelectElement_P)(_in _Object list,
    _in _Integer index, _in _Domain domain, _out _AnyPtr element);
typedef _Void (*_SetAttribute_P)(_in _Object object,
    _in _Attribute attribute, _in _AnyPtr *value);
typedef _Void (*_SetAttributeCurrent_P)(
    _in _Object object, _in _Attribute attribute,
    _in _AnyPtr *value);
typedef _Void (*_SetCSProperty_P)(_in _Object hs_object,
    _in _String property_name, _in _CString cs_string, 
    lwk_set_operation operation);
typedef _Void (*_SetContextCurrency_P)(
    _inout _Object env_ctxt, _in _CurrencyFlag currency,
    _in lwk_list list, _in _HsObject hs_object);
typedef _Void (*_SetCurrency_P)(_inout _Object env_window,
    _in _CurrencyFlag currency, _in _AnyPtr value);
typedef _Void (*_SetCursor_P)(_in _Object window,
    _in _CursorType cursor_type);
typedef _Boolean (*_SetHsObjState_P)(
    _inout _Object hs_object, _in _HsObjectState state,
    _in _StateOperation operation);
typedef _Void (*_SetProperty_P)(_in _Object hs_object,
    _in lwk_domain domain, _in _String property_name,
    _inout _AnyPtr *value, lwk_set_operation operation);
typedef _Void (*_SetValue_P)(_inout _Object object,
    _in _String property_name, _in _Domain domain,
    _in _AnyPtr value, _in _SetFlag flag);
typedef _Boolean (*_SetWindowState_P)(
    _inout _Object window, _in _WindowState state,
    _in _StateOperation operation);
typedef _Void (*_Store_P)(_in _Object hs_object);
typedef _Void (*_Update_P)(_in _Object window,
    _HsObject hs_object, _UpdateOperation update);
#else /* !_Prototypes */
typedef _Method _AddElement_P;
typedef _Method _AppendElements_P;
typedef _Method _Clear_P;
typedef _Method _Close_P;
typedef _Method _Collapse_P;
typedef _Method _Copy_P;
typedef _Method _Create_P;
typedef _Method _CreateEnvWindow_P;
typedef _Method _CreateHsObject_P;
typedef _Method _CreateLbWindow_P;
typedef _Method _CreateList_P;
typedef _Method _CreateWindow_P;
typedef _Method _DeleteElement_P;
typedef _Method _DeleteObj_P;
typedef _Method _Display_P;
typedef _Method _DisplayMessage_P;
typedef _Method _DisplayProperties_P;
typedef _Method _Expand_P;
typedef _Method _Free_P;
typedef _Method _GetAttribute_P;
typedef _Method _GetCSProperty_P;
typedef _Method _GetEnvWindow_P;
typedef _Method _GetLinkbase_P;
typedef _Method _GetProperty_P;
typedef _Method _GetSelection_P;
typedef _Method _GetValue_P;
typedef _Method _Highlight_P;
typedef _Method _Initialize_P;
typedef _Method _IsType_P;
typedef _Method _Iterate_P;
typedef _Method _LbInWindow_P;
typedef _Method _LoadDefaultAttributes_P;
typedef _Method _Open_P;
typedef _Method _OpenEnv_P;
typedef _Method _PositionWindow_P;
typedef _Method _RaiseWindow_P;
typedef _Method _RemoveCopyright_P;
typedef _Method _RemoveElement_P;
typedef _Method _ResetAttributes_P;
typedef _Method _ResetDefaultAttribute_P;
typedef _Method _Retrieve_P;
typedef _Method _Save_P;
typedef _Method _SaveAttributes_P;
typedef _Method _SaveComposite_P;
typedef _Method _SaveList_P;
typedef _Method _Select_P;
typedef _Method _SelectElement_P;
typedef _Method _SetAttribute_P;
typedef _Method _SetAttributeCurrent_P;
typedef _Method _SetCSProperty_P;
typedef _Method _SetContextCurrency_P;
typedef _Method _SetCurrency_P;
typedef _Method _SetCursor_P;
typedef _Method _SetHsObjState_P;
typedef _Method _SetProperty_P;
typedef _Method _SetValue_P;
typedef _Method _SetWindowState_P;
typedef _Method _Store_P;
typedef _Method _Update_P;
#endif /* _Prototypes */
