$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0

$quote "
$set MS_SA
BADID		"sa: Preposterous user id, %d: ignored\n"
CANTOPEN	"sa: Can't open %s\n"
CANTSAVE	"sa: Can't save to %s\n"
CATEGOR		"Categorizing commands used %d times or fewer as **junk**\n"
NOFILENM	"sa: Missing filename\n"
ONEFILE		"sa: Only 1 file with -s\n"
SAUSAGE		"Usage: %s [-abcdDfijkKlmnorstu] [-v Number] [-S SaveFile] [-U UserFile] [File]\n"
