$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0
$quote "
$set MS_QUOT

USAGE   "usage: quot [-cfghnv] [filesystem ...]\n"
READERR "quot: read error at block %ld\n"
BADSTAT "quot: could not stat %s\n"
BADTYPE "quot: not a character or block device\n"

$set MS_QUOT_SEC

AUTH	"%s: need sysadmin authorization\n"
PRIV	"%s: insufficient privileges\n"
