 
$ *****************************************************************
$ *                                                               *
$ *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
$ *                                                               *
$ *   All Rights Reserved.  Unpublished rights  reserved  under   *
$ *   the copyright laws of the United States.                    *
$ *                                                               *
$ *   The software contained on this media  is  proprietary  to   *
$ *   and  embodies  the  confidential  technology  of  Digital   *
$ *   Equipment Corporation.  Possession, use,  duplication  or   *
$ *   dissemination of the software and media is authorized only  *
$ *   pursuant to a valid written license from Digital Equipment  *
$ *   Corporation.                                                *
$ *                                                               *
$ *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
$ *   by the U.S. Government is subject to restrictions  as  set  *
$ *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
$ *   or  in  FAR 52.227-19, as applicable.                       *
$ *                                                               *
$ *****************************************************************
$
$ HISTORY
 
$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0
$ @(#)$RCSfile: trpt.msg,v $ $Revision: 4.2 $ (DEC) $Date: 1991/09/20 06:33:42 $

$set MS_TRPT

$quote "

TRPT_USAGE	"usage: trpt [-afjst] [-p hex-address] [system [core]]\n"
TRPT_NONAME	"trpt: %s: no namelist\n"
TRPT_STR_X	"%x"
TRPT_SRC	"(src=%s,%u, "
TRPT_DST	"dst=%s,%u)"
TRPT_WIN	"(win=%x)"
TRPT_ARROW	">"
TRPT_NEWLINE	"\n"
TRPT_SFLAG1	"\trcv_nxt %lx rcv_wnd %x snd_una %lx snd_nxt %lx snd_max %lx\n"
TRPT_SFLAG2	"\tsnd_wl1 %lx snd_wl2 %lx snd_wnd %x\n"
TRPT_RXTSHFT	" (t_rxtshft=%d)"
TRPT_FMT1	"\n%x:\n"
TRPT_FMT2	"%03ld %s:%s "
TRPT_FMT3	"[%lx..%lx)"
TRPT_FMT4	"%lx"
TRPT_FMT5	"%s%s"
TRPT_FMT6	"%s"
TRPT_FMT7	"<%s>"
TRPT_FMT8	"%s%s=%d"
TRPT_FMT9	"@%lx"
TRPT_FMT10	" -> %s"
