.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.TH cda_msg 4
.SH NAME
\*Lcda_msg\*O \- CDA run-time messages
.SH DESCRIPTION
.iX "CDA messages"
.PP
CDA run-time messages may be reported while you are converting or
viewing a CDA document, or while you are using a CDA application. These
messages refer to conditions that range from successful completion of the
operation to termination of processing because of a serious error.
.PP
When converting a CDA document, CDA run-time messages are returned to your
system's standard error location (your screen, by default).
.PP
When viewing a CDA document on a workstation, select Diagnostic
Information... from the File pull-down menu in the CDA Viewer window to
display messages. When viewing a CDA document on a character-cell terminal,
CDA run-time messages appear on your screen by default.
.PP
For information on how other CDA applications report CDA run-time messages,
consult your application's message documentation.
.PP
CDA run-time messages consist of a message number and message text.
.PP
The following section lists the CDA run-time messages. A brief explanation
and recommended user action follows each message, unless a user action is
not required. The messages are listed in alphabetical order, by message
name.
.SH CDA RUN-TIME MESSAGES
.PP
28606465, NORMAL, normal successful completion
.br
\f3Level:\f1 Success
.br
\f3Explanation:\f1 The specified action has been successfully
completed.
.sp
.PP
28606473, DEFAULT, item present by default
.br
\f3Level:\f1 Success
.br
\f3Explanation:\f1 The application called cda_locate_item, which determined
that the item was present by default in the input stream.
.sp
.PP
28606481, SUSPEND, converter is suspended
.br
\f3Level:\f1 Success
.br
\f3Explanation:\f1 The application called cda_convert, which determined that
the back end suspended conversion. This message can only be returned by the CDA
viewer.
.sp
.PP
28606489, INHERIT, item present by inheritance
.br
\f3Level:\f1 Success
.br
\f3Explanation:\f1 The application called cda_locate_item, which determined
that the item was present by inheritance in the input stream.
.sp
.PP
28606497, UNRECENC, Unrecognized encodings skipped
.br
\f3Level:\f1 Success, Informational
.br
\f3Explanation:\f1 This success status is returned by the GET AGGREGATE and GET DOCUMENT
routines if unrecognized data in the input encoding is skipped.
This informational status is logged to the common message log by
the bundled DDIF and DTIF converter front ends if data is skipped
during the reading within the front-end conversion.
.sp
.PP
28607267, INFINPLOG, informational messages produced during, input
conversion, see error log
.br
\f3Level:\f1 Informational
.br
\f3Explanation:\f1 The input conversion completed but some informational messages
were produced.
.br
\f3User Action:\f1 Refer to the error log for more details.
.sp
.PP
28607275, INFOUTLOG, informational messages produced during, output conversion,
see error log
.br
\f3Level:\f1 Informational
.br
\f3Explanation:\f1 The output conversion completed but some informational messages
were produced.
.br
\f3User Action:\f1 Refer to the error log for more details.
.sp
.PP
28607283, FILESPEC, missing filespec
.br
\f3Level:\f1 Informational
.br
\f3Explanation:\f1 Missing filespec: 'filespec'.
This is the name of the missing filespec.
.sp
.PP
28607291, ITMAGGCNT, aggregate item code: !ZL Aggregate type: !AD  Agg count: !ZL
.br
\f3Level:\f1 Informational
.br
\f3Explanation:\f1 Aggregate item code: 'integer' Aggregate type: 'string' Agg count: 'integer'.
This is information on a missing item, aggregate name, and the count of
the aggregate type.
.sp
.PP
28607299, AGGCNT, aggregate type: !AD    Agg count: !ZL
.br
\f3Level:\f1 Informational
.br
\f3Explanation:\f1 Aggregate type: 'string' Agg count: 'integer'.
This is information on the aggregate name, and the count of
the aggregate type.
.sp
.PP
28607371, TYPEREF, reference to undefined type name
.br
\f3Level:\f1 Informational
.br
\f3Explanation:\f1 The definition of type \f2typeref\f1 was not found.
.sp
.PP
28607419, STYGDEFBK, fallback to non-locale-specific style guide: 'filespec'
.br
\f3Level:\f1 Informational
.br
\f3Explanation:\f1 Fallback to non-locale-specific style guide: 'filespec'.
Since the locale-specific style guide could not be found, the
non-locale-specific version of the style guide was used instead.
.sp
.PP
28608064, MISEXTREF, external reference file missing or could not be read
.br
\f3Level:\f1 Warning
.br
\f3Explanation:\f1 An external reference file is missing or could not be read.
A document's external reference could not be found, read, or processed.
.sp
.PP
28608072, MISSTYGDE, style guide file missing or could not be read
.br
\f3Level:\f1 Warning
.br
\f3Explanation:\f1 Style guide file missing or could not be read.
A document's external style guide could not be found, read, or processed.
.sp
.PP
28608866, ENDOFDOC, end of document
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application called cda_get_aggregate, which determined
that no more aggregates exist in the document.
.sp
.PP
ENDOFSEQ, end of sequence
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application called cda_next_aggregate referencing an
aggregate that was at the end of a sequence.
.sp
.PP
28608882, EMPTY, empty item
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application called a CDA access procedure referencing an
item that is empty.
.sp
.PP
28608890, INDEX, index out of range
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application called cda_locate_item, cda_store_item, or
cda_erase_item referencing an array-valued item, but the index
is out of range.
.sp
.PP
28608898, INVINSERT, invalid insert
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application called cda_insert_aggregate or
cda_store_item referencing an aggregate that was already part
of a sequence, but was not the first aggregate of the sequence.
.sp
.PP
28608906, INVAGGTYP, invalid aggregate type
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application called a CDA access procedure referencing an
aggregate type code that is undefined, or an aggregate that has
an undefined type code.
.sp
.PP
28608914, INVITMCOD, invalid item code
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application called a CDA access procedure referencing an
aggregate item code that is not defined.
.sp
.PP
28608922, INVDOC, invalid document syntax
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The CDA access procedures determined that the document
contains invalid syntax.
.sp
.PP
28608930, INVITMLST, invalid item list
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application called cda_open_file or
cda_create_root_aggregate with a processing options item list
that contained an invalid item.
.sp
.PP
28608938, VAREMPTY, empty variant item (OBSOLETE)
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application called cda_locate_item, cda_store_item, or
cda_erase_item referencing an item that has a variable data
type.  The item that specifies the data type is empty.
.sp
.PP
28608946, VARINDEX, variant index out of range (OBSOLETE)
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application called cda_locate_item, cda_store_item, or
cda_erase_item referencing an array-valued item that has a
variable data type, but the index is out of range for the item
that specifies the data type.
.sp
.PP
28608954, VARVALUE, variant value out of range
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application called cda_locate_item, cda_store_item, or
cda_erase_item referencing an item that has a variable
data type, but the item that specifies the data type has an
invalid value.
.sp
.PP
28608962, INVTAGCOD, invalid tag code
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application called cda_store_item referencing an item
that has a special tag encoding, but the value of the \*Ladd-info\*O
parameter is not defined for the item.
.sp
.PP
28608970, INVBUFLEN, invalid buffer length
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application called cda_store_item referencing an item
that is required to have a specified buffer length.  The
value of the buffer length parameter is not the required value.
.sp
.PP
28608978, ALLOCFAIL, memory allocation failure
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The standard memory allocation procedure
failed to allocate dynamic memory.
.sp
.PP
28608986, INVFUNCOD, invalid function code
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application called cda_convert with an invalid function
code.
.sp
.PP
28608994, UNSUPFMT, unsupported document format
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application called cda_convert with an unsupported
document format name.  The document format name may be misspelled,
or the required conversion module may not be installed.
.sp
.PP
28609002, READONLY, aggregate is read-only
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application requested input processing options that
require an aggregate to be read-only.  The application attempted
to write or delete the aggregate.
.sp
.PP
28609010, DEFNOTFOU, definition not found
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application called cda_find_definition referencing an
entity that is not defined.
.sp
.PP
28609018, READFAIL, read failure
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The standard read function has failed.
.sp
.PP
28609026, WRITFAIL, write failure
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The standard write function has failed.
.sp
.PP
28609034, OPENFAIL, open failure
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The standard open function has failed.
.sp
.PP
28609042, CLOSEFAIL, close failure
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The standard close function has failed.
.sp
.PP
28609050, INVSCOCOD, invalid scope code
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application called cda_enter_scope or cda_leave_scope
referencing a scope code that is not defined or invalid
in following correct document scoping rules.
.sp
.PP
28609058, INVSCOTRAN, invalid scope transition
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The application made a call to cda_enter_scope or
cda_leave_scope that did not follow correct scoping rules.
.sp
.PP
28609066, ERRINPLOG, error messages produced during, input conversion,
see error log
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The input conversion did not complete and some error messages
were produced.
.br
\f3User Action:\f1 Refer to the error log for more details.
.sp
.PP
28609074, ERROUTLOG, error messages produced during, output conversion, see
error log
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The output conversion did not complete and some error messages
were produced.
.br
\f3User Action:\f1 Refer to the error log for more details.
.sp
.PP
28609082, INVDATLEN, invalid data length
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The length of the value data exceeded the specified
length for the data type.
.sp
.PP
28609090, UNSUPCNV, unsupported document conversion
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The input and output document formats are incompatible for conversion.
.sp
.PP
28609098, INVOPTION, invalid converter option
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 An invalid option was specified for the converter.
.br
\f3User Action:\f1 Refer to the documentation for this converter to see the valid options.
.sp
.PP
28609106, VERSKEW, major version skew between, input file and CDA Toolkit
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The file's major version is different from the Toolkit's.
Thus, the Toolkit cannot properly process the file.
.sp
.PP
28609114, INVADDINF, invalid additional information
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The \*Ladd-info\*O parameter in a call to cda_locate_item or
cda_store_item is invalid.
.sp
.PP
28609122, INVFLTVAL, invalid floating-point value
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 A floating-point datum has a reserved value.
.sp
.PP
28609130, FLTTRN, floating-point truncation
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 During cda_locate_item for a general floating-point value,
floating truncation occurred.
.sp
.PP
28609138, INVINPDMN, invalid input domain
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 An invalid input domain was specified for the front end. Only DDIF and DTIF
are supported as domains.
.sp
.PP
28609146, INVOUTDMN, invalid output domain
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 An invalid output domain was specified for the back end. Only DDIF and DTIF
are supported as domains.
.sp
.PP
28609154, DCVNOTFND, domain converter not found
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The required domain converter could not be found.
.sp
.PP
28609162, ICVNOTFND, input converter not found
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The specified input converter could not be found.
.sp
.PP
28609170, OCVNOTFND, output converter not found
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The specified output converter could not be found.
.sp
.PP
28609178, INVSTSCOD, invalid status code
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The specified status code's associated message could
not be found.
.sp
.PP
28609186, INVAGGCTX, invalid aggregate context
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The user called PUT AGGREGATE, PUT DOCUMENT, or ENTER SCOPE
with an aggregate that is invalid in its context in the document
.sp
.PP
28609194, REQITMMIS, required item missing
.br
\f3Level:\f1 Error
.br
\f3Explanation:\f1 The user called PUT AGGREGATE, PUT DOCUMENT, or ENTER SCOPE
with an aggregate containing an item that is required, but empty.
.sp
.PP
28609668, INTERR, internal error
.br
\f3Level:\f1 Fatal
.br
\f3Explanation:\f1 The CDA Toolkit detected an internal error.
.sp
********
.SH SEE ALSO
.PP
ctod(1), ddifanls(1), ddifps(1), ddiftext(1), dtifanls(1), dtifddif(1),
dtoc(1), dxvdoc(1X), textddif(1), vdoc(1),
cda(4), ddif(4), ddis(4), dots(4), dtif(4), dvr_msg(4)
.EQ
delim off
.EN
