.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: Xqtdir.4,v $ $Revision: 3.2.5.2 $ (DEC) $Date: 1994/01/11 16:59:52 $
.\"
.\"
.\"  THIS OSF SOURCE FILE HAS BEEN MODIFIED BY DLIBRARY IN OSP
.\"  If you need information about the changes, send mail 
.\"  to dlibrary@ravine at Digital Equipment Corp.
.\"
.\" 
.\" (c) Copyright 1991, OPEN SOFTWARE FOUNDATION, INC.
.\" ALL RIGHTS RESERVED
.\" 
.TH Xqtdir 4
.SH NAME
.PP
\*LXqtdir\*O, \*L.Xqtdir\*O \- Contains temporary files used by the \*Luuxqt\*O daemon to execute remote command requests
.SH SYNOPSIS
.PP
.sS
\*L/usr/spool/uucp/.Xqtdir\*O
.sE
.SH "DESCRIPTION"
.PP
.iX "\&.Xqtdir" "uuxqt temporary files"
.iX "uuxqt" "temporary files"
The \*L/usr/spool/uucp/.Xqtdir\*O directory contains temporary
.\"Begin Digital correction.
files used by the \*Luuxqt\*O daemon to execute
.\"End Digital correction.
remote command requests.
.SH "RELATED INFORMATION"
.PP
.\"Begin Digital correction.
Daemons: \*Luuxqt\*O(1)
.\"End Digital correction.
.PP
Commands: \*Luux\*O(1)
.EQ
delim off
.EN
