$
$ *****************************************************************
$ *                                                               *
$ *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
$ *                                                               *
$ *   All Rights Reserved.  Unpublished rights  reserved  under   *
$ *   the copyright laws of the United States.                    *
$ *                                                               *
$ *   The software contained on this media  is  proprietary  to   *
$ *   and  embodies  the  confidential  technology  of  Digital   *
$ *   Equipment Corporation.  Possession, use,  duplication  or   *
$ *   dissemination of the software and media is authorized only  *
$ *   pursuant to a valid written license from Digital Equipment  *
$ *   Corporation.                                                *
$ *                                                               *
$ *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
$ *   by the U.S. Government is subject to restrictions  as  set  *
$ *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
$ *   or  in  FAR 52.227-19, as applicable.                       *
$ *                                                               *
$ *****************************************************************
$
$
$ (c) Copyright 1990, 1991, 1992, 1993 OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ @(#)$RCSfile: libcurses.msg,v $ $Revision: 1.1.3.2 $ (DEC) $Date: 1993/06/12 21:46:28 $
$
$
$ HISTORY
$

$
$ Messages for libcurses.
$
$quote "

$
$ message for setupterm.c
$
$set MS_SETUPTERM

M_MSG_1 "setupterm: No such terminal: "
M_MSG_2 "setupterm: corrupted term entry\r\n"
M_MSG_3 "setupterm: term entry too long\r\n"

$
$ messages for showstring.c
$
$set MS_SHOWSTRING

M_MSG_4 "showstring: Bad call to _showstring, first %x, last %x, diff %dpcx\n"
