$
$ *****************************************************************
$ *                                                               *
$ *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
$ *                                                               *
$ *   All Rights Reserved.  Unpublished rights  reserved  under   *
$ *   the copyright laws of the United States.                    *
$ *                                                               *
$ *   The software contained on this media  is  proprietary  to   *
$ *   and  embodies  the  confidential  technology  of  Digital   *
$ *   Equipment Corporation.  Possession, use,  duplication  or   *
$ *   dissemination of the software and media is authorized only  *
$ *   pursuant to a valid written license from Digital Equipment  *
$ *   Corporation.                                                *
$ *                                                               *
$ *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
$ *   by the U.S. Government is subject to restrictions  as  set  *
$ *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
$ *   or  in  FAR 52.227-19, as applicable.                       *
$ *                                                               *
$ *****************************************************************
$
$ HISTORY
$
$ @(#)$RCSfile: libcapsar.msg,v $ $Revision: 1.1.3.2 $ (DEC) $Date: 1992/03/19 16:38:35 $
$

$quote "         define quote character.

$set MS_libcapsar        Define initial set#

M_MSG_0              "capsar_get_messages failed\n"
M_MSG_1              "cannot malloc enough space\n"
M_MSG_2              "cannot open message file %s\n"
M_MSG_4              "cannot realloc space\n"
M_MSG_5              "search permission denied to %s\n"
M_MSG_6              "%s does not exist\n"
M_MSG_7              "cannot stat %s\n"
M_MSG_8              "cannot open  %s\n"
M_MSG_9              "read error on %s\n"
M_MSG_10             "%s is not a DDIF/DOTS file\n"
M_MSG_11             "unable to allocate mail structure\n"
M_MSG_12             "capsar_create failed\n"
M_MSG_13             "/bin/pwd"
M_MSG_14             "fgets"
M_MSG_15             "bad starting directory\n"
M_MSG_16             "cannot access cmd: %s\n"
M_MSG_17             "cannot execute command\n %s\n"
M_MSG_18             "%s failed\n"
M_MSG_19             "cannot access cmd : %s\n"
M_MSG_20             "cannot allocate memory\n"
M_MSG_21             "cannot reallocate any space\n"
M_MSG_22             "encoding error on ddif/dots document\n"
M_MSG_23             "bad change to home directory\n"
M_MSG_25             "NULL message\n"
M_MSG_26             "cannot open %s for writing\n"
M_MSG_27             "write error on file %s\n"
M_MSG_31             "extract : write error"
M_MSG_32             "extract read error\n"
M_MSG_33             "cannot open file %s for reading\n"
M_MSG_35             "write error on %s\n"
M_MSG_36             "empty message\n"
M_MSG_37             "no headers in mail message\n"
M_MSG_38             "end of field encountered\n"
M_MSG_40             "cannot allocate more space\n"
M_MSG_41             "to many body parts\n"
M_MSG_42             "? DOTS/DDIF document in mail message"
M_MSG_43             "? DOTS/DDIF documents inmail message and ? text documents\n"
M_MSG_44             "cannot allocate space for new mail message\n"
M_MSG_45             "illegal smtp type\n"
M_MSG_46             "cannot copy mail data to temp file\n"
M_MSG_47             "cannot open temporary file name %s\n"
M_MSG_49             "no headers lines in message\n"
M_MSG_50             "data is not a mail message\n"
M_MSG_51             "cannot malloc space\n"
M_MSG_53             "unable to allocate data storage\n"
M_MSG_54             "error in reading mail data\n"
M_MSG_55             "cannot open temporary file for writing\n"
M_MSG_56             "error in copyng data\n"
M_MSG_57             "unexpected eof\n"
M_MSG_58             "not valid file descriptor\n"
M_MSG_59             "file descriptor points to an invalid address\n"
M_MSG_60             "I/O error on read/write\n"
M_MSG_61             "connect request or remote file operation failed\n"
M_MSG_62             "cannot stat file descriptor\n"
M_MSG_64             "file descriptor refers to a directory\n"
M_MSG_65             "error in opening %s\n"
M_MSG_67             "no headers in message\n"
M_MSG_68             "mail message has no header lines\n"
M_MSG_71             "unable to allocate string storage"
M_MSG_72             "error in file manipulation\n"
M_MSG_75             "cannot open %s\n"
M_MSG_76	     "no/bad headers in mail message\n"
M_MSG_77	     "error copying data to temporary file\n"
M_MSG_78	     "illegal file descriptor\n"
M_MSG_79	     "socket descriptor\n"
M_MSG_80             "cannot allocate space for eb\n"
M_MSG_81             "error opening %s\n"
M_MSG_82             "write error\n"
