 
$ *****************************************************************
$ *                                                               *
$ *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
$ *                                                               *
$ *   All Rights Reserved.  Unpublished rights  reserved  under   *
$ *   the copyright laws of the United States.                    *
$ *                                                               *
$ *   The software contained on this media  is  proprietary  to   *
$ *   and  embodies  the  confidential  technology  of  Digital   *
$ *   Equipment Corporation.  Possession, use,  duplication  or   *
$ *   dissemination of the software and media is authorized only  *
$ *   pursuant to a valid written license from Digital Equipment  *
$ *   Corporation.                                                *
$ *                                                               *
$ *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
$ *   by the U.S. Government is subject to restrictions  as  set  *
$ *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
$ *   or  in  FAR 52.227-19, as applicable.                       *
$ *                                                               *
$ *****************************************************************
$
$ HISTORY
 
$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0

$
$ RESTRICTED RIGHTS LEGEND
$ Use, Duplication or Disclosure by the Government is subject to
$ restrictions as set forth in paragraph (b)(3)(B) of the rights in
$ Technical Data and Computer Software clause in DAR 7-104.9(a).
$ 
$  @(#)$RCSfile: fshelp.msg,v $ $Revision: 4.2 $ (DEC) $Date: 1991/09/20 03:34:37 $
$
$ COMPONENT_NAME: (LIBCADM) Standard C Library System Admin Functions 
$
$ FUNCTIONS: 
$
$ ORIGINS: 27 
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$ OBJECT CODE ONLY SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1989 
$ All Rights Reserved
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ 

$ messages for fshelp

$set MS_FSHELP_ERR
$quote "

Msg_INVAL	"0506-501 Invalid argument"
Msg_INVALFS	"0506-502 Invalid filesystem"
Msg_INVALFILNO	"0506-503 Invalid file number"
Msg_INVALDBLK	"0506-504 Invalid data block"
Msg_INVALMODE	"0506-505 Invalid mode"
Msg_INVALARG	"0506-506 Invalid argument"
Msg_AXSHELPER	"0506-507 Access denied or could not execute"
Msg_ARGMISSING	"0506-508 Argument is missing"
Msg_NOP		"0506-509 That is a no-op."
Msg_SYNTAX	"0506-510 Syntax error"
Msg_UNKVFS	"0506-511 Unknown vfs type"
Msg_UNKOP	"0506-512 Unknown filesystem helper operation"
Msg_VFSMANGLED	"0506-513 VFS file is mangled"
Msg_VFSAXS	"0506-514 VFS file access denied"
Msg_NOTSUP	"0506-515 Filesystem helper does not support this operation"
Msg_WOULDBLOCK	"0506-516 This would block"
Msg_ACTIVE	"0506-517 Inappropriate action on an active filesystem"
Msg_CANTLOCK	"0506-518 Can not lock the device"
Msg_DEVOPEN	"0506-519 Device open failed"
Msg_DEVFAIL	"0506-520 Device operation failed"
Msg_DEVFAILRD	"0506-521 Device read failed"
Msg_DEVFAILWR	"0506-522 Device write failed"
Msg_CORRUPT	"0506-523 Filesystem is corrupt"
Msg_NOMEM	"0506-524 Out of memory"
Msg_INTERNAL	"0506-525 Internal error"
Msg_IMPERR	"0506-526 Implementation-specific error, code = "
Msg_UNKERR	"0506-527 Unknown error, code = "
