/*
 * *****************************************************************
 * *                                                               *
 * *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
 * *                                                               *
 * *   All Rights Reserved.  Unpublished rights  reserved  under   *
 * *   the copyright laws of the United States.                    *
 * *                                                               *
 * *   The software contained on this media  is  proprietary  to   *
 * *   and  embodies  the  confidential  technology  of  Digital   *
 * *   Equipment Corporation.  Possession, use,  duplication  or   *
 * *   dissemination of the software and media is authorized only  *
 * *   pursuant to a valid written license from Digital Equipment  *
 * *   Corporation.                                                *
 * *                                                               *
 * *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
 * *   by the U.S. Government is subject to restrictions  as  set  *
 * *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
 * *   or  in  FAR 52.227-19, as applicable.                       *
 * *                                                               *
 * *****************************************************************
 */
/*
 * HISTORY
 */
/*
 * @(#)$RCSfile: pollution.h,v $ $Revision: 1.1.5.15 $ (DEC) $Date: 1993/11/19 15:42:34 $
 */

/* pollution.h: non-ANSI global symbol defines */

#define DEPSILON __DEPSILON
#define DFPMAX __DFPMAX
#define DFPMIN __DFPMIN
#define DINFINITY __DINFINITY
#define DQNAN __DQNAN
#define DSNAN __DSNAN
#define NCchrlen __NCchrlen
#define NCcollate __NCcollate
#define NCcoluniq __NCcoluniq
#define NCdec __NCdec
#define NCdechr __NCdechr
#define NCdecode __NCdecode
#define NCdecstr __NCdecstr
#define NCenc __NCenc
#define NCencode __NCencode
#define NCencstr __NCencstr
#define NCflatchr __NCflatchr
#define NCisNLchar __NCisNLchar
#define NCislower islower
#define NCisupper isupper
#define NETGROUP __NETGROUP
#define NLasctime __NLasctime
#define NLcatgets __catgets
#define NLchrlen __NLchrlen
#define NLctime __NLctime
#define NLflatstr __NLflatstr
#define NLfprintf fprintf
#define NLgetamsg __NLgetamsg
#define NLisNLcp __NLisNLcp
#define NLstrlen strlen
#define NLstrtime __NLstrtime
#define SEPSILON __SEPSILON
#define SFPMAX __SFPMAX
#define SFPMIN __SFPMIN
#define SINFINITY __SINFINITY
#define SQNAN __SQNAN
#define SSNAN __SSNAN
#define a64l __a64l
#define abstimer __abstimer
#define accept __accept
#define access __access
#define acct __acct
#define addtominuslist __addtominuslist
#define adjtime __adjtime
#define alarm __alarm
#define alloca __alloca
#define alphasort __alphasort
#define arg_setup __arg_setup
#define asctime_r __asctime_r
#define async_daemon __async_daemon
#define audcntl __audcntl
#define audgen __audgen
#define auditwrite __auditwrite
#define authnone_create __authnone_create
#define authunix_create __authunix_create
#define authunix_create_default __authunix_create_default
#define basename __basename
#define bcmp __bcmp
#define bcopy __bcopy
#define bind __bind
#define bind_initialized __bind_initialized
#define bindresvport __bindresvport
#define bindup __bindup
#define brk __brk
#define bsd_chg_it __bsd_chg_it
#define bsd_replace __bsd_replace
#define bsd_siad_getgrgid __bsd_siad_getgrgid
#define bsd_siad_getpwnam __bsd_siad_getpwnam
#define bsd_ulimit __bsd_ulimit
#define bzero __bzero
#define cacheflush __cacheflush
#define callrpc __callrpc
#define catclose __catclose
#define catgetmsg __catgetmsg
#define catgets __catgets
#define catopen __catopen
#define cfgetispeed __cfgetispeed
#define cfgetospeed __cfgetospeed
#define cfmakeraw __cfmakeraw
#define cfree __cfree
#define cfsetispeed __cfsetispeed
#define cfsetospeed __cfsetospeed
#define cfsetspeed __cfsetspeed
#define chdir __chdir
#define chflags __chflags
#define chk_perm __chk_perm
#define chmod __chmod
#define chown __chown
#define chroot __chroot
#define clearenv __clearenv
#define clnt_broadcast __clnt_broadcast
#define clnt_broadcast_exp __clnt_broadcast_exp
#define clnt_create __clnt_create
#define clnt_create_vers __clnt_create_vers
#define clnt_pcreateerror __clnt_pcreateerror
#define clnt_perrno __clnt_perrno
#define clnt_perror __clnt_perror
#define clnt_spcreateerror __clnt_spcreateerror
#define clnt_sperrno __clnt_sperrno
#define clnt_sperror __clnt_sperror
#define clntraw_create __clntraw_create
#define clnttcp_create __clnttcp_create
#define clntudp_bufcreate __clntudp_bufcreate
#define clntudp_create __clntudp_create
#define close __close
#define closedir __closedir
#define closelog __closelog
#define closelog_r __closelog_r
#define clrlock __clrlock
#define confstr __confstr
#define connect __connect
#define copysign __copysign
#define creadir __creadir
#define creat __creat
#define creatediskbyname __creatediskbyname
#define creatediskbyname_r __creatediskbyname_r
#define crypt __crypt
#define crypt16 __crypt16
#define ctermid __ctermid
#define ctime_r __ctime_r
#define cuserid __cuserid
#define daylight __daylight
#define dbm_close __dbm_close
#define dbm_close_status __dbm_close_status
#define dbm_delete __dbm_delete
#define dbm_do_nextkey __dbm_do_nextkey
#define dbm_fetch __dbm_fetch
#define dbm_firstkey __dbm_firstkey
#define dbm_forder __dbm_forder
#define dbm_nextkey __dbm_nextkey
#define dbm_open __dbm_open
#define dbm_setdefwrite __dbm_setdefwrite
#define dbm_store __dbm_store
#define dirname __dirname
#define dirname_r __dirname_r
#define dkcksum __dkcksum
#define dlclose __dlclose
#define dlerror __dlerror
#define dlopen __dlopen
#define dlsym __dlsym
#define dn_comp __dn_comp
#define dn_expand __dn_expand
#define dn_skipname __dn_skipname
#define drand48 __drand48
#define drand48_r __drand48_r
#define dup __dup
#define dup2 __dup2
#define ecvt __ecvt
#define ecvt_r __ecvt_r
#define encrypt __encrypt
#define endent_bind __endent_bind
#define endfsent __endfsent
#define endfsent_r __endfsent_r
#define endgrent __endgrent
#define endgrent_r __endgrent_r
#define endhostent __endhostent
#define endhostent_local __endhostent_local
#define endhostent_r __endhostent_r
#define endnetent __endnetent
#define endnetent_local __endnetent_local
#define endnetent_r __endnetent_r
#define endnetgrent __endnetgrent
#define endprotoent __endprotoent
#define endprotoent_r __endprotoent_r
#define endpwent __endpwent
#define endpwent_r __endpwent_r
#define endrpcent __endrpcent
#define endrpcent_local __endrpcent_local
#define endrpcent_yp __endrpcent_yp
#define endservent __endservent
#define endservent_local __endservent_local
#define endservent_r __endservent_r
#define endttyent __endttyent
#define endttyent_r __endttyent_r
#define endusershell __endusershell
#define endusershell_r __endusershell_r
#define endutent __endutent
#define endutent_r __endutent_r
#define environ __environ
#define erand48 __erand48
#define erand48_r __erand48_r
#define exc_add_gp_range __exc_add_gp_range
#define exc_add_pc_range_table __exc_add_pc_range_table
#define exc_remove_gp_range __exc_remove_gp_range
#define exc_remove_pc_range_table __exc_remove_pc_range_table
#define exec_with_loader __exec_with_loader
#define execl __execl
#define execle __execle
#define execlp __execlp
#define execv __execv
#define execve __execve
#define execvp __execvp
#define expacct __expacct
#define exportfs __exportfs
#define fchdir __fchdir
#define fchflags __fchflags
#define fchk_perm __fchk_perm
#define fchmod __fchmod
#define fchown __fchown
#define fclose_unlocked __fclose_unlocked
#define fcntl __fcntl
#define fcvt __fcvt
#define fcvt_r __fcvt_r
#define fdopen __fdopen
#define fegetround __fegetround
#define fesetround __fesetround
#define fflush_unlocked __fflush_unlocked
#define ffs __ffs
#define fgetwc getwc
#define fgetws __fgetws
#define _filbuf __filbuf
#define fileno __fileno
#define fix_errno __fix_errno
#define fix_sigcontext __fix_sigcontext
#define fix_ucontext __fix_ucontext
#define flock __flock
#define flockfile __flockfile
#define fmtmsg __fmtmsg
#define fnmatch __fnmatch
#define fork __fork
#define fork_slvmod __fork_slvmod
#define forkpty __forkpty
#define formatter __formatter
#define fp_class_d __fp_class_d
#define fp_class_f __fp_class_f
#define fp_query __fp_query
#define fpathconf __fpathconf
#define fputws __fputws
#define fread_unlocked __fread_unlocked
#define freeminuslist __freeminuslist
#define fseek_unlocked __fseek_unlocked
#define fstat __fstat
#define fstatfs __fstatfs
#define fstatvfs __fstatvfs
#define fsync __fsync
#define ftok __ftok
#define ftruncate __ftruncate
#define ftw __ftw
#define funlockfile __funlockfile
#define fwrite_unlocked __fwrite_unlocked
#define gcvt __gcvt
#define get_myaddress __get_myaddress
#define getaddressconf __getaddressconf
#define getc_unlocked __getc_unlocked
#define getchar_unlocked __getchar_unlocked
#define getclock __getclock
#define getcommon_any __getcommon_any
#define getcwd __getcwd
#define getdate __getdate
#define getdate_r __getdate_r
#define getdirentries __getdirentries
#define getdiskbyname __getdiskbyname
#define getdiskbyname_r __getdiskbyname_r
#define getdomainname __getdomainname
#define getdtablesize __getdtablesize
#define getegid __getegid
#define geterrno __geterrno
#define geteuid __geteuid
#define getfh __getfh
#define getfsent __getfsent
#define getfsent_r __getfsent_r
#define getfsfile __getfsfile
#define getfsfile_r __getfsfile_r
#define getfsspec __getfsspec
#define getfsspec_r __getfsspec_r
#define getfsstat __getfsstat
#define getgid __getgid
#define getgrent __getgrent
#define getgrent_r __getgrent_r
#define getgrgid __getgrgid
#define getgrgid_r __getgrgid_r
#define getgrnam __getgrnam
#define getgrnam_r __getgrnam_r
#define getgroups __getgroups
#define gethostbyaddr __gethostbyaddr
#define gethostbyaddr_local __gethostbyaddr_local
#define gethostbyaddr_r __gethostbyaddr_r
#define gethostbyname __gethostbyname
#define gethostbyname_local __gethostbyname_local
#define gethostbyname_r __gethostbyname_r
#define gethostdomain __gethostdomain
#define gethostdomain_r __gethostdomain_r
#define gethostent __gethostent
#define gethostent_local __gethostent_local
#define gethostent_r __gethostent_r
#define gethostid __gethostid
#define gethostname __gethostname
#define getitimer __getitimer
#define getlogin __getlogin
#define getlogin_r __getlogin_r
#define getmntinfo __getmntinfo
#define getmntinfo_r __getmntinfo_r
#define getmsg __getmsg
#define getnetbyaddr __getnetbyaddr
#define getnetbyaddr_local __getnetbyaddr_local
#define getnetbyaddr_r __getnetbyaddr_r
#define getnetbyname __getnetbyname
#define getnetbyname_local __getnetbyname_local
#define getnetbyname_r __getnetbyname_r
#define getnetent __getnetent
#define getnetent_local __getnetent_local
#define getnetent_r __getnetent_r
#define getnetgrent __getnetgrent
#define getnetname __getnetname
#define getopt __getopt
#define getpagesize __getpagesize
#define getpass __getpass
#define getpeername __getpeername
#define getpgid __getpgid
#define getpgrp __getpgrp
#define getpid __getpid
#define getppid __getppid
#define getpriority __getpriority
#define getprotobyname __getprotobyname
#define getprotobyname_r __getprotobyname_r
#define getprotobynumber __getprotobynumber
#define getprotobynumber_r __getprotobynumber_r
#define getprotoent __getprotoent
#define getprotoent_r __getprotoent_r
#define getpw __getpw
#define getpwent __getpwent
#define getpwent_local __getpwent_local
#define getpwent_r __getpwent_r
#define getpwnam __getpwnam
#define getpwnam_local __getpwnam_local
#define getpwnam_r __getpwnam_r
#define getpwuid __getpwuid
#define getpwuid_local __getpwuid_local
#define getpwuid_r __getpwuid_r
#define getrlimit __getrlimit
#define getrpcbyname __getrpcbyname
#define getrpcbyname_bind __getrpcbyname_bind
#define getrpcbyname_local __getrpcbyname_local
#define getrpcbyname_yp __getrpcbyname_yp
#define getrpcbynumber __getrpcbynumber
#define getrpcbynumber_bind __getrpcbynumber_bind
#define getrpcbynumber_local __getrpcbynumber_local
#define getrpcbynumber_yp __getrpcbynumber_yp
#define getrpcent __getrpcent
#define getrpcent_bind __getrpcent_bind
#define getrpcent_local __getrpcent_local
#define getrpcent_yp __getrpcent_yp
#define getrpcport __getrpcport
#define getrusage __getrusage
#define getservbyname __getservbyname
#define getservbyname_local __getservbyname_local
#define getservbyname_r __getservbyname_r
#define getservbyport __getservbyport
#define getservbyport_local __getservbyport_local
#define getservbyport_r __getservbyport_r
#define getservent __getservent
#define getservent_local __getservent_local
#define getservent_r __getservent_r
#define getsid __getsid
#define getsockname __getsockname
#define getsockopt __getsockopt
#define getsvc __getsvc
#define getsvc_r __getsvc_r
#define getsysinfo __getsysinfo
#define getsubopt __getsubopt
#define gettxt __gettxt
#define gettimeofday __gettimeofday
#define gettimer __gettimer
#define getttyent __getttyent
#define getttyent_r __getttyent_r
#define getttynam __getttynam
#define getttynam_r __getttynam_r
#define getuid __getuid
#define getusershell __getusershell
#define getusershell_r __getusershell_r
#define getutent __getutent
#define getutent_r __getutent_r
#define getutid __getutid
#define getutid_r __getutid_r
#define getutline __getutline
#define getutline_r __getutline_r
#define getvfsbyname __getvfsbyname
#define getvfsbynumber __getvfsbynumber
#define getw __getw
#define getwc __getwc
#define getwc_unlocked __getwc_unlocked
#define getwchar __getwchar
#define getwd __getwd
#define glob __glob
#define globfree __globfree
#define gmtime_r __gmtime_r
#define gsignal __gsignal
#define gsignal_r __gsignal_r
#define gtty __gtty
#define hcreate __hcreate
#define hcreate_r __hcreate_r
#define hdestroy __hdestroy
#define hdestroy_r __hdestroy_r
#define herror __herror
#define host2netname __host2netname
#define hostalias __hostalias
#define hostalias_r __hostalias_r
#define hsearch __hsearch
#define hsearch_r __hsearch_r
#define htonl __htonl
#define htons __htons
#define ieee_get_fp_control __ieee_get_fp_control
#define ieee_get_state_at_signal __ieee_get_state_at_signal
#define ieee_ignore_state_at_signal __ieee_ignore_state_at_signal
#define ieee_set_fp_control __ieee_set_fp_control
#define ieee_set_state_at_signal __ieee_set_state_at_signal
#define index __index
#define inet_addr __inet_addr
#define inet_aton __inet_aton
#define inet_lnaof __inet_lnaof
#define inet_makeaddr __inet_makeaddr
#define inet_netof __inet_netof
#define inet_network __inet_network
#define inet_ntoa __inet_ntoa
#define init_svc __Init_svc
#define init_svc_r __Init_svc_r
#define initgroups __initgroups
#define initstate __initstate
#define initstate_r __initstate_r
#define innetgr __innetgr
#define insque __insque
#define ioctl __ioctl
#define isascii __isascii
#define isatty __isatty
#define isaverb __isaverb
#define iswalnum __iswalnum
#define iswalpha __iswalpha
#define iswcntrl __iswcntrl
#define iswctype __iswctype
#define iswdigit __iswdigit
#define iswgraph __iswgraph
#define iswlower __iswlower
#define iswprint __iswprint
#define iswpunct __iswpunct
#define iswspace __iswspace
#define iswupper __iswupper
#define iswxdigit __iswxdigit
#define itrunc __itrunc
#define jrand48 __jrand48
#define jrand48_r __jrand48_r
#define key_decryptsession __key_decryptsession
#define key_encryptsession __key_encryptsession
#define key_gendes __key_gendes
#define key_setsecret __key_setsecret
#define kill __kill
#define killpg __killpg
#define kloadcall __kloadcall
#define kls_client_entry __kls_client_entry
#define kls_client_inq_module __kls_client_inq_module
#define kls_client_inq_region __kls_client_inq_region
#define kls_client_ipc_connect_to_server __kls_client_ipc_connect_to_server
#define kls_client_ipc_disconnect_from_server __kls_client_ipc_disconnect_from_server
#define kls_client_ipc_receive_reply __kls_client_ipc_receive_reply
#define kls_client_ipc_send_request __kls_client_ipc_send_request
#define kls_client_load __kls_client_load
#define kls_client_lookup __kls_client_lookup
#define kls_client_lookup_package __kls_client_lookup_package
#define kls_client_next_module __kls_client_next_module
#define kls_client_unload __kls_client_unload
#define kls_message_create_entry_request __kls_message_create_entry_request
#define kls_message_create_inq_module_request __kls_message_create_inq_module_request
#define kls_message_create_inq_region_request __kls_message_create_inq_region_request
#define kls_message_create_load_request __kls_message_create_load_request
#define kls_message_create_lookup_package_request __kls_message_create_lookup_package_request
#define kls_message_create_lookup_request __kls_message_create_lookup_request
#define kls_message_create_next_module_request __kls_message_create_next_module_request
#define kls_message_create_unload_request __kls_message_create_unload_request
#define l3tol __l3tol
#define l64a __l64a
#define label_ok __label_ok
#define lchown __lchown
#define lcong48 __lcong48
#define lcong48_r __lcong48_r
#define ldr_atexit __ldr_atexit
#define ldr_bootstrap __ldr_bootstrap
#define ldr_brk __ldr_brk
#define ldr_context_atexit __ldr_context_atexit
#define ldr_context_bootstrap __ldr_context_bootstrap
#define ldr_context_create __ldr_context_create
#define ldr_context_get_entry_pt __ldr_context_get_entry_pt
#define ldr_context_global_file_init __ldr_context_global_file_init
#define ldr_context_global_file_remove __ldr_context_global_file_remove
#define ldr_context_inherit __ldr_context_inherit
#define ldr_context_inq_module __ldr_context_inq_module
#define ldr_context_inq_region __ldr_context_inq_region
#define ldr_context_install __ldr_context_install
#define ldr_context_load __ldr_context_load
#define ldr_context_lookup __ldr_context_lookup
#define ldr_context_lookup_package __ldr_context_lookup_package
#define ldr_context_next_module __ldr_context_next_module
#define ldr_context_remove __ldr_context_remove
#define ldr_context_unload __ldr_context_unload
#define ldr_declare_lock_functions __ldr_declare_lock_functions
#define ldr_entry __ldr_entry
#define ldr_inq_module __ldr_inq_module
#define ldr_inq_region __ldr_inq_region
#define ldr_install __ldr_install
#define ldr_kernel_process __ldr_kernel_process
#define ldr_lookup __ldr_lookup
#define ldr_lookup_package __ldr_lookup_package
#define ldr_my_process __ldr_my_process
#define ldr_next_module __ldr_next_module
#define ldr_remove __ldr_remove
#define ldr_sbrk __ldr_sbrk
#define ldr_status_to_errno __ldr_status_to_errno
#define ldr_xattach __ldr_xattach
#define ldr_xdetach __ldr_xdetach
#define ldr_xentry __ldr_xentry
#define ldr_xload __ldr_xload
#define ldr_xlookup __ldr_xlookup
#define ldr_xlookup_package __ldr_xlookup_package
#define ldr_xunload __ldr_xunload
#define lfind __lfind
#define libc_declare_lock_functions __libc_declare_lock_functions
#define libc_locks_init __libc_locks_init
#define libc_locks_reinit __libc_locks_reinit
#define link __link
#define link_addr __link_addr
#define link_ntoa __link_ntoa
#define list_free __list_free
#define listen __listen
#define load __load
#define local_hostname_length __local_hostname_length
#define localtime_r __localtime_r
#define lockf __lockf
#define login __login
#define login_tty __login_tty
#define longjmperror __longjmperror
#define lrand48 __lrand48
#define lrand48_r __lrand48_r
#define lsearch __lsearch
#define lseek __lseek
#define lstat __lstat
#define ltol3 __ltol3
#define madvise __madvise
#define make_stack_executable __make_stack_executable
#define mallinfo __mallinfo
#define mallopt __mallopt
#define mbsadvance __mbsadvance
#define mbscat __mbscat
#define mbschr __mbschr
#define mbscpy __mbscpy
#define mbsinvalid __mbsinvalid
#define mbslen __mbslen
#define mbsncat __mbsncat
#define mbsncmp __mbsncmp
#define mbsncpy __mbsncpy
#define mbspbrk __mbspbrk
#define mbsrchr __mbsrchr
#define mbstoint __mbstoint
#define mbstomb __mbstomb
#define mbswidth __mbswidth
#define memccpy __memccpy
#define mk_query __mk_query
#define mkdir __mkdir
#define mkfifo __mkfifo
#define mknod __mknod
#define mkpwclear __mkpwclear
#define mkpwunclear __mkpwunclear
#define mkstemp __mkstemp
#define mktemp __mktemp
#define mktimer __mktimer
#define mmap __mmap
#define mount __mount
#define mprotect __mprotect
#define mrand48 __mrand48
#define mrand48_r __mrand48_r
#define msem_init __msem_init
#define msem_lock __msem_lock
#define msem_remove __msem_remove
#define msem_unlock __msem_unlock
#define msgctl __msgctl
#define msgget __msgget
#define msgrcv __msgrcv
#define msgsnd __msgsnd
#define msleep __msleep
#define msync __msync
#define munmap __munmap
#define mvalid __mvalid
#define mwakeup __mwakeup
#define naccept __naccept
#define nanosleep_d9 __nanosleep_d9
#define nearest __nearest
#define netname2host __netname2host
#define netname2user __netname2user
#define nfssvc __nfssvc
#define nftw __nftw
#define ngetpeername __ngetpeername
#define ngetsockname __ngetsockname
#define nice __nice
#define nl_langinfo __nl_langinfo
#define nlist __nlist
#define nrand48 __nrand48
#define nrand48_r __nrand48_r
#define nrecvfrom __nrecvfrom
#define nrecvmsg __nrecvmsg
#define ns_addr __ns_addr
#define ns_ntoa __ns_ntoa
#define nsendmsg __nsendmsg
#define ntohl __ntohl
#define ntohs __ntohs
#define numlocks __numlocks
#define offtime __offtime
#define offtime_r __offtime_r
#define onminuslist __onminuslist
#define open __open
#define opendir __opendir
#define openlog __openlog
#define openlog_r __openlog_r
#define openpty __openpty
#define opterr __opterr
#define optind __optind
#define p_cdname __p_cdname
#define p_class __p_class
#define p_query __p_query
#define p_rr __p_rr
#define p_time __p_time
#define p_type __p_type
#define pathconf __pathconf
#define pause __pause
#define pclose __pclose
#define pipe __pipe
#define plock __plock
#define pmap_getmaps __pmap_getmaps
#define pmap_getport __pmap_getport
#define pmap_rmtcall __pmap_rmtcall
#define pmap_set __pmap_set
#define pmap_unset __pmap_unset
#define poll __poll
#define popen __popen
#define priocntlset __priocntlset
#define profil __profil
#define psignal __psignal
#define ptrace __ptrace
#define putc_unlocked __putc_unlocked
#define putchar_unlocked __putchar_unlocked
#define putenv __putenv
#define putgr __putgr
#define putgrent __putgrent
#define putgrsent __putgrsent
#define putlock __putlock
#define putlong __putlong
#define putmsg __putmsg
#define putpw __putpw
#define putpwent __putpwent
#define putshort __putshort
#define pututline __pututline
#define pututline_r __pututline_r
#define putw __putw
#define putwc __putwc
#define putwchar __putwchar
#define pw_file __pw_file
#define qadd __qadd
#define qfextension __qfextension
#define qfname __qfname
#define qmuladd __qmuladd
#define qsort __qsort
#define quotactl __quotactl
#define quotagroup __quotagroup
#define rand_r __rand_r
#define random __random
#define random_r __random_r
#define rcmd __rcmd
#define rcmd_r __rcmd_r
#define re_comp __re_comp
#define re_comp_r __re_comp_r
#define re_exec __re_exec
#define re_exec_r __re_exec_r
#define read __read
#define read_rnd __read_rnd
#define readdir __readdir
#define readdir_r __readdir_r
#define readlink __readlink
#define readv __readv
#define realtime_kernel __realtime_kernel
#define reboot __reboot
#define rec_mutex_alloc __rec_mutex_alloc
#define rec_mutex_free __rec_mutex_free
#define rec_mutex_init __rec_mutex_init
#define rec_mutex_lock __rec_mutex_lock
#define rec_mutex_readlock __rec_mutex_readlock
#define rec_mutex_reinit __rec_mutex_reinit
#define rec_mutex_trylock __rec_mutex_trylock
#define rec_mutex_unlock __rec_mutex_unlock
#define rec_mutex_readunlock __rec_mutex_readunlock
#define recv __recv
#define recvfrom __recvfrom
#define recvmsg __recvmsg
#define regcomp __regcomp
#define regerror __regerror
#define regexec __regexec
#define regfree __regfree
#define registerrpc __registerrpc
#define reltimer __reltimer
#define remque __remque
#define res_init __res_init
#define res_mkquery __res_mkquery
#define res_query __res_query
#define res_querydomain __res_querydomain
#define res_search __res_search
#define res_send __res_send
#define resabs __resabs
#define resclock __resclock
#define resrel __resrel
#define ressleep __ressleep
#define revoke __revoke
#define rewinddir __rewinddir
#define rexec __rexec
#define rexec_r __rexec_r
#define rindex __rindex
#define rint __rint
#define rmdir __rmdir
#define rmtimer __rmtimer
#define rpmatch __rpmatch
#define rresvport __rresvport
#define rtime __rtime
#define ruserok __ruserok
#define ruserpass __ruserpass
#define sbrk __sbrk
#define scandir __scandir
#define security __security
#define seed48 __seed48
#define seed48_r __seed48_r
#define seekdir __seekdir
#define select __select
#define semctl __semctl
#define semget __semget
#define semop __semop
#define send __send
#define sendmsg __sendmsg
#define sendto __sendto
#define set_program_attributes __set_program_attributes
#define setbuffer __setbuffer
#define setclock __setclock
#define setcontext __setcontext
#define setdomainname __setdomainname
#define setegid __setegid
#define setent_bind __setent_bind
#define setenv __setenv
#define seterrno __seterrno
#define seteuid __seteuid
#define setfsent __setfsent
#define setfsent_r __setfsent_r
#define setgid __setgid
#define setgrent __setgrent
#define setgrent_r __setgrent_r
#define setgroups __setgroups
#define sethostent __sethostent
#define sethostent_local __sethostent_local
#define sethostent_r __sethostent_r
#define sethostid __sethostid
#define sethostname __sethostname
#define setitimer __setitimer
#define setkey __setkey
#define setlinebuf __setlinebuf
#define setlogin __setlogin
#define setlogmask __setlogmask
#define setlogmask_r __setlogmask_r
#define setnetent __setnetent
#define setnetent_local __setnetent_local
#define setnetent_r __setnetent_r
#define setnetgrent __setnetgrent
#define setpgid __setpgid
#define setpgrp __setpgrp
#define setpriority __setpriority
#define setprotoent __setprotoent
#define setprotoent_r __setprotoent_r
#define setpwent __setpwent
#define setpwent_r __setpwent_r
#define setpwfile __setpwfile
#define setregid __setregid
#define setreuid __setreuid
#define setrgid __setrgid
#define setrlimit __setrlimit
#define setrpcent __setrpcent
#define setrpcent_local __setrpcent_local
#define setrpcent_yp __setrpcent_yp
#define setruid __setruid
#define setservent __setservent
#define setservent_local __setservent_local
#define setservent_r __setservent_r
#define setsid __setsid
#define setsockopt __setsockopt
#define setstate __setstate
#define setstate_r __setstate_r
#define setsysinfo __setsysinfo
#define settimeofday __settimeofday
#define setttyent __setttyent
#define setttyent_r __setttyent_r
#define setuid __setuid
#define setusershell __setusershell
#define setusershell_r __setusershell_r
#define setutent __setutent
#define setutent_r __setutent_r
#define setvbuf_unlocked __setvbuf_unlocked
#define severity_lookup __severity_lookup
#define shmat __shmat
#define shmctl __shmctl
#define shmdt __shmdt
#define shmget __shmget
#define shutdown __shutdown
#define sia_alloc_entity __sia_alloc_entity
#define sia_audit __sia_audit
#define sia_authorize __sia_authorize
#define sia_caps __sia_caps
#define sia_cap_fps __sia_cap_fps
#define sia_chdir __sia_chdir
#define sia_chg_finger __sia_chg_finger
#define sia_chg_password __sia_chg_password
#define sia_chg_shell __sia_chg_shell
#define sia_chk_invoker __sia_chk_invoker
#define sia_collect_trm __sia_collect_trm
#define sia_free_entity __sia_free_entity
#define sia_getamsg __sia_getamsg
#define sia_getgroup __sia_getgroup
#define sia_getpasswd __sia_getpasswd
#define sia_handle __sia_handle
#define sia_init __sia_init
#define sia_initialized __sia_initialized
#define sia_log __sia_log
#define sia_make_entity_pwd __sia_make_entity_pwd
#define sia_mat_init __sia_mat_init
#define sia_mechs __sia_mechs
#define sia_ses_authent __sia_ses_authent
#define sia_ses_estab __sia_ses_estab
#define sia_ses_init __sia_ses_init
#define sia_ses_launch __sia_ses_launch
#define sia_ses_reauthent __sia_ses_reauthent
#define sia_ses_release __sia_ses_release
#define sia_ses_suauthent __sia_ses_suauthent
#define sia_setupfp __sia_setupfp
#define sia_sig __sia_sig
#define sia_switch __sia_switch
#define sia_timed_action __sia_timed_action
#define sia_timeout __sia_timeout
#define sia_warning __sia_warning
#define siad_chg_finger __siad_chg_finger
#define siad_chg_password __siad_chg_password
#define siad_chg_shell __siad_chg_shell
#define siad_chk_invoker __siad_chk_invoker
#define siad_chk_user __siad_chk_user
#define siad_endgrent __siad_endgrent
#define siad_endpwent __siad_endpwent
#define siad_getgrent __siad_getgrent
#define siad_getgrgid __siad_getgrgid
#define siad_getgrnam __siad_getgrnam
#define siad_getpwent __siad_getpwent
#define siad_getpwnam __siad_getpwnam
#define siad_getpwuid __siad_getpwuid
#define siad_init __siad_init
#define siad_ses_authent __siad_ses_authent
#define siad_ses_estab __siad_ses_estab
#define siad_ses_init __siad_ses_init
#define siad_ses_launch __siad_ses_launch
#define siad_ses_reauthent __siad_ses_reauthent
#define siad_ses_release __siad_ses_release
#define siad_ses_suauthent __siad_ses_suauthent
#define siad_setgrent __siad_setgrent
#define siad_setpwent __siad_setpwent
#define sigaction __sigaction
#define sigaddset __sigaddset
#define sigblock __sigblock
#define sigdelset __sigdelset
#define sigemptyset __sigemptyset
#define sigfillset __sigfillset
#define sighold __sighold
#define sigignore __sigignore
#define sigismember __sigismember
#define siglongjmp __siglongjmp
#define sigpause __sigpause
#define sigpending __sigpending
#define sigprocmask __sigprocmask
#define sigrelse __sigrelse
#define sigreturn __sigreturn
#define sigsendset __sigsendset
#define sigset __sigset
#define sigsetjmp __sigsetjmp
#define sigsetmask __sigsetmask
#define sigstack __sigstack
#define sigsuspend __sigsuspend
#define sigvec __sigvec
#define sleep __sleep
#define socket __socket
#define socketpair __socketpair
#define srand48 __srand48
#define srand48_r __srand48_r
#define srandom __srandom
#define srandom_r __srandom_r
#define ssignal __ssignal
#define ssignal_r __ssignal_r
#define stat __stat
#define statfs __statfs
#define statvfs __statvfs
#define stime __stime
#define strcasecmp __strcasecmp
#define strcpyn __strcpyn
#define strdup __strdup
#define strerror_r __strerror_r
#define strfind __strfind
#define strfmon __strfmon
#define strncasecmp __strncasecmp
#define strptime __strptime
#define strtok_r __strtok_r
#define stty __stty
#define svc_gethostflag __svc_gethostflag
#define svc_getnetflag __svc_getnetflag
#define svc_getprotoflag __svc_getprotoflag
#define svc_getreq __svc_getreq
#define svc_getreqset __svc_getreqset
#define svc_getrpcflag __svc_getrpcflag
#define svc_getservflag __svc_getservflag
#define svc_register __svc_register
#define svc_run __svc_run
#define svc_sendreply __svc_sendreply
#define svc_unregister __svc_unregister
#define svc_versquiet __svc_versquiet
#define svcerr_auth __svcerr_auth
#define svcerr_decode __svcerr_decode
#define svcerr_noproc __svcerr_noproc
#define svcerr_noprog __svcerr_noprog
#define svcerr_progvers __svcerr_progvers
#define svcerr_systemerr __svcerr_systemerr
#define svcerr_weakauth __svcerr_weakauth
#define svcfd_create __svcfd_create
#define svcraw_create __svcraw_create
#define svctcp_create __svctcp_create
#define svcudp_bufcreate __svcudp_bufcreate
#define svcudp_create __svcudp_create
#define svcudp_enablecache __svcudp_enablecache
#define swab __swab
#define swapon __swapon
#define symlink __symlink
#define sync __sync
#define sys_errlist __sys_errlist
#define sys_nerr __sys_nerr
#define sys_siglist __sys_siglist
#define syscall __syscall
#define sysconf __sysconf
#define syslog __syslog
#define syslog_r __syslog_r
#define table __table
#define tcdrain __tcdrain
#define tcflow __tcflow
#define tcflush __tcflush
#define tcgetattr __tcgetattr
#define tcgetpgrp __tcgetpgrp
#define tcgetsid __tcgetsid
#define tcsendbreak __tcsendbreak
#define tcsetattr __tcsetattr
#define tcsetpgrp __tcsetpgrp
#define tdelete __tdelete
#define tell __tell
#define telldir __telldir
#define tempnam __tempnam
#define tfind __tfind
#define times __times
#define timezone __timezone
#define tlockf __tlockf
#define toascii __toascii
#define towlower __towlower
#define towupper __towupper
#define trunc __trunc
#define truncate __truncate
#define tsearch __tsearch
#define ttylock __ttylock
#define ttylocked __ttylocked
#define ttyname __ttyname
#define ttyname_r __ttyname_r
#define ttyslot __ttyslot
#define ttytouchlock __ttytouchlock
#define ttyunlock __ttyunlock
#define ttywait __ttywait
#define twalk __twalk
#define tzset __tzset
#define ualarm __ualarm
#define uitrunc __uitrunc
#define ulimit __ulimit
#define umask __umask
#define umount __umount
#define uname __uname
#define ungetwc __ungetwc
#define unlink __unlink
#define unload __unload
#define unlocked_brk __unlocked_brk
#define unsetenv __unsetenv
#define user2netname __user2netname
#define usingypmap __usingypmap
#define usleep __usleep
#define usleep_thread __usleep_thread
#define ustat __ustat
#define uswitch __uswitch
#define utime __utime
#define utimes __utimes
#define utmpname __utmpname
#define v1prot_dofirst __v1prot_dofirst
#define v1prot_donext __v1prot_donext
#define vfork __vfork
#define wait __wait
#define wait3 __wait3
#define wait4 __wait4
#define waitpid __waitpid
#define wcscat __wcscat
#define wcschr __wcschr
#define wcscmp __wcscmp
#define wcscoll __wcscoll
#define wcscpy __wcscpy
#define wcscspn __wcscspn
#define wcsftime __wcsftime
#define wcslen __wcslen
#define wcsncat __wcsncat
#define wcsncmp __wcsncmp
#define wcsncpy __wcsncpy
#define wcspbrk __wcspbrk
#define wcsrchr __wcsrchr
#define wcsspn __wcsspn
#define wcstod __wcstod
#define wcstok __wcstok
#define wcstok_r __wcstok_r
#define wcstol __wcstol
#define wcstoul __wcstoul
#define wcswcs __wcswcs
#define wcswidth __wcswidth
#define wcsxfrm __wcsxfrm
#define wctype __wctype
#define wcwidth __wcwidth
#define wordexp __wordexp
#define wordfree __wordfree
#define write __write
#define write_rnd __write_rnd
#define writev __writev
#define xdr_accepted_reply __xdr_accepted_reply
#define xdr_array __xdr_array
#define xdr_authunix_parms __xdr_authunix_parms
#define xdr_bool __xdr_bool
#define xdr_bytes __xdr_bytes
#define xdr_callhdr __xdr_callhdr
#define xdr_callmsg __xdr_callmsg
#define xdr_char __xdr_char
#define xdr_cryptkeyarg __xdr_cryptkeyarg
#define xdr_cryptkeyres __xdr_cryptkeyres
#define xdr_datum __xdr_datum
#define xdr_des_block __xdr_des_block
#define xdr_double __xdr_double
#define xdr_enum __xdr_enum
#define xdr_float __xdr_float
#define xdr_free __xdr_free
#define xdr_getcredres __xdr_getcredres
#define xdr_int __xdr_int
#define xdr_keybuf __xdr_keybuf
#define xdr_keystatus __xdr_keystatus
#define xdr_long __xdr_long
#define xdr_netnamestr __xdr_netnamestr
#define xdr_netobj __xdr_netobj
#define xdr_opaque __xdr_opaque
#define xdr_opaque_auth __xdr_opaque_auth
#define xdr_pmap __xdr_pmap
#define xdr_pmaplist __xdr_pmaplist
#define xdr_pointer __xdr_pointer
#define xdr_reference __xdr_reference
#define xdr_rejected_reply __xdr_rejected_reply
#define xdr_replymsg __xdr_replymsg
#define xdr_rmtcall_args __xdr_rmtcall_args
#define xdr_rmtcallres __xdr_rmtcallres
#define xdr_short __xdr_short
#define xdr_string __xdr_string
#define xdr_u_char __xdr_u_char
#define xdr_u_int __xdr_u_int
#define xdr_u_long __xdr_u_long
#define xdr_u_short __xdr_u_short
#define xdr_union __xdr_union
#define xdr_unixcred __xdr_unixcred
#define xdr_vector __xdr_vector
#define xdr_void __xdr_void
#define xdr_wrapstring __xdr_wrapstring
#define xdr_yp_binding __xdr_yp_binding
#define xdr_yp_buf __xdr_yp_buf
#define xdr_yp_inaddr __xdr_yp_inaddr
#define xdr_ypall __xdr_ypall
#define xdr_ypbind_resp __xdr_ypbind_resp
#define xdr_ypbind_setdom __xdr_ypbind_setdom
#define xdr_ypdelete_args __xdr_ypdelete_args
#define xdr_ypdomain_wrap_string __xdr_ypdomain_wrap_string
#define xdr_ypmap_parms __xdr_ypmap_parms
#define xdr_ypmap_wrap_string __xdr_ypmap_wrap_string
#define xdr_ypmaplist __xdr_ypmaplist
#define xdr_ypmaplist_wrap_string __xdr_ypmaplist_wrap_string
#define xdr_ypowner_wrap_string __xdr_ypowner_wrap_string
#define xdr_yppushresp_xfr __xdr_yppushresp_xfr
#define xdr_ypreq_key __xdr_ypreq_key
#define xdr_ypreq_nokey __xdr_ypreq_nokey
#define xdr_ypreq_xfr __xdr_ypreq_xfr
#define xdr_ypresp_key_val __xdr_ypresp_key_val
#define xdr_ypresp_maplist __xdr_ypresp_maplist
#define xdr_ypresp_master __xdr_ypresp_master
#define xdr_ypresp_order __xdr_ypresp_order
#define xdr_ypresp_val __xdr_ypresp_val
#define xdr_ypupdate_args __xdr_ypupdate_args
#define xdrmem_create __xdrmem_create
#define xdrrec_create __xdrrec_create
#define xdrrec_endofrecord __xdrrec_endofrecord
#define xdrrec_eof __xdrrec_eof
#define xdrrec_readbytes __xdrrec_readbytes
#define xdrrec_skiprecord __xdrrec_skiprecord
#define xdrstdio_create __xdrstdio_create
#define xprt_register __xprt_register
#define xprt_unregister __xprt_unregister
#define yellowup __yellowup
#define yp_all __yp_all
#define yp_bind __yp_bind
#define yp_first __yp_first
#define yp_get_default_domain __yp_get_default_domain
#define yp_ismapthere __yp_ismapthere
#define yp_master __yp_master
#define yp_match __yp_match
#define yp_next __yp_next
#define yp_order __yp_order
#define yp_softbind __yp_softbind
#define yp_unbind __yp_unbind
#define ypbind_resp_arms __ypbind_resp_arms
#define yperr_string __yperr_string
#define ypprot_err __ypprot_err
