/*
 * *****************************************************************
 * *                                                               *
 * *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
 * *                                                               *
 * *   All Rights Reserved.  Unpublished rights  reserved  under   *
 * *   the copyright laws of the United States.                    *
 * *                                                               *
 * *   The software contained on this media  is  proprietary  to   *
 * *   and  embodies  the  confidential  technology  of  Digital   *
 * *   Equipment Corporation.  Possession, use,  duplication  or   *
 * *   dissemination of the software and media is authorized only  *
 * *   pursuant to a valid written license from Digital Equipment  *
 * *   Corporation.                                                *
 * *                                                               *
 * *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
 * *   by the U.S. Government is subject to restrictions  as  set  *
 * *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
 * *   or  in  FAR 52.227-19, as applicable.                       *
 * *                                                               *
 * *****************************************************************
 */
/*
 * HISTORY
 */
#ifndef lint
static char     *sccsid = "@(#)$RCSfile: ypupdate_prot.c,v $ $Revision: 4.2.5.2 $ (DEC) $Date: 1993/06/08 00:29:32 $";
#endif
/*
 */

/* name space pollution clean up */
#ifdef _NAME_SPACE_WEAK_STRONG
#include "pollution.h"
#if !defined(_THREAD_SAFE)
#pragma weak xdr_yp_buf = __xdr_yp_buf
#pragma weak xdr_ypdelete_args = __xdr_ypdelete_args
#pragma weak xdr_ypupdate_args = __xdr_ypupdate_args
#endif
#endif
#include <rpc/rpc.h>
#include <rpcsvc/ypupdate_prot.h>

/* @(#)ypupdate_prot.x	1.3 90/07/20 4.1NFSSRC; from 1.4 88/02/08 Copyr 1986, Sun Micro */

/*
 * Compiled from ypupdate_prot.x using rpcgen
 * This is NOT source code!
 * DO NOT EDIT THIS FILE!
 */


bool_t
xdr_yp_buf(xdrs, objp)
	XDR *xdrs;
	yp_buf *objp;
{
	if (!xdr_bytes(xdrs, (char **)&objp->yp_buf_val, (u_int *)&objp->yp_buf_len, MAXYPDATALEN)) {
		return (FALSE);
	}
	return (TRUE);
}




bool_t
xdr_ypupdate_args(xdrs, objp)
	XDR *xdrs;
	ypupdate_args *objp;
{
	if (!xdr_string(xdrs, &objp->mapname, MAXMAPNAMELEN)) {
		return (FALSE);
	}
	if (!xdr_yp_buf(xdrs, &objp->key)) {
		return (FALSE);
	}
	if (!xdr_yp_buf(xdrs, &objp->datum)) {
		return (FALSE);
	}
	return (TRUE);
}




bool_t
xdr_ypdelete_args(xdrs, objp)
	XDR *xdrs;
	ypdelete_args *objp;
{
	if (!xdr_string(xdrs, &objp->mapname, MAXMAPNAMELEN)) {
		return (FALSE);
	}
	if (!xdr_yp_buf(xdrs, &objp->key)) {
		return (FALSE);
	}
	return (TRUE);
}


