$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0
$
$ (C) COPYRIGHT International Business Machines Corp. 1985, 1989
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$
$ messages for telnetd
$

$set MS_TELNETD

$quote "

SELECT_ERR      "select"
FORK_ERR	"fork"
FATAL_FMT       "telnetd: %s.\r\n"
TELNETD_UNKN_OPT "telnetd: %s: unknown option\n"
TELNETD_BAD_PT	"telnetd: %s: bad port #\n"
TELNETD_UNKN_SERV	"telnetd: tcp/telnet: unknown service\n"
TELNETD_PROGNAME	"%s: "
TELNETD_USAGE1	"Usage: telnetd [-debug] [-h]"
TELNETD_USGAGE2	" [-Iinitid]"
TELNETD_USAGE3	" [-D (options|report|exercise|netdata|ptydata)]"
TELNETD_USAGE4	" [-l]"
TELNETD_USAGE5	" [-r[lowpty]-[highpty]]"
TELNETD_USAGE6	" [-B]"
TELNETD_USAGE7	" [port]\n"
