$ 
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$ OSF/1 Release 1.0
$
$ IBM CONFIDENTIAL -- (IBM Confidential Restricted when
$ combined with the aggregated modules for this product)
$ OBJECT CODE ONLY SOURCE MATERIALS
$ (C) COPYRIGHT International Business Machines Corp. 1988, 1989
$ All Rights Reserved
$ 
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ 
$ rdate.msg	4.1 16:48:44 7/15/90 SecureWare
$ messages for rdate
$
$ Do not translate rdate.
$ len
$ 
$quote "         define quote character.
$set MS_RDATE        Define initial set#

RDATE_UNKWN_SW 		"rdate: Unknown switch - %c\n"
RDATE_TIME_UNKWN 	"rdate: Time service unknown\n"
RDATE_NET_UNKWN 	"rdate: Unknown network - %s\n"
RDATE_SOCKCREATE_FAIL 	"rdate: socket create failure\n"
RDATE_BROAD_FAIL 	"rdate: set broadcast failure\n"
RDATE_SOCKSEND_FAIL 	"rdate: socket send failure\n"
RDATE_VERBOSE_MSG 	"%s: %s"
RDATE_VERBOSE_UNKWN_MSG "*Unknown*: %s"
RDATE_SELECT_FAIL 	"rdate: select failure\n"
RDATE_FAIL 		"Network time indeterminate\n"
RDATE_TIME 		"Network time is %s"
RDATE_SET_FAIL 		"rdate: Time set failed\n"
RDATE_SET_SUCCESS 	"Time set to %s"
