 
$ *****************************************************************
$ *                                                               *
$ *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
$ *                                                               *
$ *   All Rights Reserved.  Unpublished rights  reserved  under   *
$ *   the copyright laws of the United States.                    *
$ *                                                               *
$ *   The software contained on this media  is  proprietary  to   *
$ *   and  embodies  the  confidential  technology  of  Digital   *
$ *   Equipment Corporation.  Possession, use,  duplication  or   *
$ *   dissemination of the software and media is authorized only  *
$ *   pursuant to a valid written license from Digital Equipment  *
$ *   Corporation.                                                *
$ *                                                               *
$ *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
$ *   by the U.S. Government is subject to restrictions  as  set  *
$ *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
$ *   or  in  FAR 52.227-19, as applicable.                       *
$ *                                                               *
$ *****************************************************************
$
$ HISTORY
 
$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0
$
$ @(#)$RCSfile: mklost+found.msg,v $ $Revision: 4.3.3.2 $ (OSF) $Date: 1992/01/29 14:39:08 $
$
$ 09/16/91 - Tom Peterson
$	- changed symbolic names to numbers according to OSF/1 1.0.2
$	- left symbolic names and corresponding numbers as comments
$	for reference
$ 
$quote "
$set MS_MKLOST_FOUND
$
$ CREATING = 1		REMOVING = 2		DONE = 3
$
1	"creating slots...\n"
2	"removing dummy files...\n"
3	"done\n"
