.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: gethostid.2,v $ $Revision: 3.2.2.2 $ (DEC) $Date: 1992/05/15 09:00:46 $
.\"
.\" 
.\" (c) Copyright 1991, OPEN SOFTWARE FOUNDATION, INC.
.\" ALL RIGHTS RESERVED
.\" 
.\"
.\"
.TH gethostid 2
.SH NAME
\*Lgethostid\*O \- Gets the unique identifier of the current host
.SH SYNOPSIS 
.sS
.PP
\*Lint gethostid ( void );
.sE 
.SH DESCRIPTION
.iX "gethostid function"
.iX "host ID" "returning for current host"
.iX "host" "returning ID for current"
.PP
The \*Lgethostid(\|)\*O function allows a process to retrieve
the 32-bit identifier for the current host.
In most cases, the host
ID is stored in network standard byte order and is a
\*ODARPA Internet address
for the local machine.
.SH RETURN VALUES
.PP
Upon completion, the \*Lgethostid(\|)\*O function
returns the identifier for the current host.
.SH RELATED INFORMATION
.PP
Functions:
\*Lgethostname(2), sethostname(2)\*O
.iX "gethostid function"
.EQ
delim off
.EN
