/*
 * *****************************************************************
 * *                                                               *
 * *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
 * *                                                               *
 * *   All Rights Reserved.  Unpublished rights  reserved  under   *
 * *   the copyright laws of the United States.                    *
 * *                                                               *
 * *   The software contained on this media  is  proprietary  to   *
 * *   and  embodies  the  confidential  technology  of  Digital   *
 * *   Equipment Corporation.  Possession, use,  duplication  or   *
 * *   dissemination of the software and media is authorized only  *
 * *   pursuant to a valid written license from Digital Equipment  *
 * *   Corporation.                                                *
 * *                                                               *
 * *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
 * *   by the U.S. Government is subject to restrictions  as  set  *
 * *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
 * *   or  in  FAR 52.227-19, as applicable.                       *
 * *                                                               *
 * *****************************************************************
 */
/*
 * HISTORY
 */
#ifndef lint
static char     *sccsid = "@(#)$RCSfile: ypxfrd_svc.c,v $ $Revision: 4.2 $ (DEC) $Date: 1991/09/20 06:37:53 $";
#endif
/*
 */

#include <stdio.h>
#include <rpc/rpc.h>
#include <rpcsvc/ypxfrd.h>
/* 
 * @(#)ypxfrd.x	1.1 90/07/23 4.1NFSSRC Copyr 1990 Sun Micro 
 * This is NOT source code!
 * DO NOT EDIT THIS FILE!
 */

static void ypxfrd_1();

_main(argc,argv)
int argc;
char **argv;
{
	SVCXPRT *transp;
#ifdef DEBUG
	printf("ypxfrd: _main called.\n");
#endif

	(void)pmap_unset(YPXFRD, V1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		(void)fprintf(stderr, "cannot create udp service.\n");
		exit(1);
	}
	if (!svc_register(transp, YPXFRD, V1, ypxfrd_1, IPPROTO_UDP)) {
		(void)fprintf(stderr, "unable to register (YPXFRD, V1, udp).\n");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		(void)fprintf(stderr, "cannot create tcp service.\n");
		exit(1);
	}
	if (!svc_register(transp, YPXFRD, V1, ypxfrd_1, IPPROTO_TCP)) {
		(void)fprintf(stderr, "unable to register (YPXFRD, V1, tcp).\n");
		exit(1);
	}
	svc_run();
	(void)fprintf(stderr, "svc_run returned\n");
	exit(1);
}

static void
ypxfrd_1(rqstp, transp)
	struct svc_req *rqstp;
	SVCXPRT *transp;
{
	union {
		hosereq getdbm_1_arg;
	} argument;
	char *result;
	bool_t (*xdr_argument)(), (*xdr_result)();
	char *(*local)();

#ifdef DEBUG
	printf("ypxfrd: RPC entry point ypxfrd_1 called\n");
#endif
	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void)svc_sendreply(transp, xdr_void, (char *)NULL);
		return;

	case getdbm:
		xdr_argument = xdr_hosereq;
		xdr_result = xdr_dbmfyl;
		local = (char *(*)()) getdbm_1;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	bzero((char *)&argument, sizeof(argument));
	if (!svc_getargs(transp, xdr_argument, &argument)) {
		svcerr_decode(transp);
		return;
	}
	result = (*local)(&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, xdr_argument, &argument)) {
		(void)fprintf(stderr, "unable to free arguments\n");
		exit(1);
	}
}

