$ 
$ *****************************************************************
$ *                                                               *
$ *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
$ *                                                               *
$ *   All Rights Reserved.  Unpublished rights  reserved  under   *
$ *   the copyright laws of the United States.                    *
$ *                                                               *
$ *   The software contained on this media  is  proprietary  to   *
$ *   and  embodies  the  confidential  technology  of  Digital   *
$ *   Equipment Corporation.  Possession, use,  duplication  or   *
$ *   dissemination of the software and media is authorized only  *
$ *   pursuant to a valid written license from Digital Equipment  *
$ *   Corporation.                                                *
$ *                                                               *
$ *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
$ *   by the U.S. Government is subject to restrictions  as  set  *
$ *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
$ *   or  in  FAR 52.227-19, as applicable.                       *
$ *                                                               *
$ *****************************************************************
$
$ HISTORY
$ 
$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0
$set MS_RWHOD

$quote "

RWHOD_SUPERUSER		"rwhod: not super user\n"
RHWOD_UNKN_SERVICE	"rwhod: udp/who: unknown service\n"
RWHOD_DIR_ERROR		"Can't change dir to  %s\n"
RWHOD_MALLOC_FAIL	"rwhod: malloc failed\n"
RWHOD_UTMP_ERR		"rwhod: %s: %s\n"
RWHOD_NO_BOOT		"No boot time in utmp file\n"
RWHOD_SENDTO		"sendto %x.%d\n"
RWHOD_HOSTNAME		"hostname %s %s\n"
RWHOD_LOAD		"load %4.2f, %4.2f, %4.2f\n"
RWHOD_SPACE		"   "
RWHOD_NEWLINE		"\n"
RWHOD_FMT1		"%-8.8s %s:%s %.12s"
RWHOD_FMT2		" %2d"
RWHOD_FMT3		":%02d"
RWHOD_USAGE		"Usage: rwhod [-b | -l]\n"
RWHOD_UNKN_ARG		"rwhod: unknown argument -- %s\n"
