$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0
$quote "
$set MS_ACLSYN

ACLSYN_1	"Can't load synonyms from %s\n"
ACLSYN_2	"Can't rewrite synonym file %s\n"
ACLSYN_3	"usage:	aclsyn [-d database] [synonym] ...\n"
ACLSYN_4	"	aclsyn [-d database] -u synonym ...\n"
ACLSYN_5	"	aclsyn [-d database] -a [file] ...\n"
ACLSYN_6	"	aclsyn [-d database] -r [file] ...\n"
ACLSYN_7	"%s: undefined synonym\n"
ACLSYN_8	"out of memory"
