$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0
$quote "
$set MS_EPA

EPA_1	"Cannot locate clearance '%s'\n"
EPA_2	"Cannot locate sec level '%s'\n"
EPA_3	"Cannot locate caveat set '%s'\n"
EPA_4	"Unknown kernel authorization\n"
EPA_5	"Unknown base privilege\n"
EPA_6	"usage:  %s [-u RUID] [-l LUID] [-g RGID] "
EPA_7	"[-p base_privs] [-a auth] "
$ EPA_8
EPA_9	"[-c clearance] [-s sens_level] "
EPA_10	"[-v caveats] "
EPA_11	"command\n"
EPA_12	"Where RUID is the real user ID\n"
EPA_13	"      LUID is the login user ID\n"
EPA_14	"      RGID is the real group ID\n"
EPA_15	"      auth is the set of kernel authorizations\n"
EPA_16	"      privs is the set of base privileges\n"
EPA_17	"      clearance is the user's clearance\n"
EPA_18	"      sens_level is the process sensitivity level\n"
EPA_19	"      caveats is the process caveat set\n"
EPA_20	"%s: Warning: "
EPA_21	"Cannot set login UID"
EPA_22	"Cannot set real GID"
EPA_23	"Cannot set real UID"
EPA_24	"Cannot set clearance"
EPA_25	"Cannot set sensitivity level"
EPA_26	"Cannot establish caveat set"
EPA_27	"Cannot set information label"
EPA_28	"Cannot set kernel authorizations"
EPA_29	"Cannot set base privileges"
EPA_30	"cannot execute %s\n"
EPA_31	"UID contains non-digit `%c'\n"
EPA_32	"Unknown user `%s'\n"
EPA_33	"GID contains non-digit `%c'\n"
EPA_34	"Unknown group `%s'\n"
