 
$ *****************************************************************
$ *                                                               *
$ *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
$ *                                                               *
$ *   All Rights Reserved.  Unpublished rights  reserved  under   *
$ *   the copyright laws of the United States.                    *
$ *                                                               *
$ *   The software contained on this media  is  proprietary  to   *
$ *   and  embodies  the  confidential  technology  of  Digital   *
$ *   Equipment Corporation.  Possession, use,  duplication  or   *
$ *   dissemination of the software and media is authorized only  *
$ *   pursuant to a valid written license from Digital Equipment  *
$ *   Corporation.                                                *
$ *                                                               *
$ *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
$ *   by the U.S. Government is subject to restrictions  as  set  *
$ *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
$ *   or  in  FAR 52.227-19, as applicable.                       *
$ *                                                               *
$ *****************************************************************
$
$ HISTORY
 
$ @(#)$RCSfile: lpbanner.msg,v $ $Revision: 4.2 $ (DEC) $Date: 1991/09/20 00:12:45 $ 8/15/90 SecureWare
$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0
$quote "
$set MS_LPBANNER

LPBANNER_1	"%s: Unknown printer type: %s\n"
LPBANNER_2	"%s: can't allocate space for label IRs\n"
LPBANNER_3	"%s: can't get sensitivity label for %s: %s\n"
LPBANNER_4	"%s: can't get information label for %s: %s\n"
LPBANNER_5	"User"
LPBANNER_6	"Job"
LPBANNER_7	"Printer"
LPBANNER_8	"Date"
