$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0
$quote "
$set MS_LPRCAT

LPRCAT_1	"usage:  %s [-f] [-l] file model\n"
LPRCAT_2	"Where -f suppresses filtering\n"
LPRCAT_3	"      -l suppresses page labeling\n"
LPRCAT_4	"      file is the data file to filter\n"
LPRCAT_5	"      model is the printer model\n"
LPRCAT_6	"%s: %s is not a valid printer model\n"
LPRCAT_7	"%s: descriptor for %s omits page or line length\n"
LPRCAT_8	"%s: ran out of space\n"
LPRCAT_9	"%s: cannot open %s\n"
LPRCAT_10	"%s: no character string length specified"
LPRCAT_11	" for %s"
LPRCAT_12	"%s: no escape string length specified"
