$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0
$quote "
$set MS_MKMULTDIR

MKMULTDIR_1	"usage:  %s [-c] [-m fmode] dir ...\n"
MKMULTDIR_2	"Where -c is create directory if needed\n"
MKMULTDIR_3	"      -m is set directory mode to fmode\n"
MKMULTDIR_4	"      dir is a directory to change/create\n"
MKMULTDIR_5	"%s need the multileveldir authorization\n"
MKMULTDIR_6	"%s: insufficient privileges\n"
MKMULTDIR_7	"%s: mode contains non-octal digit '%c'\n"
MKMULTDIR_8	"%s: cannot create directory "
MKMULTDIR_9	"%s: cannot change mode of "
MKMULTDIR_10	"%s: cannot set multilevel flag of "
$ MKMULTDIR_11	"Not an extended format filesystem.\n"
$ MKMULTDIR_12	"File is already a multilevel directory.\n"
$ MKMULTDIR_13	"Not a directory.\n"
$ MKMULTDIR_14	"Directory not empty.\n"
$ MKMULTDIR_15	"Access denied."
$ MKMULTDIR_16	"Don't own the directory and have appropriate privilege.\n"
