$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0
$quote "
$set MS_PRIVS

PRIVS_1	"usage: %s [-v] [-k] [-b] [{-a|-r|-i} privs] [-c cmd]\n"
PRIVS_2	"%s: not authorized for %s\n"
PRIVS_3	"%s: cannot get kernel authorizations\n"
PRIVS_4	"%s: cannot get base privileges\n"
PRIVS_5	"%s: cannot confirm increased privileges\n"
PRIVS_6	"Kernel authorizations:\n"
PRIVS_7	"Base privileges:\n"
PRIVS_8	"%s: Type Yes to raise base privileges, anything else to abort: "
PRIVS_9	"%s: command aborted\n"
PRIVS_10	"Privilege specification invalid: %s\n"
PRIVS_11	"kernel authorizations"
PRIVS_12	"base privileges"

PRIVS_18	"%s: cannot set new %s\n"
PRIVS_19	"New %s: "
PRIVS_20	"%s: No shell.\n"
YES	"yes"
