$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0
$quote "
$set MS_RMMULTDIR

RMMULTDIR_1	"usage:  %s [-r] dir ...\n"
RMMULTDIR_2	"Where -r means totally remove\n"
RMMULTDIR_3	"      (no -r leaves a regular directory)\n"
RMMULTDIR_4	"      dir is a directory to change/remove\n"
RMMULTDIR_5	"%s: need multileveldir authorization\n"
RMMULTDIR_6	"%s: insufficient privileges\n"
RMMULTDIR_7	"%s: cannot remove "
RMMULTDIR_8	"%s: cannot remove multilevel flag of "
$ RMMULTDIR_9	"Not an extended format filesystem.\n"
$ RMMULTDIR_10	"File is not a multilevel directory.\n"
$ RMMULTDIR_11	"Not a directory.\n"
$ RMMULTDIR_12	"Directory not empty.\n"
$ RMMULTDIR_13	"Access denied."
$ RMMULTDIR_14	"Don't own the directory and have appropriate privilege.\n"
