 
$ *****************************************************************
$ *                                                               *
$ *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
$ *                                                               *
$ *   All Rights Reserved.  Unpublished rights  reserved  under   *
$ *   the copyright laws of the United States.                    *
$ *                                                               *
$ *   The software contained on this media  is  proprietary  to   *
$ *   and  embodies  the  confidential  technology  of  Digital   *
$ *   Equipment Corporation.  Possession, use,  duplication  or   *
$ *   dissemination of the software and media is authorized only  *
$ *   pursuant to a valid written license from Digital Equipment  *
$ *   Corporation.                                                *
$ *                                                               *
$ *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
$ *   by the U.S. Government is subject to restrictions  as  set  *
$ *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
$ *   or  in  FAR 52.227-19, as applicable.                       *
$ *                                                               *
$ *****************************************************************
$
$ HISTORY
 
$ @(#)$RCSfile: setfiles.msg,v $ $Revision: 4.2 $ (DEC) $Date: 1991/09/20 00:13:44 $ 8/30/90 SecureWare
$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0
$quote "
$set MS_SETFILES

SETFILES_1	"%s: need isso authorization\n"
SETFILES_2	"%s: Cannot initialize space for target paths.\n"
SETFILES_3	"usage:  %s [-n] [-v] [-i] [-p prefix] [path] ...\n"
SETFILES_4	"setfiles: can't allocate file done table\n"
SETFILES_5	"%s: Cannot allocate space for path `%s'.\n"
SETFILES_6	"%s: Cannot expand path vector to hold `%s'.\n"
SETFILES_7	"Directory %s (entry %d) is missing.\n"
SETFILES_8	"%s (%sentry %d) ignored.\n"
SETFILES_9	"wildcard "
SETFILES_10	"%s (%sentry %d) is missing.\n"
SETFILES_11	"%s (%sentry %d) is fine.\n"
SETFILES_12	"%s (%sentry %d) reset"
SETFILES_13	" owner"
SETFILES_14	" group"
SETFILES_15	" (failed)"
SETFILES_16	" mode"
SETFILES_17	" type"
SETFILES_18	" type (failed)"
SETFILES_19	" slevel"
SETFILES_20	" caveats"
SETFILES_21	" acl"
SETFILES_22	" pprivs"
SETFILES_23	" gprivs"
SETFILES_24	"setfiles: can't expand fdone table\n"
SETFILES_25	"%s: insufficient privileges\n"
SETFILES_26	"setfiles: can't allocate path check table\n"
SETFILES_27	"setfiles: no file control database entry for %s\n"
