$
$ (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
$ ALL RIGHTS RESERVED
$
$
$ OSF/1 Release 1.0

$quote "
$set MS_RMT
CNAL		"cannot allocate buffer space"
CODBG		"cannot open debug output file %s\n"
CODBG2		"main(): fopen(): %s\n"
ILLCOM		"unrecognized command %c"
REOF		"end-of-file on standard input"
REOI		"read error on standard input"
REOI2		"main(): read(): %s"
REOI3		"getstring(): read(): %s" 
RPEOF		"premature end-of-file on standard input"
SOCSZ		"cannot set socket receive-buffer size"
SOCSZ2		"checkbuf(): setsockopt(): %s" 
USAGE		"Usage: rmt [<debug-output-file>]\n"
WEOSO		"write error on standard output"
WEOSO2		"main(): write(): %s" 
WEOSO3		"acknowledge(): write(): %s" 
WEOSO4		"tape_error(): write(): %s" 
