#!/bin/csh -f
# mdtype,v 1.3 92/02/16 21:29:41 leres Exp $ (LBL)
#
# Determine machine type.
#
set mach="UNKNOWN"
if ( -f /bin/arch ) set mach=`/bin/arch`
if ($mach == "UNKNOWN") then
	set temp=`machine`
	if ($temp != "") set mach=$temp
endif
# Hack, hack...
if ($mach == "sparc") set mach=sun4
echo $mach
if ($mach == "UNKNOWN") exit 1
exit 0
