/*
 * *****************************************************************
 * *                                                               *
 * *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
 * *                                                               *
 * *   All Rights Reserved.  Unpublished rights  reserved  under   *
 * *   the copyright laws of the United States.                    *
 * *                                                               *
 * *   The software contained on this media  is  proprietary  to   *
 * *   and  embodies  the  confidential  technology  of  Digital   *
 * *   Equipment Corporation.  Possession, use,  duplication  or   *
 * *   dissemination of the software and media is authorized only  *
 * *   pursuant to a valid written license from Digital Equipment  *
 * *   Corporation.                                                *
 * *                                                               *
 * *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
 * *   by the U.S. Government is subject to restrictions  as  set  *
 * *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
 * *   or  in  FAR 52.227-19, as applicable.                       *
 * *                                                               *
 * *****************************************************************
 */
/*
 * HISTORY
 */

/*
 * DO NOT EDIT -- DO NOT EDIT -- DO NOT EDIT -- DO NOT EDIT
 *
 * This file contains declarations and data for the divide and remainder
 * RTL routines. It was machine generated by gendivglobl
 *
 * DO NOT EDIT -- DO NOT EDIT -- DO NOT EDIT -- DO NOT EDIT
 */

#define BIT_LENGTH 8
#define BIT_VALUE (1<<BIT_LENGTH)
#define BIT_MASK (BIT_VALUE-1)
#define K_BIT_LENGTH 8
#define K_BIT_VALUE (1<<K_BIT_LENGTH)
#define K_BIT_MASK (K_BIT_VALUE-1)

#define TABLE_BIAS 16384

#define LOG2TAB -16384
#define INV_FLAG -15360
#define INV -14848
#define INV_M -14840

#define A $24
#define B $25
#define Q $27
#define RA $23

	.globl	__divdat
