#! /bin/sh
#
# *****************************************************************
# *                                                               *
# *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
# *                                                               *
# *   All Rights Reserved.  Unpublished rights  reserved  under   *
# *   the copyright laws of the United States.                    *
# *                                                               *
# *   The software contained on this media  is  proprietary  to   *
# *   and  embodies  the  confidential  technology  of  Digital   *
# *   Equipment Corporation.  Possession, use,  duplication  or   *
# *   dissemination of the software and media is authorized only  *
# *   pursuant to a valid written license from Digital Equipment  *
# *   Corporation.                                                *
# *                                                               *
# *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
# *   by the U.S. Government is subject to restrictions  as  set  *
# *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
# *   or  in  FAR 52.227-19, as applicable.                       *
# *                                                               *
# *****************************************************************
#
# HISTORY
#
 
#
# turn on/off auditd; set/clear auditmask
#

AUDITD=/usr/sbin/auditd
AUDITMASK=/usr/sbin/auditmask
RCMGR=/usr/sbin/rcmgr


case "$1" in

'start')
        # enable auditd
        #
        AUDITD_FLAG=`$RCMGR get AUDITD_FLAG`
        [ "$AUDITD_FLAG" = "" ] && exit
        $AUDITD $AUDITD_FLAG


        # set auditmask
        #
        AUDITMASK_FLAG=`$RCMGR get "AUDITMASK_FLAG"`
        [ "$AUDITMASK_FLAG" = "" ] && exit 0

        for ARG in $AUDITMASK_FLAG
        do
            [ "$ARG" = "<" ] && {
                INPUT=1
                continue
            }
            [ "$INPUT" = 1 ] && {
                EVNTFILE="$ARG"
                break
            }
            AMASKARG="$AMASKARG $ARG"
        done

        case $INPUT in
        1)  $AUDITMASK $AMASKARG < $EVNTFILE    ;;
        *)  $AUDITMASK $AMASKARG    ;;
        esac
        ;;

 
'stop') 
        /bin/ps -e | grep auditd | grep -vqs grep
        [ $? = 0 ] && $AUDITD -k
        $AUDITMASK -n -s exec_argp:0 -s exec_envp:0 -s login_uname:0
        ;;


*)      
        echo "usage: $0 {start|stop}"
        ;;

esac
