#!/sbin/sh
# 
# *****************************************************************
# *                                                               *
# *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
# *                                                               *
# *   All Rights Reserved.  Unpublished rights  reserved  under   *
# *   the copyright laws of the United States.                    *
# *                                                               *
# *   The software contained on this media  is  proprietary  to   *
# *   and  embodies  the  confidential  technology  of  Digital   *
# *   Equipment Corporation.  Possession, use,  duplication  or   *
# *   dissemination of the software and media is authorized only  *
# *   pursuant to a valid written license from Digital Equipment  *
# *   Corporation.                                                *
# *                                                               *
# *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
# *   by the U.S. Government is subject to restrictions  as  set  *
# *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
# *   or  in  FAR 52.227-19, as applicable.                       *
# *                                                               *
# *****************************************************************
#
# HISTORY
# 
# (c) Copyright 1990, OPEN SOFTWARE FOUNDATION, INC.
# ALL RIGHTS RESERVED
#
#
# OSF/1 Release 1.0

PATH=/sbin:/usr/sbin:/usr/bin
export PATH

case "$1" in
'start')
	set `who -r`
	if [ "$9" = "S" ]; then
		if [ -f /usr/sbin/sendmail ]; then 
			(cd /usr/spool/mqueue; rm -f lf*)
			# Frozen configs not supported
			# /usr/sbin/sendmail -bz
			/usr/sbin/sendmail -bi
			/usr/sbin/sendmail -bd -q15m -om &
			echo "SMTP Mail Service started"
		else
			echo "Unable to start SMTP Mail Service, No /usr/sbin/sendmail"
			exit 1
		fi
	else
		echo "Unable to start SMTP Mail Service, Run level must be S"
		exit 1
	fi
	;;
'stop')
	pid=`/bin/ps -e | grep sendmail | grep connection | sed -e 's/^  *//' -e 's/ .*//' | head -1`
	if [ "X$pid" != "X" ]; then
		/bin/kill $pid
	else
		echo "No pid for SMTP Mail Service found"
		exit 1
	fi
	;;
'restart')
	/sbin/init.d/sendmail stop
	if [ $? -ne 0 ]; then
		echo "  -- Could not find running sendmail - attempting to restart..."
	fi
	sleep 2
	pid=`/bin/ps -e | grep sendmail | grep connection | sed -e 's/^  *//' -e 's/ .*//' | head -1`
	if [ "X$pid" != "X" ]; then
		sleep 3
		pid=`/bin/ps -e | grep sendmail | grep connection | sed -e 's/^  *//' -e 's/ .*//' | head -1`
		if [ "X$pid" != "X" ]; then
			echo "Could not kill SMTP Mail Service" 
			echo "  -- Kill sendmail by hand then do a start"
			exit 1
		fi
	fi
	/sbin/init.d/sendmail start | sed -e 's/start/restart/'
	;;
*)
	echo "usage: $0 {start|stop|restart}"
	;;
esac
