#!/bin/sh
# Assign ownership of the console to the invoking user
#
# By convention, both xconsole and xterm -C check that the
# console is owned by the invoking user and is readable before attaching
# the console output.  This way a random user can invoke xterm -C without
# causing serious grief.
#
# However, don't give up ownership of the console if the alternate console
# is in use, that is, if the graphics display device is not the console.
#
case `/usr/sbin/sizer -wc` in
1)
  ;;
*)
  chown $USER /dev/console
  ;;
esac



