DisplayManager.errorLogFile:	XDMDIR/xdm-errors
DisplayManager.pidFile:		XDMDIR/xdm-pid
DisplayManager.keyFile:		XDMDIR/xdm-keys
DisplayManager.servers:		XDMDIR/Xservers
DisplayManager.accessFile:	XDMDIR/Xaccess
DisplayManager.greeterLib:	XDMDIR/libXdmDecGreet.so
DisplayManager._0.authorize:	true
DisplayManager._0.setup:	XDMDIR/Xsetup_0
DisplayManager._0.startup:	XDMDIR/GiveConsole
DisplayManager._0.reset:	XDMDIR/TakeConsole
DisplayManager.local_0.authorize:	true
DisplayManager.local_0.setup:	XDMDIR/Xsetup_0
DisplayManager.local_0.startup:	XDMDIR/GiveConsole
DisplayManager.local_0.reset:	XDMDIR/TakeConsole
DisplayManager*resources:	XDMDIR/Xresources
DisplayManager*session:		XDMDIR/Xsession
DisplayManager*authComplain:	false
DisplayManager*keymaps:		XDMDIR/Xkeymaps
