#!/bin/sh

if [ -d $HOME -a -w $HOME ]
then
	exec > $HOME/.xsession-errors 2>&1
else
	echo "Xsession: $HOME directory not writeable by $USER" > /dev/console
	exec dxterm -geometry 80x40+0+0
	# exec xterm -geometry 80x24+0+0
fi

case $# in
1)
	case $1 in
	failsafe)
		exec dxterm -geometry 80x40+0+0
		# exec xterm -geometry 80x24+0+0
		;;
	esac
esac

startup=$HOME/.xsession
resources=$HOME/.Xresources

if [ -f $startup ]; then
	if [ -x $startup ]
	then
		exec $startup
	else
		exec /bin/sh $startup
	fi
else
	if [ -f $resources ]; then
		xrdb -load -retain $resources
	fi
	#
	# Motif/DECWindows Version
	#
	dxsession

	#
	# MIT/Athena Version
	#
	# For a MIT/Athena version, 
	# uncomment the following lines and comment the Motif lines above

  	# xconsole -geometry 480x130-0-0 -daemon -notify -verbose -fn fixed -exitOnFail
	# twm &
	# exec xterm -geometry 80x24+10+10 -ls
fi

