/*
 * *****************************************************************
 * *                                                               *
 * *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
 * *                                                               *
 * *   All Rights Reserved.  Unpublished rights  reserved  under   *
 * *   the copyright laws of the United States.                    *
 * *                                                               *
 * *   The software contained on this media  is  proprietary  to   *
 * *   and  embodies  the  confidential  technology  of  Digital   *
 * *   Equipment Corporation.  Possession, use,  duplication  or   *
 * *   dissemination of the software and media is authorized only  *
 * *   pursuant to a valid written license from Digital Equipment  *
 * *   Corporation.                                                *
 * *                                                               *
 * *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
 * *   by the U.S. Government is subject to restrictions  as  set  *
 * *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
 * *   or  in  FAR 52.227-19, as applicable.                       *
 * *                                                               *
 * *****************************************************************
 */
/*
 * HISTORY
 */
/*
 * @(#)$RCSfile: man_status.h,v $ $Revision: 1.1.2.2 $ (DEC) $Date: 1993/04/26 22:10:23 $
 */
/**/
/******************************************************************************/
/**                                                                          **/
/**  Copyright (c) 1992                                                      **/
/**  by DIGITAL Equipment Corporation, Maynard, Mass.                        **/
/**                                                                          **/
/**  This software is furnished under a license and may be used and  copied  **/
/**  only  in  accordance  with  the  terms  of  such  license and with the  **/
/**  inclusion of the above copyright notice.  This software or  any  other  **/
/**  copies  thereof may not be provided or otherwise made available to any  **/
/**  other person.  No title to and ownership of  the  software  is  hereby  **/
/**  transferred.                                                            **/
/**                                                                          **/
/**  The information in this software is subject to change  without  notice  **/
/**  and  should  not  be  construed  as  a commitment by DIGITAL Equipment  **/
/**  Corporation.                                                            **/
/**                                                                          **/
/**  DIGITAL assumes no responsibility for the use or  reliability  of  its  **/
/**  software on equipment which is not supplied by DIGITAL.                 **/
/**                                                                          **/
/******************************************************************************/
/********************************************************************************************************************************/
/* Created 27-APR-1992 22:01:17 by VAX SDL V3.2-12     Source: 27-APR-1992 22:01:10 DSK$RESD$:[AGENT.SRC]MAN_STATUS.SDL;1 */
/********************************************************************************************************************************/
 
/*** MODULE $MAN_DEF ***/
/*                                                                          */
/* This SDL File Generated by VAX-11 Message V04-00 on 27-APR-1992 22:01:11.41 */
/*                                                                          */
/*                                                                          */
/*************************************************************************** */
/**                                                                        * */
/**  COPYRIGHT (C) 1990, 1991, 1992 BY                                     * */
/**  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.                * */
/**  ALL RIGHTS RESERVED.                                                  * */
/**                                                                        * */
/**  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED * */
/**  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE  * */
/**  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER * */
/**  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY * */
/**  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE SOFTWARE IS  HEREBY  * */
/**  TRANSFERRED.                                                          * */
/**                                                                        * */
/**  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE * */
/**  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT * */
/**  CORPORATION.                                                          * */
/**                                                                        * */
/**  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR RELIABILITY OF ITS  * */
/**  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.               * */
/**                                                                        * */
/**                                                                        * */
/*************************************************************************** */
/*                                                                          */
/*                                                                          */
/*                                                                          */
/* MAN_STATUS.MSG                                                           */
/*                                                                          */
/* THIS FILE DEFINES THE MAN_STATUS VALUES AND MESSAGES.  THE MESSAGES      */
/* ARE USED BY VMS.  THE VALUES BY ALL IMPLEMENTATIONS OF THE COMMON        */
/* AGENT.                                                                   */
/*                                                                          */
/* THIS FILE IS USED TO GENERATE AN SDL FILE.  THE SDL FILE IS USED IN      */
/* TURN TO GENERATE AN .H FILE FOR C LANGUAGE USERS.                        */
/*                                                                          */
/************************************************************************!  */
/*									!   */
/* N.B.	WHEN MAKING MODIFICATIONS TO THIS FILE, BE SURE TO MAKE THE	!   */
/*	EQUIVALENT CHANGES TO MAN.H.					!   */
/*									!   */
/************************************************************************!  */
/*                                                                          */
/* AUTHOR: STEVE PITCHER	8-NOV-1990                                  */
/*                                                                          */
/* REVISION HISTORY:                                                        */
/*                                                                          */
/*   F-19	GJA			GARY J. ALLISON		25-APR-1992 */
/*		ADD BL7 MOMGEN MESSAGES.                                    */
/*                                                                          */
/*   F-17	SMG		SUSAN M. GEORGE			17-APR-1992 */
/*		ADD MAN_C_PROFILE_NOT_DISABLED STATUS CODE.                 */
/*                                                                          */
/*   F-17	SMG		SUSAN M. GEORGE			17-APR-1992 */
/*		ADD MAN_C_PROFILE_NOT_ENABLED STATUS CODE.                  */
/*                                                                          */
/*   F-16	DMR1176		DAVID M. ROSENBERG		 8-APR-1992 */
/*		ADD STATUS CODES FOR MOSS_INSTANCE_NAME_SUPPORT.C.          */
/*		ADD MAN_C_NEGATIVE_CONSTRUCT_LEVEL FOR MOSS_AVL_VERIFY().   */
/*                                                                          */
/*   F-13	JMA060		J. ALBERT			12-MAR-1992 */
/*		ADD RETURN STATUS' FROM MOSS_AVL_VERIFY FOR                 */
/*		START AND  END CONSTRUCTION.                                */
/*                                                                          */
/*   F-12	ND1053		NESTOR DUTKO			17-JAN-1992 */
/*		ADD RETURN STATUS' FROM MOSS_CHECK_ACCESS.                  */
/*                                                                          */
/*   F-11	RJB1132		RICHARD J. BOUCHARD JR.		12-DEC-1991 */
/*		CHANGE MODULE TITLE TO BE A FORMAT WE CAN SHOW USERS.       */
/*                                                                          */
/*   F-10	PRD		PAUL R. DESTEFANO		03-DEC-1991 */
/*		CHANGED TEXT OF PROCESSING_FAILURE TO A MORE GENERAL        */
/*		MESSAGE.                                                    */
/*                                                                          */
/*   F-9		GJA			GARY J. ALLISON		22-OCT-1991 */
/*		ADD MOMGEN MESSAGES.                                        */
/*                                                                          */
/*   F-8		SME			SUE ELBEERY		17-OCT-1991 */
/*		ADD MAN_C_NO_SUCH_PROFILE CODE.                             */
/*                                                                          */
/*   F-7		PRD			PAUL R. DESTEFANO	07-OCT-1991 */
/*		ADD SEVERAL NEW EVD CODES.                                  */
/*                                                                          */
/*   F-6		RNM0152			RUSS MURRAY		10-SEP-1991 */
/*		ADD ACCESS_VIOLATION                                        */
/*                                                                          */
/*   F-5 	ND1000			NESTOR DUTKO		5-SEP-1991  */
/*		BUMP BASE OF VMS SPECIFIC MESSAGES TO .BASE 2000.           */
/*		ADD DSM AUTHENTICATION MESSAGES                             */
/*                                                                          */
/*   F-4					SUE ELBEERY		29-AUG-1991 */
/*		ADD MOM PROFILER ERROR CODES                                */
/*                                                                          */
/*   F-3					STEVE PITCHER		9-JUL-1991 */
/*		BRING UP TO DECWEST 1G LEVEL                                */
/*                                                                          */
/*   F-2					STEVE PITCHER		25-FEB-1991 */
/*		USE ASSIGNED FACILITY CODE = 1422.                          */
/*		ADD MIRIAM'S ADDITIONS TO MAN.H.                            */
/*                                                                          */
/*   F-1					STEVE PITCHER		29-NOV-1990 */
/*		MAKE FALSE AND NOT_EQUAL INFORMATIONALS.                    */
/*                                                                          */
/*                                                                          */
/*                                                                          */
#define MAN$_FACILITY 1422
#define MAN_K_SUCCESS 93225041
/*                                                                          */
/* CMIP (ISO AND DNA) ERROR RETURN VALUES                                   */
/*                                                                          */
#define MAN_K_NO_SUCH_CLASS 93225762
#define MAN_K_NO_SUCH_OBJECT_INSTANCE 93225770
#define MAN_K_ACCESS_DENIED 93225778
#define MAN_K_SYNC_NOT_SUPPORTED 93225786
#define MAN_K_INVALID_FILTER 93225794
#define MAN_K_NO_SUCH_ATTRIBUTE_ID 93225802
#define MAN_K_INVALID_ATTRIBUTE_VALUE 93225810
#define MAN_K_GET_LIST_ERROR 93225818
#define MAN_K_SET_LIST_ERROR 93225826
#define MAN_K_NO_SUCH_ACTION 93225834
#define MAN_K_PROCESSING_FAILURE 93225842
#define MAN_K_DUPLICATE_M_O_INSTANCE 93225850
#define MAN_K_NO_SUCH_REFERENCE_OBJECT 93225858
#define MAN_K_NO_SUCH_EVENT_TYPE 93225866
#define MAN_K_NO_SUCH_ARGUMENT 93225874
#define MAN_K_INVALID_ARGUMENT_VALUE 93225882
#define MAN_K_INVALID_SCOPE 93225890
#define MAN_K_INVALID_OBJECT_INSTANCE 93225898
#define MAN_K_MISSING_ATTRIBUTE_VALUE 93225906
#define MAN_K_CLASS_INSTANCE_CONFLICT 93225914
#define MAN_K_COMPLEXITY_LIMITATION 93225922
#define MAN_K_MISTYPED_OPERATION 93225930
#define MAN_K_NO_SUCH_INVOKE_ID 93225938
#define MAN_K_OPERATION_CANCELLED 93225946
#define MAN_K_INVALID_OPERATOR 93225954
#define MAN_K_INVALID_OPERATION 93225962
#define MAN_K_DIRECTIVE_NOT_SUPPORTED 93225970
#define MAN_K_ENTITY_CLASS_NOT_SUPPORTD 93225978
#define MAN_K_INVALID_USE_OF_WILDCARD 93225986
#define MAN_K_CONSTRAINT_VIOLATION 93225994
#define MAN_K_WRITE_ONLY_ATTRIBUTE 93226002
#define MAN_K_READ_ONLY_ATTRIBUTE 93226010
#define MAN_K_DUPLICATE_ATTRIBUTE 93226018
#define MAN_K_DUPLICATE_ARGUMENT 93226026
#define MAN_K_REQUIRED_ARGUMENT_OMITTED 93226034
#define MAN_K_FILTER_INVALID_FOR_ACTION 93226042
#define MAN_K_INSUFFICIENT_RESOURCES 93226050
#define MAN_K_NO_SUCH_ATTRIBUTE_GROUP 93226058
#define MAN_K_FILTER_USED_WITH_CREATE 93226066
/*                                                                          */
/* ADDITIONAL CMIP ERROR VALUES (CURRENTLY NOT DEFINED IN A SPEC)           */
/*                                                                          */
#define MAN_K_WILD_NOT_AT_LOWEST_LEVEL 93226562
#define MAN_K_WILD_CLASS_WITH_FILTER 93226570
#define MAN_K_WILD_INVALID_DIRECTIVE 93226578
#define MAN_K_WILD_WITH_CREATE 93226586
#define MAN_K_WILD_INVALID_GROUP 93226594
#define MAN_K_SCOPE_TOO_COMPLEX 93226602
#define MAN_K_SYNC_TOO_COMPLEX 93226610
#define MAN_K_FILTER_TOO_COMPLEX 93226618
/*                                                                          */
/* MOSS SPECIFIC ERROR RETURN CODES                                         */
/*                                                                          */
#define MAN_K_ALREADY_INITIALIZED 93227362
#define MAN_K_BAD_PARAMETER 93227370
#define MAN_K_FAILURE 93227378
#define MAN_K_HANDLE_NOT_BOUND 93227386
#define MAN_K_HAS_ACTIVE_CHILDREN 93227394
#define MAN_K_MO_TIMEOUT 93227402
#define MAN_K_MOLD_TIMEOUT 93227410
#define MAN_K_NO_ELEMENT 93227418
#define MAN_K_NO_MOLD 93227426
#define MAN_K_NO_REPLY 93227434
#define MAN_K_NO_SUCH_PARENT_CLASS 93227442
#define MAN_K_NOT_CONSTRUCTED 93227450
#define MAN_K_NOT_INITIALIZED 93227458
#define MAN_K_OBJECT_ALREADY_EXISTS 93227466
#define MAN_K_PE_TIMEOUT 93227474
#define MAN_K_READ_ONLY 93227482
#define MAN_K_MISSING_END_CONST 93227490
#define MAN_K_END_WITHOUT_START_CONST 93227498
#define MAN_K_MISSING_PARAMETER 93227506
#define MAN_K_BAD_START_OF_CONSTRUCT 93227514
#define MAN_K_BAD_END_OF_CONSTRUCT 93227522
#define MAN_K_NO_SUCH_RDN 93227530
#define MAN_K_NO_SUPERIOR_INSTANCE 93227538
#define MAN_K_MODULE_RDN_CANT_BE_GLOBAL 93227546
#define MAN_K_RDN_IS_CONSTRUCTED 93227554
#define MAN_K_NEGATIVE_CONSTRUCT_LEVEL 93227562
/*                                                                          */
/* MOSS CONDITIONAL RETURN CODES                                            */
/*                                                                          */
#define MAN_K_EQUAL 93228163
#define MAN_K_TRUE 93228171
#define MAN_K_NOT_EQUAL 93228179
#define MAN_K_FALSE 93228187
#define MAN_K_LESS 93228195
#define MAN_K_GREATER 93228203
/*                                                                          */
/* SNMP SPECIFIC RETURN CODES                                               */
/*                                                                          */
#define MAN_K_NOT_SUPPORTED 93228962
#define MAN_K_END_OF_MIB 93228970
/*                                                                          */
/* EVD RETURN CODES                                                         */
/*                                                                          */
#define MAN_K_NO_QUEUE 93229762
#define MAN_K_BAD_HANDLE 93229770
#define MAN_K_ILLEGAL_EVENT_SIZE 93229778
#define MAN_K_NO_EVENT 93229786
#define MAN_K_TRUNCATED 93229794
#define MAN_K_ILLEGAL_INSTANCE_STATE 93229802
#define MAN_K_NO_OPER 93229810
#define MAN_K_EXASTLM 93229818
#define MAN_K_EXENQLM 93229826
#define MAN_K_SUBSYSTEM_DISABLED 93229834
#define MAN_K_INSUFFICIENT_VM 93229842
#define MAN_K_INSUFFICIENT_SYSMEM 93229850
/*                                                                          */
/* MOM PROFILER RETURN CODES                                                */
/*                                                                          */
#define MAN_K_PIR_INITIALIZATION_ERROR 93240962
#define MAN_K_PIR_ACCESS_FAILURE 93240970
#define MAN_K_REGISTRATION_FAILURE 93240978
#define MAN_K_MOLD_ACCESS_FAILURE 93240986
#define MAN_K_PREREGISTRATION_FAILURE 93240994
#define MAN_K_THREAD_CREATION_FAILURE 93241002
#define MAN_K_MOM_ALREADY_STARTED 93241010
#define MAN_K_PROFILE_CREATION_FAILURE 93241018
#define MAN_K_NO_SUCH_METHOD 93241026
#define MAN_K_MOM_ALREADY_STOPPED 93241034
#define MAN_K_STOP_FAILURE 93241042
#define MAN_K_STOP_IN_PROGRESS 93241050
#define MAN_K_START_IN_PROGRESS 93241058
#define MAN_K_PROFILE_ALREADY_EXISTS 93241066
#define MAN_K_NO_SUCH_PROFILE 93241074
#define MAN_K_PROFILE_NOT_ENABLED 93241082
#define MAN_K_PROFILE_NOT_DISABLED 93241090
/*                                                                          */
/* DSM AUTHENTICATION/AUTHORIZATION RETURN CODES                            */
/*                                                                          */
#define MAN_K_INVCREDENTIAL 93244962
#define MAN_K_SEC_NOT_INITIALIZED 93244970
#define MAN_K_INSUFFICIENT_ARG_VALUES 93244978
/*                                                                          */
/* MOM GENERATOR RETURN CODES                                               */
/*                                                                          */
#define MAN_K_MOMGEN_ERROR 93248962
#define MAN_K_MIR_NOT_FOUND 93248970
#define MAN_K_MIR_ERROR 93248978
#define MAN_K_MCC_ERROR 93248986
#define MAN_K_INV_INFO_FILE 93248994
#define MAN_K_INT_MOMGEN_ERROR 93249002
#define MAN_K_NO_OID_FOUND 93249010
#define MAN_K_NO_CLASSES 93249018
#define MAN_K_NO_AUTHOR 93249026
#define MAN_K_NO_FACILITY 93249034
#define MAN_K_NO_ORGANIZATION 93249042
#define MAN_K_NO_PARENT_CLASS 93249050
#define MAN_K_NO_CLASS_PREFIX 93249058
#define MAN_K_NO_MOM_NAME 93249066
#define MAN_K_INV_NUM_PREFIXES 93249074
#define MAN_K_INV_NUM_PARENT_CLASSES 93249082
#define MAN_K_NO_DNA_CMIP_INT 93249090  /*                                  */
/* OTHER STATUS CODES.                                                      */
/*                                                                          */
#define MAN_K_BUGCHECK 93249100
#define MAN_K_ACCESS_VIOLATION 93249108
