.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: access.3,v $ $Revision: 3.2.2.2 $ (DEC) $Date: 1992/05/26 15:51:23 $
.\"
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\" @(#)access.3f 6.2 (Berkeley) 5/27/86
.\"
.TH access 3
.SH NAME
access \- determine accessibility of a file
.SH SYNOPSIS
.PP
.B integer function access (name, mode)
.br
.B character*(*) name, mode
.SH DESCRIPTION
.PP
.B access
checks the given file,
\*Vname,\*O
for accessibility with respect to the caller according to
\*Vmode.\*O
\*Vmode\*O
may include in any order and in any combination one or more of:
.RS
.TP 12
\f3r\f1
test for read permission
.TP
\f3w\f1
test for write permission
.TP
\f3x\f1
test for execute permission
.TP
(blank)
test for existence
.RE
.PP
An error code is returned if either argument is illegal, or if the file
cannot be accessed in all of the specified modes.
0 is returned if the specified access would be successful.
.SH RESTRICTIONS
.PP
Pathnames can be no longer than
.SM MAXPATHLEN
as defined in
.RI < sys/param.h >.
.SH FILES
.PP
\*V/usr/lib/libU77.a\*O
.SH RELATED INFORMATION
.PP
\*Laccess\*O(2), \*Lperror\*O(3)
.EQ
delim off
.EN
