.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: addwchstr.3,v $ $Revision: 1.1.3.3 $ (DEC) $Date: 1993/11/16 00:00:06 $
.\"
.TH addwchstr 3
.SH NAME
\*Laddwchstr\*O, \*Laddwchnstr\*O, \*Lwaddwchstr\*O, \*Lwaddwchnstr\*O, \*Lmvaddwchstr\*O, \*Lmvaddwchnstr\*O, \*Lmvwaddwchstr\*O, \*Lmvwaddwchnstr\*O \- Add a string of wchar_t characters (and attributes) to a curses window
.SH LIBRARY
.PP
The \*Lcurses\*O library (\*Llibcurses.so\*O, \*Llibcurses.a\*O)
.SH SYNOPSIS
.PP
.sS
\*L#include <curses.h>\*O
.PP
\*Lint addwchstr(chtype \(**\*Vwchstr\*L);\*O
.PP
\*Lint addwchnstr(
.br
        chtype \(**\*Vwchstr\*L,
.br
        int \*Vn\*L);\*O
.PP
\*Lint waddwchstr(
.br
        WINDOW \(**\*Vwin\*L,
.br
        chtype \(**\*Vwchstr\*L);\*O
.PP
\*Lint waddwchnstr(
.br
        WINDOW \(**\*Vwin\*L,
.br
        chtype \(**\*Vwchstr\*L,
.br
        int \*Vn\*L);\*O
.PP
\*Lint mvaddwchstr(
.br
        int \*Vy\*L,
.br
        int \*Vx\*L,
.br
        chtype \(**\*Vwchstr\*L);\*O
.PP
\*Lint mvaddwchnstr(
.br
        int \*Vy\*L,
.br
        int \*Vx\*L,
.br
        chtype \(**\*Vwchstr\*L,
.br
        int \*Vn\*L);\*O
.PP
\*Lint mvwaddwchstr(
.br
        WINDOW \(**\*Vwin\*L,
.br
        int \*Vy\*L,
.br
        int \*Vx\*L,
.br
        chtype \(**\*Vwchstr\*L);\*O
.PP
\*Lint mvwaddwchnstr(
.br
        WINDOW \(**\*Vwin\*L,
.br
        int \*Vy\*L,
.br
        int \*Vx\*L,
.br
        chtype \(**\*Vwchstr\*L,
.br
        int \*Vn\*L);\*O
.sE
.SH PARAMETERS
.PP
.VL
.LI "\*Vwchstr\*O"
Specifies the wide-character string to be added to the window.
.LI "\*Vwin\*O"
Specifies a \*Lcurses\*O window. If not specified, the
window is the default window \*Lstdscr\*O.
.LI "\*Vy\*O, \*Vx\*O"
Specifies the line (\*Vy\*O) and column (\*Vx\*O)
coordinates of the target position on the window.
If coordinates are not specified, the target
position is the current position of the logical cursor.
.LI "\*Vn\*O"
Specifies the maximum number of wide characters to be added
from the string.
.LE
.SH DESCRIPTION
.PP
.iX "addwchstr macro"
.iX "addnwstr macro"
.iX "waddwchstr macro"
.iX "waddnwstr subroutine"
.iX "mvaddwchstr macro"
.iX "mvaddnwstr macro"
.iX "mvwaddwchstr macro"
.iX "mvwaddnwstr macro"
The \*Laddwchstr\*O routine writes all the characters of the
wchar_t character string \*Vwchstr\*O
on the default window at the current (\*Vy\*O, \*Vx\*O) coordinates.
.PP
The \*Laddwchnstr\*O routine writes at most \*Vn\*O characters of the
wchar_t character string \*Vwchstr\*O
on the default window at the current (\*Vy\*O, \*Vx\*O) coordinates.
.PP
The \*Lwaddwchstr\*O routine writes all the characters of the
wchar_t character string \*Vwchstr\*O
on the specified window at the current (\*Vy\*O, \*Vx\*O) coordinates.
.PP
The \*Lwaddwchnstr\*O routine writes at most \*Vn\*O characters of the
wchar_t character string \*Vwchstr\*O
on the specified window at the current (\*Vy\*O, \*Vx\*O) coordinates.
.PP
The \*Lmvaddwchstr\*O routine writes all the characters of the
wchar_t character string \*Lwchstr\*O
on the default window at the specified (\*Vy\*O, \*Vx\*O) coordinates.
.PP
The \*Lmvaddwchnstr\*O routine writes at most \*Vn\*O characters of the
wchar_t character string \*Vwchstr\*O
on the default window at the specified (\*Vy\*O, \*Vx\*O) coordinates.
.PP
The \*Lmvwaddwchstr\*O routine writes all the characters of the
wchar_t character string \*Vwchstr\*O
on the specified window at the specified (\*Vy\*O, \*Vx\*O) coordinates.
.PP
The \*Lmvwaddwchnstr\*O routine writes at most \*Vn\*O characters of the
wchar_t character string \*Vwchstr\*O
on the specified window at the specified (\*Vy\*O, \*Vx\*O) coordinates.
.PP
For those routines with \*Vn\*O as the last argument, if \*Vn\*O is \-1
then the whole string is written to the window.
.PP
The following information applies to all the routines:
.ML
.LI
The cursor position is \*Enot\*O advanced after the write operation.
.LI
\*LERR\*O (error) is returned if writing the string causes illegal scrolling.
.IP
In this case, the routine will write as much of the string
on the window as possible.
.LE
.PP
The
\*Laddwchstr\*O, \*Laddwchnstr\*O, \*Lwaddwchstr\*O, \*Lmvaddwchstr\*O,
\*Lmvaddwchnstr\*O, \*Lmvwaddwchstr\*O, and \*Lmvwaddwchnstr\*O
routines are macros.
.SH RETURN VALUES
.PP
The \*Laddwchstr\*O, \*Laddwchnstr\*O, \*Lwaddwchstr\*O, \*Lwaddwchnstr\*O,
\*Lmvaddwchstr\*O, \*Lmvaddwchnstr\*O, \*Lmvwaddwchstr\*O, and
\*Lmvwaddwchnstr\*O routines return OK on success and ERR on error.
.SH RELATED INFORMATION
.PP
Functions: \*Laddwstr\*O(3), \*Lcurses\*O(3), \*Lcurses_intro\*O(3),
\*Linwstr\*O(3).
.EQ
delim off
.EN
