.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: chdir.3,v $ $Revision: 3.2.2.2 $ (DEC) $Date: 1992/05/26 15:53:28 $
.\"
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\" @(#)chdir.3f 6.1 (Berkeley) 5/15/85
.\"
.TH chdir 3
.SH NAME
chdir \- change default directory
.SH SYNOPSIS
.PP
.B integer function chdir (dirname)
.br
.B character*(*) dirname
.SH DESCRIPTION
.PP
The default directory for creating and locating files will be
changed to
\*Vdirname.\*O
Zero is returned if successful; an error code otherwise.
.SH FILES
.PP
.ie \nM /usr/ucb/lib/libU77.a
.el /usr/lib/libU77.a
.SH RELATED INFORMATION
.PP
\*Lchdir\*O(2), \*Lcd\*O(1), \*Lperror\*O(3)
.SH RESTRICTIONS
.PP
Pathnames can be no longer than MAXPATHLEN as defined in
.RI < sys/param.h >.
.PP
Use of this function may cause
.B inquire
by unit to fail.
.EQ
delim off
.EN
