.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: clearenv.3,v $ $Revision: 3.2.2.2 $ (DEC) $Date: 1992/05/15 15:04:17 $
.\"
.\" 
.\" (c) Copyright 1991, OPEN SOFTWARE FOUNDATION, INC.
.\" ALL RIGHTS RESERVED
.\" 
.\"
.\"
.TH clearenv 3
.SH NAME
\*Lclearenv\*O \- Clears the process environment
.SH LIBRARY
\*OStandard C Library (\*Llibc.a\*O)
.SH SYNOPSIS 
.sS
.iS
\*L#include <stdlib.h>
.sp .4v
\*Lint clearenv ( void );
.iE
.sE
.SH DESCRIPTION
.iX "clearenv function"
.iX "process" "clearing environment"
.PP
The
\*Lclearenv(\|)\*O
function clears the process environment.  No environment variables are
defined immediately after a call to
\*Lclearenv(\|)\*O.
The
\*Lclearenv(\|)\*O
function sets the value of the external variable
\*Lenviron\*O
to NULL.
.SH NOTES
.VL 1.5i
.LI "\*LAES Support Level:\*O"
Trial use
.LE
.SH RETURN VALUES
.nL
Upon successful completion, the
\*Lclearenv(\|)\*O function
returns 0 (zero).
Otherwise, it returns \-1.
.PP 
If
\*Lenviron\*O
has been modified by anything other than the
\*Lputenv(\|) ,\*O
\*Lgetenv(\|) ,\*O
or
\*Lclearenv(\|)\*O
functions, then
\*Lclearenv(\|)\*O
will return an error and the process
environment will remain unchanged.
.SH RELATED INFORMATION
.PP 
Functions:
\*Lexec\*O(2),
\*Lgetenv\*O(3),
\*Lputenv\*O(3)
.iX "clearenv function"
.EQ
delim off
.EN
