.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: clock.3,v $ $Revision: 3.2.2.2 $ (DEC) $Date: 1992/05/15 15:05:02 $
.\"
.\" 
.\" (c) Copyright 1991, OPEN SOFTWARE FOUNDATION, INC.
.\" ALL RIGHTS RESERVED
.\" 
.\"
.\"
.TH clock 3
.SH NAME
\*Lclock\*O \- Reports CPU time used
.SH LIBRARY
\*OStandard C Library (\*Llibc.a\*O)
.SH SYNOPSIS 
.sS
.PP 
\*L#include <time.h>
.PP 
\*Lclock_t clock (void);
.sE 
.SH DESCRIPTION
.iX "clock function"
.iX "CPU time" "returning"
.iX "process" "returning CPU time used"
.PP 
The \*Lclock(\|)\*O function reports the amount of processor
time used by the calling process.
.SH NOTES
.PP 
The \*Lclock(\|)\*O function is made obsolete by the \*Lgetrusage(\|)\*O
function; however, it is included for compatibility with older
BSD programs.
.VL 1.5i
.LI "\*LAES Support Level:\*O"
Full use
.LE
.SH RETURN VALUES
.PP 
The \*Lclock(\|)\*O function returns the amount of processor
time (in microseconds) used since the first call to \*Lclock(\|)\*O.
To determine the time in seconds, divide the value returned by
\*Lclock(\|)\*O
by the value CLOCKS_PER_SEC.  If the processor time
used is not available or its value cannot be represented, the
\*Lclock(\|)\*O
function returns (\*Lclock_t\*O)-1.
.SH RELATED INFORMATION
.PP 
Functions:
\*Lgetrusage\*O(2),
\*Ltimes\*O(3),
\*Lwait\*O(2)
.iX "clock function"
.EQ
delim off
.EN
