.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: clrtobot.3,v $ $Revision: 3.2.4.3 $ (DEC) $Date: 1993/09/15 20:09:46 $
.\"
.TH clrtobot 3
.SH NAME
\*Lclrtobot\*O, \*Lwclrtobot\*O \- Clears to the end of the screen
.SH SYNOPSIS
.PP
.sS
\*L#include <curses.h>\*O

\*Lint clrtobot(\|)\*O

\*Lint wclrtobot(\*Vwin\*L)
    WINDOW \(**\*Vwin\*L;\*O
.sE
.SH DESCRIPTION
.PP
.iX "clrtobot macro"
.iX "wclrtobot subroutine"
.PP
The \*Lclrtobot\*O routine
begins at the current cursor position in the default window
and changes the remainder of the
screen to blanks. The current cursor position is also
changed to a blank.
.PP
The \*Lwclrtobot\*O routine begins at the current cursor
position in the specified window
and changes the rest of the screen to blanks, including the
current cursor position.
.PP
The routine \*Lclrtobot\*O is a macro.
.SH RETURN VALUES
.PP
The \*Lclrtobot\*O and \*Lwclrtobot\*O
functions return OK on success and ERR on error.
.EQ
delim off
.EN
