.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: expacct.3,v $ $Revision: 3.2.2.2 $ (DEC) $Date: 1992/05/15 15:12:19 $
.\"
.\" 
.\" (c) Copyright 1991, OPEN SOFTWARE FOUNDATION, INC.
.\" ALL RIGHTS RESERVED
.\" 
.\"
.\"
.\" expacct3.man
.\" hah_17.07.90
.\" nm_31.07.90
.TH expacct 3
.SH NAME
\*Lexpacct\*O \- Expands accounting record
.SH SYNOPSIS 
.sS
.PP 
\*L#include\*O <\*Lsys/acct.h\*O>\*L
.PP 
\*Ldouble expacct (
.nL
    \*Lcomp_t \*Vrecord\*L );
.sE 
.SH PARAMETERS
.\"from TP "  
.VL 
.LI "\*Vrecord\*O"
Specifies the compressed data type value obtained from any source
containing such information.
.LE 
.SH DESCRIPTION
.iX "expacct function"
.iX "accounting record" "expanding"
The \*Lexpacct(\|)\*O function
converts
\*Lacct\*O
structure members
that have been packed
into a pseudo floating-point format
from the compressed data type \*Lcomp_t\*O
to data type \*Ldouble\*O.
.SH NOTES
The algorithm for compressing kernel accounting data is system dependent.
.SH "RELATED INFORMATION"
.PP 
Functions:
\*Lacct\*O(2)
.iX "expacct function"
.EQ
delim off
.EN
