.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: getwstr.3,v $ $Revision: 1.1.3.3 $ (DEC) $Date: 1993/11/16 00:11:46 $
.\"
.TH getwstr 3
.SH NAME
\*Lgetwstr\*O, \*Lgetnwstr\*O, \*Lmvgetwstr\*O, \*Lmvgetnwstr\*O, \*Lmvwgetwstr\*O, \*Lmvwgetnwstr\*O, \*Lwgetwstr\*O, \*Lwgetnwstr\*O  \- Read wchar_t character strings from curses terminal keyboard
.SH LIBRARY
.PP
The \*Lcurses\*O library (\*Llibcurses.so\*O, \*Llibcurses.a\*O)
.SH SYNOPSIS
.PP
.sS
\*L#include <curses.h>\*O
.PP
\*Lint getwstr( wchar_t \(**\*Vwstr \*L);
.PP
\*Lint getnwstr(
.br
        wchar_t \(**\*Vwstr\*L,
.br
        int \*Vn \*L);\*O
.PP
\*Lint mvgetwstr(
.br
        int \*Vy\*L,
.br
        int \*Vx\*L,
.br
        wchar_t \(**\*Vwstr \*L);\*O
.PP
\*Lint mvgetnwstr(
.br
        int \*Vy\*L,
.br
        int \*Vx\*L,
.br
        wchar_t \(**\*Vwstr\*L,
.br
        int \*Vn \*L);\*O
.PP
\*Lint mvwgetwstr(
.br
        WINDOW \(**\*Vwin\*L,
.br
        int \*Vy\*L,
.br
        int \*Vx\*L,
.br
        wchar_t \(**\*Vwstr \*L);\*O
.PP
\*Lint mvwgetnwstr(
.br
        WINDOW \(**\*Vwin\*L,
.br
        int \*Vy\*L,
.br
        int \*Vx\*L,
.br
        wchar_t \(**\*Vwstr\*L,
.br
        int \*Vn \*L);\*O
.PP
\*Lint wgetwstr(
.br
        WINDOW \(**\*Vwin\*L,
.br
        wchar_t \(**\*Vwstr \*L);\*O
.PP
\*Lint wgetnwstr(
.br
        WINDOW \(**\*Vwin\*L,
.br
        wchar_t \(**\*Vwstr\*L,
.br
        int \*Vn \*L);\*O
.sE
.SH PARAMETERS
.PP
.VL
.LI "\*Vwstr\*O"
Specifies a pointer to the buffer for the wide-character string.
.LI "\*Vwin\*O"
Specifies a \*Lcurses\*O window. If not specified, the
window is the default window \*Lstdscr\*O.
.LI "\*Vy\*O, \*Vx\*O"
Specifies the line (\*Vy\*O) and column (\*Vx\*O)
coordinates of the target position on the window.
If coordinates are not specified, the target
position is the current position of the logical cursor.
.LI "\*Vn\*O"
Specifies the maximum number of wide characters in the string.
.LE
.SH DESCRIPTION
.PP
.iX "getwstr macro"
.iX "getnwstr macro"
.iX "mvgetwstr macro"
.iX "mvgetnwstr macro"
.iX "mvwgetwstr macro"
.iX "mvwgetnwstr macro"
.iX "wgetwstr macro"
.iX "wgetnwstr subroutine"
The following information applies to all routines:
.ML
.LI
Each character read from the terminal is converted to a wchar_t
character and the resulting wchar_t character string is placed in the
buffer pointed to by the wchar_t character pointer \*Vwstr\*O.
.LI
The user's erase and kill characters are interpreted.
.LE
.PP
The \*Lgetwstr\*O routine reads wchar_t characters from the terminal
associated with the default window and stores them in a
buffer until a carriage return or newline is received from
\*Lstdscr\*O.
.PP
The \*Lgetnwstr\*O routine reads at most \*Vn\*O wchar_t characters
from the terminal associated with the default window
and stores them in a buffer until a carriage return or
newline is received from \*Lstdscr\*O.
.PP
The \*Lmvgetwstr\*O routine reads wchar_t characters
from the terminal associated with the default window.
The characters are read from the specified cursor position
(\*Vy\*O, \*Vx\*O) until a newline or carriage return is received.
.PP
The \*Lmvgetnwstr\*O routine reads at most \*Vn\*O wchar_t characters
from the terminal associated with the default window.
The characters are read from the specified cursor position
(\*Vy\*O, \*Vx\*O) until a newline or carriage return is received.
.PP
The \*Lmvwgetwstr\*O routine reads wchar_t characters
from the terminal associated with the window \*Vwin\*O.
The characters are read from the specified cursor position
(\*Vy\*O, \*Vx\*O) until a newline or carriage return is received.
.PP
The \*Lmvwgetnwstr\*O routine reads at most \*Vn\*O wchar_t characters
from the terminal associated with the window \*Vwin\*O.
The characters are read from the specified cursor position
(\*Vy\*O, \*Vx\*O) until a newline or carriage return is received.
.PP
The \*Lwgetwstr\*O routine reads wchar_t characters from the
terminal associated with the window \*Vwin\*O.
The characters are read from the current cursor position
until a newline or carriage return is received.
.PP
The \*Lwgetnwstr\*O routine reads at most \*Vn\*O wchar_t characters from the
terminal associated with the window \*Vwin\*O.
Characters are read from the current cursor position
until a newline or carriage return is received; \*Lwgetnwstr(\|)\*O
calls \*Lwgetwch(\|)\*O to read each character.
The \*Lwgetnwstr\*O routine does not check for buffer overflow,
so make sure that the buffer specified by \*Vwstr\*O is large
enough to hold the string.
If the buffer is not large enough, the result is unpredictable.
.PP
The \*Lgetwstr\*O, \*Lgetnwstr\*O, \*Lmvgetwstr\*O, \*Lmvgetnwstr\*O,
\*Lmvwgetwstr\*O, \*Lmvwgetnwstr\*O, and \*Lwgetwstr\*O
routines are macros.
.SH RETURN VALUES
.PP
The \*Lgetwstr\*O, \*Lgetnwstr\*O, \*Lmvgetwstr\*O, \*Lmvgetnwstr\*O,
\*Lmvwgetwstr\*O, \*Lmvwgetnwstr\*O, \*Lwgetwstr\*O, and \*Lwgetnwstr\*O
functions return \*LOK\*O on success and \*LERR\*O on error.
.SH RELATED INFORMATION
.PP
Functions: \*Lgetwch\*O(3).
.EQ
delim off
.EN
