.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: inswstr.3,v $ $Revision: 1.1.3.3 $ (DEC) $Date: 1993/11/16 00:16:54 $
.\"
.TH inswstr 3
.SH NAME
\*Linswstr\*O, \*Linsnwstr\*O, \*Lwinswstr\*O, \*Lwinnswstr\*O, \*Lmvinswstr\*O, \*Lmvinsnwstr\*O, \*Lmvwinswstr\*O, \*Lmvwinsnwstr\*O \- Insert a string of wchar_t characters before the character under the cursor in a curses window
.SH LIBRARY
.PP
The \*Lcurses\*O library (\*Llibcurses.so\*O, \*Llibcurses.a\*O)
.SH SYNOPSIS
.PP
.sS
\*L#include <curses.h>\*O
.PP
\*Lint inswstr( wchar_t \(**\*Vwstr \*L);\*O
.PP
\*Lint insnwstr(
.br
        wchar_t \(**\*Vwstr\*L,
.br
        int \*Vn \*L);\*O
.PP
\*Lint winswstr(
.br
        WINDOW \(**\*Vwin\*L,
.br
        wchar_t \(**\*Vwstr \*L);\*O
.PP
\*Lint winsnwstr(
.br
        WINDOW \(**\*Vwin\*L,
.br
        wchar_t \(**\*Vwstr\*L,
.br
        int \*Vn \*L);\*O
.PP
\*Lint mvinswstr(
.br
        int \*Vy\*L,
.br
        int \*Vx\*L,
.br
        wchar_t \(**\*Vwstr \*L);\*O
.PP
\*Lint mvinsnwstr(
.br
        int \*Vy\*L,
.br
        int \*Vx\*L,
.br
        wchar_t \(**\*Vwstr\*L,
.br
        int \*Vn \*L);\*O
.PP
\*Lint mvwinswstr(
.br
        WINDOW \(**\*Vwin\*L,
.br
        int \*Vy\*L,
.br
        int \*Vx\*L,
.br
        wchar_t \(**\*Vwstr \*L);\*O
.PP
\*Lint mvwinsnwstr(
.br
        WINDOW \(**\*Vwin\*L,
.br
        int \*Vy\*L,
.br
        int \*Vx\*L,
.br
        wchar_t \(**\*Vwstr\*L,
.br
        int \*Vn \*L);\*O
.sE
.SH PARAMETERS
.PP
.VL
.LI "\*Vwstr\*O"
Specifies the wide-character string to be inserted on the window.
.LI "\*Vwin\*O"
Specifies a \*Lcurses\*O window. If not specified, the
window is the default window \*Lstdscr\*O.
.LI "\*Vy\*O, \*Vx\*O"
Specifies the line (\*Vy\*O) and column (\*Vx\*O)
coordinates of the target position on the window.
If coordinates are not specified, the target
position is the current position of the logical cursor.
.LI "\*Vn\*O"
Specifies the maximum number of wide characters to be inserted
from the string.
.LE
.SH DESCRIPTION
.PP
.iX "inswstr macro"
.iX "insnwstr macro"
.iX "winswstr macro"
.iX "winsnwstr subroutine"
.iX "mvinswstr macro"
.iX "mvinsnwstr macro"
.iX "mvwinswstr macro"
.iX "mvwinsnwstr macro"
The \*Linswstr\*O routine inserts a string of wchar_t characters
on the default window at the current coordinates.
.PP
The \*Linsnwstr\*O routine inserts at most \*Vn\*O characters in the wchar_t
character string \*Vwstr\*O
on the default window at the current coordinates.
.PP
The \*Lwinswstr\*O routine inserts a string of wchar_t characters
on window \*Vwin\*O at the current coordinates.
.PP
The \*Lwinsnwstr\*O routine inserts at most \*Vn\*O characters in the wchar_t
character string \*Vwstr\*O
on window \*Vwin\*O at the current coordinates.
.PP
The \*Lmvinswstr\*O routine inserts a string of wchar_t characters
on the default window at the coordinates (\*Vy\*O, \*Vx\*O).
.PP
The \*Lmvinsnwstr\*O routine inserts at most \*Vn\*O characters in the wchar_t
character string \*Vwstr\*O
on the default window at the coordinates (\*Vy\*O, \*Vx\*O).
.PP
The \*Lmvwinswstr\*O routine inserts a string of wchar_t characters
on window \*Vwin\*O at the coordinates (\*Vy\*O, \*Vx\*O).
.PP
The \*Lmvwinsnwstr\*O routine inserts at most \*Vn\*O characters in the wchar_t
character string \*Vwstr\*O
on window \*Vwin\*O at the coordinates (\*Vy\*O, \*Vx\*O).
.PP
The preceding routines insert as many wchar_t characters as
will fit on the line.
For the four routines with \*Vn\*O as the last argument,
only the first \*Vn\*O wchar_t
characters are inserted. If \*Vn\*O is equal to \-1, the whole string is
inserted.
After insertion, all characters from the cursor position
to the right edge of the window are moved to the right.
The rightmost characters on the line may be lost, even if they are blanks.
The cursor position does not change (after moving to \*Vy\*O, \*Vx\*O,
if specified).
.PP
If any wchar_t character in \*Vwstr\*O is a tab, newline, or backspace,
the cursor is moved appropriately within the window.
A tab moves the cursor to the next tab position within the window.
A newline calls \*Lclrtoeol(\|)\*O
before moving the cursor to the beginning of the next line.
If newline mapping is off, newline moves the cursor to the
next line, but the x coordinate is unchanged.
If a character in \*Vwstr\*O is another control character, it is
drawn in the ^X notation.
Calling the \*Lwinwch\*O routine after adding a control character
returns the representation of the control character, not the control character.
.PP
The \*Linswstr\*O, \*Linsnwstr\*O, \*Lwinswstr\*O,
\*Lmvinswstr\*O, \*Lmvinsnwstr\*O, \*Lmvwinswstr\*O, and \*Lmvwinsnwstr\*O
routines are macros.
.SH RETURN VALUES
.PP
The \*Linswstr\*O, \*Linsnwstr\*O, \*Lwinswstr\*O, \*Lwinsnwstr\*O,
\*Lmvinswstr\*O, \*Lmvinsnwstr\*O, \*Lmvwinswstr\*O, and \*Lmvwinsnwstr\*O
functions return \*LOK\*O on success and \*LERR\*O on error.
.SH RELATED INFORMATION
.PP
Functions: \*Laddwstr\*O(3), \*Lcurses\*O(3), \*Lcurses_intro\*O(3).
.EQ
delim off
.EN
