.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: ldahread.3,v $ $Revision: 3.2.2.2 $ (DEC) $Date: 1992/05/27 10:55:26 $
.\"
.\" ---------------------------------------------------
.\" | Copyright (c) 1986, MIPS Computer Systems, Inc. |
.\" | All Rights Reserved.                            |
.\" ---------------------------------------------------
.\" $Header: /usr/doc/osf1doc/refpages/rcs/src/./BASE/DEC/man3/ldahread.3,v 3.2.2.2 1992/05/27 10:55:26 Joyce_Demers Exp $
.TH ldahread 3
.SH NAME
ldahread \- read the archive header of a member of an archive file
.SH SYNOPSIS
.PP
.nf
.ta \w'\s-1LDFILE\s+1\ \ \ 'u
.B #include <stdio.h>
.B #include <ar.h>
.ie '\*p'' \{
.B #include <filehdr.h>
.B #include <syms.h>
.B #include <ldfcn.h>
\}
.el \{
.B #include "INCDIR\/filehdr.h"
.B #include "INCDIR\/syms.h"
.B #include "INCDIR\/ldfcn.h"
\}
.PP
.BR "int ldahread (" "ldptr, arhead" )
.BR "\s-1LDFILE\s+1 \(**" ldptr ;
.BR "\s-1ARCHDR\s+1 \(**" arhead ;
.fi
.SH DESCRIPTION
.PP
If
.BI \s-1TYPE\s+1( ldptr )
is the archive file magic number,
.B ldahread
reads the archive header of the common object file
currently associated with
\*Vldptr\*O
into the area of memory beginning at
.IR arhead.
.PP
.B ldahread
.RB "returns " \s-1SUCCESS\s+1 " or " \s-1FAILURE\s+1 .
If
.BI \s-1TYPE\s+1( ldptr )
does not represent an archive file
or if it cannot read the archive header,
.B ldahread
fails.
.PP
The program must be loaded with the object file access routine library
.ie '\*p'' \{
.BR libmld.a .
\}
.el \{
.BR \s-1LIBDIR\s+1\/libmld.a .
\}
.PP
.ie !'\*p'' \{
\*Lintro\*O(4)
describes
.BR \s-1LIBDIR\s+1  and  \s-1INCDIR\s+1 .
\}
.SH RELATED INFORMATION
.PP
\*Lldclose\*O(3), \*Lldopen\*O(3), \*Lar\*O(4), \*Lldfcn\*O(4),
\*Lintro\*O(4).
.EQ
delim off
.EN
