.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: leaveok.3,v $ $Revision: 3.2.4.3 $ (DEC) $Date: 1993/10/15 23:24:16 $
.\"
.TH leaveok 3
.SH NAME
\*Lleaveok\*O \- Enables a non-tracking cursor
.SH SYNOPSIS
.PP
.sS
\*L#include <curses.h>\*O

\*Lint leaveok(\*Vwin\*L, \*Vbf\*L)
    WINDOW \(**\*Vwin\*L;
    bool \*Vbf\*L;\*O
.sE
.SH DESCRIPTION
.PP
.iX "leaveok subroutine"
This option allows the cursor to be left wherever the
update happens to leave it.  Normally, the cursor is left at the
current location (y, x) of the window being refreshed.
This routine is useful for applications where the cursor is not used,
since it reduces the need for cursor motions.
If possible, the cursor is made invisible when this option is enabled.
.PP
This option is initially disabled, and is not enabled until
the value of \*Lbf\*O is changed from \*LFALSE\*O to \*LTRUE\*O.
.SH RETURN VALUES
.PP
The \*Lleaveok\*O function returns OK on success and ERR on error.
.EQ
delim off
.EN
