.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: mvcur.3,v $ $Revision: 3.2.4.2 $ (DEC) $Date: 1993/09/15 18:48:26 $
.\"
.TH mvcur 3
.SH NAME
\*Lmvcur\*O \- Controls low-level cursor movement
.SH SYNOPSIS
.PP
.sS
\*L#include <curses.h>\*O

\*Lmvcur(\*Voldrow\*L, \*Voldcol\*L, \*Vnewrow\*L, \*Vnewcol\*L)
    int \*Voldrow\*L, \*Voldcol\*L, \*Vnewrow\*L, \*Vnewcol\*L;\*O
.sE
.SH DESCRIPTION
.PP
.iX "mvcur subroutine"
This function controls low-level cursor motion with optimization.
.EQ
delim off
.EN
