.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: newwin.3,v $ $Revision: 3.2.4.2 $ (DEC) $Date: 1993/09/15 20:39:58 $
.\"
.TH newwin 3
.SH NAME
\*Lnewwin\*O \- Creates a new window
.SH SYNOPSIS
.PP
.sS
\*L#include <curses.h>\*O

\*LWINDOW \(**newwin(\*Vnlines\*L, \*Vncols\*L, \*Vbegin_y\*L, \*Vbegin_x\*L)
    int \*Vnlines\*L, \*Vncols\*L, \*Vbegin_y\*L, \*Vbegin_x\*L;\*O
.sE
.SH DESCRIPTION
.PP
.iX "newwin subroutine"
The function \*Lnewwin\*O creates a new window with the
specified number of lines, \*Lnlines\*O, and columns, \*Lncols\*O.
The upper left corner of the window is at line \*Lbegin_y\*O,
column \*Lbegin_x\*O.
.PP
If either \*Lnlines\*O or \*Lncols\*O is zero, it will be
defaulted to LINES \- \*Lbegin_y\*O and COLS\ - \*Lbegin_x\*O .
A new full-screen window is created by calling
\*Lnewwin (0,0,0,0)\*O.
.SH RETURN VALUES
.PP
On success, the \*Lnewwin\*O function returns a pointer
to the new WINDOW structure created.  On failure,
the function returns a null pointer.
.EQ
delim off
.EN
