.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: nl.3,v $ $Revision: 3.2.4.2 $ (DEC) $Date: 1993/09/15 20:40:08 $
.\"
.TH nl 3
.SH NAME
\*Lnl\*O, \*Lnonl\*O \- Enables or disables newline control
.SH SYNOPSIS
.PP
.sS
\*L#include <curses.h>\*O

\*Lint nl(\|)\*O

\*Lint nonl(\|)\*O
.sE
.SH DESCRIPTION
.PP
.iX "nl macro"
.iX "nonl subroutine"
The \*Lnl\*O routine enables the newline control translations.
When newline control is enabled, a newline is translated into
a carriage return
and a linefeed on output, and a return is translated into
a newline on input.  Initially, these translations do occur.
.PP
The \*Lnonl\*O routine disables these translations, allowing
the \*Lcurses\*O program to use the linefeed capability
of the terminal, resulting in faster cursor motion.
The \*Lnl\*O routine is a macro.
.SH RETURN VALUES
.PP
The \*Lnl\*O and \*Lnonl\*O functions return OK on success and
ERR on error.
.EQ
delim off
.EN
