.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: nodelay.3,v $ $Revision: 3.2.4.2 $ (DEC) $Date: 1993/09/15 20:40:18 $
.\"
.TH nodelay 3
.SH NAME
\*Lnodelay\*O \- Disables a block during a read
.SH SYNOPSIS
.PP
.sS
\*L#include <curses.h>\*O

\*Lint nodelay(\*Vwin\*L, \*Vbf\*L)
    WINDOW \(**\*Vwin\*L;
    bool \*Vbf\*L;\*O
.sE
.SH DESCRIPTION
.PP
.iX "nodelay subroutine"
.iX "getch subroutine" "nodelay subroutine"
This option causes the \*Lgetch\*O routine to be a non-blocking call.
If no input is ready and \*Lnodelay\*O is enabled, \*Lgetch\*O
will return the integer \*LERR\*O.  If \*Lnodelay\*O is disabled,
\*Lgetch\*O will wait until input is ready.
.SH RETURN VALUES
.PP
The \*Lnodelay\*O function returns OK on success and ERR on error.
.SH RELATED INFORMATION
.PP
\*Lgetch\*O(3)
.EQ
delim off
.EN
