.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: ntohl.3,v $ $Revision: 3.2.5.2 $ (DEC) $Date: 1993/09/27 14:45:58 $
.\"
.\" 
.\" (c) Copyright 1991, OPEN SOFTWARE FOUNDATION, INC.
.\" ALL RIGHTS RESERVED
.\" 
.\"build rmifdef
.\"
.\"
.\"build rmifdef tbl eqn
.TH ntohl 3
.SH NAME
.PP
\*Lntohl\*O \- Converts an unsigned 32-bit integer from Internet network-byte order to host-byte order
.SH LIBRARY
.PP
Standard C Library (\*Llibc.a\*O)
.SH SYNOPSIS
.PP
.sS
\*Lunsigned int ntohl\*O (\*L
.nL
	\*Lunsigned int \*Vnetint\*L) ;
.sE
.SH PARAMETERS
.PP
.\"from TP "  
.VL
.LI "\*Vnetint\*O"
Specifies a 32-bit integer in network-byte order.
.LE
.SH DESCRIPTION
.PP
.iX "ntohl function"
.iX "host-byte order" "converting long integer"
.iX "network-byte order" "converting long integer"
.iX "long integer" "converting to host-byte order"
The \*Lntohl(\|)\*O (network-to-host long) function
converts an unsigned 32-bit integer from Internet
network-byte order to host-byte order.
.PP
\*OThe Internet network requires address and port reference data in
network-byte order (most significant byte leftmost, least significant
byte rightmost).  You can use the \*Lntohl(\|)\*O function to convert Internet
network address and port data to host byte-ordered integers.
.\" Commented out per Mary Walker -- QAR 13674
.\".PP
.\"The \*Lntohl(\|)\*O function is defined as a \*Vlittle-endian\*O function in
.\"the \*Lnetinet/in.h\*O header file for machine environments where
.\"network-byte order and host-byte order are not identical.
.SH RETURN VALUES
.PP
\*OThe \*Lntohl(\|)\*O function
returns a 32-bit integer in host-byte order.
.SH RELATED INFORMATION
.PP
Functions:
\*Lntohs\*O(3),
\*Lhtonl\*O(3),
\*Lhtons\*O(3)
.iX "ntohl function"
.EQ
delim off
.EN
