.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: pfopen.3,v $ $Revision: 1.1.4.2 $ (DEC) $Date: 1993/07/21 16:09:55 $
.\"
.TH pfopen 3
.SH NAME
.PP
\*Lpfopen\*O \- Open a packet filter file
.SH SYNOPSIS
.PP
.sS
pfopen(ifname, flags)
.sp
char *ifname;
int flags;
.sE
.SH DESCRIPTION
.iX "packetfilter" "pfopen subroutine"
.iX "pfopen subroutine"
The packet filter (see \*Lpacketfilter\*O(7))
provides raw access to Ethernets and similar network data link layers.
The routine \*Lpfopen\*O
is used to open a packet filter file descriptor.  The routine hides various
details about the way packet filter files are opened and named.
.PP
The \*Vifname\*O
argument is a pointer to a null-terminated string containing the name
of the interface for which the application is opening the packet filter.
This name may be the name of an actual interface on the system
(for example, \*Lln0\*O) or it may be a pseudo-interface name of the
form \*Lpf\*Vn\*O, used to specify the \*Vnth\*O
interface attached to the system.  For example, \*Lpf0\*O specifies the
first such interface.  If \*Vifname\*O
is NULL, the default interface (\*Lpf0\*O) is used.
.PP
The \*Vflags\*O
argument has the same meaning as the corresponding argument to the
\*Lopen\*O(2) system call.
.PP
The file descriptor returned by \*Lpfopen\*O
is otherwise identical to one returned by \*Lopen\*O(2).
.SH ERRORS
.PP
The \*Lpfopen\*O
routine returns a negative integer if the file could not be opened.
This may be because of resource limitations, or because the specified
interface does not exist.
.SH RELATED INFORMATION
.PP
Commands: \*Lopen\*O(2)
.PP
Files: \*Lbpf\*O(7), \*Lpacketfilter\*O(7)
.EQ
delim off
.EN
