.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: pthread_intro.3,v $ $Revision: 3.3.2.4 $ (DEC) $Date: 1992/07/22 12:24:39 $
.\" 
...\" Copyright 1991, Open Software Foundation, Inc. ALL RIGHTS RESERVED.
...\" ********************************************************************
...\"                                                                    *
...\" COPYRIGHT (c) 1990 BY DIGITAL EQUIPMENT CORPORATION,               *
...\" Maynard, Mass.                                                     *
...\"                                                                    *
...\" This document is furnished under a license and may be used and     *
...\" copied only in accordance with the terms of such license and with  *
...\" the inclusion of the above copyright notice. This document or any  *
...\" other copies thereof may not be provided or otherwise made         *
...\" available to any other person. No title to or ownership of the     *
...\" document is hereby transferred.                                    *
...\"                                                                    *
...\" The information in this document is subject to change without      *
...\" notice and should not be construed as a commitment by DIGITAL      *
...\" Equipment Corporation.                                             *
...\"                                                                    *
...\" ********************************************************************
.wH "<routine_section>"
.nr H1 1
.TH pthread_intro 3
.SH NAME
\*Lpthread_intro\*O \- Introduction to DCE Threads
.SH DESCRIPTION
.PP
DCE Threads are a set of routines that you can call to create a
multithreaded program. Multithreading is used to improve the performance of
a program.
.PP
The routines in this section are listed alphabetically. However, this
introduction groups the routines as follows:
.ML
.LI
Threads Routines
.LI
Attributes Object Routines
.LI
Mutex Routines
.LI
Condition Variable Routines
.LI
Per-Thread Context Routines
.LI
Thread Cancelation Routines
.LI
Thread Priority and Scheduling Routines
.LI
Cleanup Routines
.LE
.sp 0.25i
.SS "Threads Routines"
.VL 14m
.LI "pthread_create"
Creates a Thread
.LI "pthread_delay_np"
Causes a Thread to Wait for a Period of Time
.LI "pthread_detach"
Marks a Thread for Deletion
.LI "pthread_exit"
Terminates the Calling Thread
.LI "pthread_join"
Causes the Calling Thread to Wait for the
Termination of a Specified Thread
.LI "pthread_once"
Calls an Initialization Routine to be Executed Only
Once
.LI "pthread_self"
Obtains the Identifier of the Current Thread
.LI "pthread_yield"
Notifies the Scheduler that the Current Thread
Will Release its Processor to Other Threads of the Same or Higher Priority
.LE
.sp 0.25i
.SS "Attributes Object Routines"
.VL 14m
.LI "pthread_attr_create"
Creates a Thread Attributes Object
.LI "pthread_attr_delete"
Deletes a Thread Attributes Object
.LI "pthread_attr_getinheritsched"
Obtains the Inherit Scheduling
Attribute
.LI "pthread_attr_getprio"
Obtains the Scheduling Priority Attribute
.LI "pthread_attr_getsched"
Obtains the Scheduling Policy Attribute
.LI "pthread_attr_getstacksize"
Obtains the Stacksize Attribute
.LI "pthread_attr_setinheritsched"
Changes the Inherit Scheduling
Attribute
.LI "pthread_attr_setprio"
Changes the Scheduling Priority Attribute
.LI "pthread_attr_setsched"
Changes the Scheduling Policy Attribute
.LI "pthread_attr_setstacksize"
Changes the Stacksize Attribute
.LI "pthread_condattr_create"
Creates a Condition Variable Attributes
Object
.LI "pthread_condattr_delete"
Deletes a Condition Variable Attributes
Object
.LI "pthread_mutexattr_create"
Creates a Mutex Attributes Object
.LI "pthread_mutexattr_delete"
Deletes a Mutex Attributes Object
.LI "pthread_mutexattr_getkind_np"
Obtains the Mutex Type Attribute
.LI "pthread_mutexattr_setkind_np"
Specifies the Mutex Type Attribute
.LE
.sp 0.25i
.SS "Mutex Routines"
.VL 14m
.LI "pthread_lock_global_np"
Locks a Global Mutex
.LI "pthread_mutex_destroy"
Deletes a Mutex
.LI "pthread_mutex_init"
Creates a Mutex
.LI "pthread_mutex_lock"
Locks a Mutex and Waits if Mutex is Already
Locked
.LI "pthread_mutex_trylock"
Locks a Mutex and Returns if Mutex is
Already Locked
.LI "pthread_mutex_unlock"
Unlocks a Mutex
.LI "pthread_unlock_global_np"
Unlocks a Global Mutex
.LE
.sp 0.25i
.SS "Condition Variable Routines"
.VL 14m
.LI "pthread_cond_broadcast"
Wakes All Threads Waiting on a Condition
Variable
.LI "pthread_cond_destroy"
Deletes a Condition Variable
.LI "pthread_cond_init"
Creates a Condition Variable
.LI "pthread_cond_signal"
Wakes One Thread Waiting on a Condition
Variable
.LI "pthread_cond_timedwait"
Causes a Thread to Wait for a Condition
Variable to be Signaled or Broadcast for a Specified Period of Time
.LI "pthread_cond_wait"
Causes a Thread to Wait for a Condition
Variable to be Signaled or Broadcast
.LI "pthread_get_expiration_np"
Obtains a Value Representing a Desired
Expiration Time
.LE
.sp 0.25i
.SS "Per-thread Context Routines"
.VL 14m
.LI "pthread_getspecific"
Obtains the Per-thread Context Associated
with the Specified Key
.LI "pthread_keycreate"
Generates a Unique Per-thread Context Key
Value
.LI "pthread_setspecific"
Sets the Per-thread Context Associated with
the Specified Key
.LE
.sp 0.25i
.SS "Thread Cancelation Routines"
.VL 14m
.LI "pthread_cancel"
Allows a Thread to Request Termination
.LI "pthread_setasynccancel"
Enables or Disables the Current Thread's
Asynchronous Cancelability
.LI "pthread_setcancel"
Enables or Disables the Current Thread's
General Cancelability
.LI "pthread_testcancel"
Requests Delivery of a Pending Cancel
.LE
.sp 0.25i
.SS "Priority and Scheduling Routines"
.VL 14m
.LI "pthread_getprio"
Obtains the Current Priority of a Thread
.LI "pthread_getscheduler"
Obtains the Current Scheduling Policy of a
Thread
.LI "pthread_setprio"
Changes the Current Priority of a Thread
.LI "pthread_setscheduler"
Changes the Current Scheduling Policy and
Priority of a Thread
.LE
.sp 0.25i
.SS "Cleanup Routines"
.VL 14m
.LI "pthread_cleanup_pop"
Removes a Cleanup Handler from the Stack
.LI "pthread_cleanup_push"
Establishes a Cleanup Handler
.LE
.wH "<endroutine_section>"
.EQ
delim off
.EN
