.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: pthread_get_expiration_np.3,v $ $Revision: 3.3.2.2 $ (DEC) $Date: 1992/05/27 11:08:52 $
.\"
...\" Copyright 1991, Open Software Foundation, Inc. ALL RIGHTS RESERVED.
.wH ********************************************************************
.wH                                                                    *
.wH COPYRIGHT (c) 1990 BY DIGITAL EQUIPMENT CORPORATION,               *
.wH Maynard, Mass.                                                     *
.wH                                                                    *
.wH This document is furnished under a license and may be used and     *
.wH copied only in accordance with the terms of such license and with  *
.wH the inclusion of the above copyright notice. This document or any  *
.wH other copies thereof may not be provided or otherwise made         *
.wH available to any other person. No title to or ownership of the     *
.wH document is hereby transferred.                                    *
.wH                                                                    *
.wH The information in this document is subject to change without      *
.wH notice and should not be construed as a commitment by DIGITAL      *
.wH Equipment Corporation.                                             *
.wH                                                                    *
.wH ********************************************************************
.wH "<routine_section>"
.TH pthread_get_expiration_np 3
.SH NAME
\*Lpthread_get_expiration_np\*O \- Obtains a value representing a desired expiration time.
.SH SYNOPSIS
.PP
.sS
\*L#include <pthread.h>
.fS "int pthread_get_expiration_np"
.dS "struct timespec"
\*V*delta\*L
.dE
.dS "struct timespec"
\*V*abstime\*O
.dE
.fE
.sE
.wH "<endformat>"
.SH PARAMETERS
.PP
.VL 5m
.LI "\*Vdelta\*O"
Number of seconds and nanoseconds to add to the current system time. The
result is the time that a timed wait expires.
.LI "\*Vabstime\*O"
Value representing the expiration time.
.LE
.wH "<endparameters>"
.SH DESCRIPTION
.iX "Time" "obtaining expiration"
.iX "Time" "adding interval to current time"
.iX "Expiration time" "obtaining"
.PP
This routine adds a specified interval to the current absolute system time
and returns a new absolute time. This new absolute time is used as the
expiration time in a call to \*Lpthread_cond_timedwait\*O.
.PP
.wH "<mark>"
The \*Lstruct timespec\*O structure contains two fields, as follows:
.ML
.LI
\*Ltv.sec\*O is an integer number of seconds, and
.LI
\*Ltv.nsec\*O is an integer number of nanoseconds.
.LE
.wH "<endmark>"
.SH RETURN VALUES
.PP
If an error condition occurs, this routine returns \-1 and sets
\*Eerrno\*O to the corresponding error value. Possible return values
are as follows:
.sp
.TS
center, tab(@);
l l l.
\*LReturn@Error@Description\*O
_
\00@@Successful completion.
\&\-1@[\*LEINVAL\*O]@The value specified by \*Vdelta\*O is invalid.
.TE
.wH "<endnas_return>"
.cS
.SH EXAMPLES
.PP
.oS
extern int pthread_get_expiration_np (struct timespec *delta,
 struct timespec *abstime);
.oE
.cE
.wH "<endnas_examples>"
.SH RELATED INFORMATION
.PP
\*Lpthread_cond_timedwait\*O(3)
.EQ
delim off
.EN
