.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: raw.3,v $ $Revision: 3.2.4.2 $ (DEC) $Date: 1993/09/15 21:42:13 $
.\"
.TH raw 3
.SH NAME
\*Lraw\*O, \*Lnoraw\*O \- Enables or disables raw mode
.SH SYNOPSIS
.PP
.sS
\*L#include <curses.h>\*O

\*Lint raw(\|)\*O

\*Lint noraw(\|)\*O
.sE
.SH DESCRIPTION
.PP
.iX "noraw subroutine"
.iX "raw subroutine"
.PP
The \*Lraw\*O routine sets the terminal into RAW mode.
RAW mode is similar to CBREAK mode, in that characters are immediately
passed through to the user program as they are typed.
In RAW mode, the interrupt, quit, suspend, and flow
control characters are passed through uninterpreted
and do not generate a signal.
.PP
The behavior of the BREAK key depends on the settings of bits that
are not controlled by \*Lcurses\*O.
.PP
The \*Lnoraw\*O routine disables RAW mode.
.SH RETURN VALUES
.PP
The \*Lraw\*O and \*Lnoraw\*O functions return OK on success
and ERR on error.
.EQ
delim off
.EN
