.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: resetty.3,v $ $Revision: 3.2.4.2 $ (DEC) $Date: 1993/09/15 21:42:42 $
.\"
.TH resetty 3
.SH NAME
\*Lresetty\*O, \*Lsavetty\*O \- Restores or saves terminal modes
.SH SYNOPSIS
.PP
.sS
\*L#include <curses.h>\*O

\*Lint resetty(\|)\*O

\*Lint savetty(\|)\*O
.sE
.SH DESCRIPTION
.PP
.iX "resetty subroutine"
.iX "savetty subroutine"
The \*Lsavetty\*O routine saves the current state of the
terminal modes in a buffer.  The routine \*Lresetty\*O
restores the state of the terminal
modes to what it was at the last call to \*Lsavetty\*O.
.SH RETURN VALUES
.PP
The \*Lresetty\*O and \*Lsavetty\*O
functions return OK on success and ERR on error.
.EQ
delim off
.EN
