.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: restartterm.3,v $ $Revision: 3.2.4.3 $ (DEC) $Date: 1993/10/15 23:24:33 $
.\"
.TH restartterm 3
.SH NAME
\*Lrestartterm\*O \- Restarts the terminal for a curses application
.SH SYNOPSIS
.PP
.sS
\*L#include <curses.h>\*O

\*Lrestartterm(\*Vterm\*L, \*Vfilenum\*L, \*Verrret\*L)
    char *\*Vterm\*L;
    int \*Vfilenum\*L;
    int *\*Verrret\*L;\*O
.sE
.SH DESCRIPTION
.PP
.iX "restartterm subroutine"
This function sets up the current terminal \*Lterm\*O
after a save/restore of a \*Lcurses\*O application program.
The \*Lrestartterm\*O function
assumes that the windows and modes are the same for the restarted
application as when memory was saved.
It assumes that the terminal type
and dependent settings, such as baudrate, may have changed.
The routine \*Lsetupterm\*O is called to extract the
terminal information from the \*Lterminfo\*O database
and set up the terminal.
.SH RELATED INFORMATION
.PP
\*Lsetupterm\*L(3), \*Lterminfo\*L(4)
.EQ
delim off
.EN
