.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: stty.3,v $ $Revision: 1.1.2.3 $ (DEC) $Date: 1992/08/07 07:55:22 $
.\"
.\" This manpage source uses rsml coding.
.TH stty 3
.SH NAME 
.PP
\*Lstty\*O, \*Lgtty\*O \- Set and get terminal state 
.SH SYNOPSIS
.PP
.sS
\*L#include <sgtty.h>\*O
.sp
\*Lstty (
.nL
    \*Lint \*Vfd\*L,
.nL
    \*Lstruct sgttyb \*V*buf \*L);\*O
.sp
\*Lgtty (
.nL
    \*Lint \*Vfd\*L,
.nL
    \*Lstruct sgttyb \*V*buf \*L);\*O
.sE
.SH DESCRIPTION
.PP 
.iX "stty subroutine"
.iX "gtty subroutine"
.iX "terminals" "setting state of"
.iX "terminals" "getting state of"
The \*Lstty\*O subroutine sets the state of the terminal associated
with \*Vfd\*O.  The \*Lgtty\*O subroutine retrieves the state of the
terminal associated with \*Vfd\*O. To set the state of a terminal,
the \*Lstty\*O call must have write permission.
.PP
Calls to these subroutines, supported only to ensure BSD binary compatibility, 
have been superseded by 
the \*Lioctl\*O system call.
The \*Lstty\*O call is implemented as
\*Lioctl(\|\*Vfd\*L, TIOCSETP, \*Vbuf\*L\|)\*O,
while the \*Lgtty\*O call is implemented as
\*Lioctl(\|\*Vfd\*L, TIOCGETP, \*Vbuf\*L\|)\*O.
See \*Lioctl\*O(2) and \*Ltty\*O(7) for more information. 
.SH RETURN VALUES 
.PP
If the call is successful, zero is returned; otherwise, \-1 is
returned and the global variable \*Lerrno\*O
indicates the reason for the failure.
.SH RELATED INFORMATION
.PP 
Functions:
\*Lioctl\*O(2)
.PP
Files:
\*Ltty\*O(7)
.EQ
delim off
.EN
