.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: swapsex.3,v $ $Revision: 3.2.2.2 $ (DEC) $Date: 1992/05/27 13:06:26 $
.\"
.\"
.\" This is a new ref page created from the gethostsex.3 manpage
.\" supplied by MIPS and included with the BL5 build for TIN.
.\" The original gethostsex.3 ref page has been split into a
.\" new, shortened gethostsex.3 page and this swapsex.3 page.
.\" This was done on 6/20/91. JM
.\"
.\" Copyright (c) 1991, Digital Equipment Corporation
.\" ALL RIGHTS RESERVED
.\"
.\" ---------------------------------------------------
.\" | Copyright (c) 1986, MIPS Computer Systems, Inc. |
.\" | All Rights Reserved.                            |
.\" ---------------------------------------------------
.\" $Header: /usr/doc/osf1doc/refpages/rcs/src/./BASE/DEC/man3/swapsex.3,v 3.2.2.2 1992/05/27 13:06:26 Joyce_Demers Exp $
.ds ]W MIPS Computer Systems
.TH swapsex 3
.SH NAME
swapsex \- swap the sex of the specified structure
.SH SYNOPSIS
.PP
.B "#include <sex.h>
.br
.B "#include <filehdr.h>
.br
.B "#include <aouthdr.h>
.br
.B "#include <scnhdr.h>
.br
.B "#include <sym.h>
.br
.B "#include <symconst.h>
.br
.B "#include <cmplrs/stsupport.h>
.br
.B "#include <reloc.h>
.br
.B "#include <ar.h>
.PP
.B "long swap_word(word)
.br
.B "long word;
.PP
.B "short swap_half(half)
.br
.B "short half;
.PP
.B "void swap_filehdr(pfilehdr, destsex)
.br
.B "FILHDR *pfilehdr;
.br
.B "long destsex;
.PP
.B "void swap_aouthdr(paouthdr, destsex)
.br
.B "AOUTHDR *paouthdr;
.br
.B "long destsex;
.PP
.B "void swap_scnhdr(pscnhdr, destsex)
.br
.B "SCNHDR *pscnhdr;
.br
.B "long destsex;
.PP
.B "void swap_hdr(phdr, destsex)
.br
.B "pHDRR phdr;
.br
.B "long destsex;
.PP
.B "void swap_fd(pfd, count, destsex)
.br
.B "pFDR pfd;
.br
.B "long count;
.br
.B "long destsex;
.PP
.B "void swap_fi(pfi, count, destsex)
.br
.B "pFIT pfi;
.br
.B "long count;
.br
.B "long destsex;
.PP
.B "void swap_sym(psym, count, destsex)
.br
.B "pSYMR psym;
.br
.B "long count;
.br
.B "long destsex;
.PP
.B "void swap_ext(pext, count, destsex)
.br
.B "pEXTR pext;
.br
.B "long count;
.br
.B "long destsex;
.PP
.B "void swap_pd(ppd, count, destsex)
.br
.B "pPDR ppd;
.br
.B "long count;
.br
.B "long destsex;
.PP
.B "void swap_dn(pdn, count, destsex)
.br
.B "pRNDXR pdn;
.br
.B "long count;
.br
.B "long destsex;
.PP
.B "void swap_opt(popt, count, destsex)
.br
.B "pOPTR popt;
.br
.B "long count;
.br
.B "long destsex;
.PP
.B "void swap_aux(paux, type, destsex)
.br
.B "pAUXU paux;
.br
.B "long type;
.br
.B "long destsex;
.PP
.B "void swap_reloc(preloc, count, destsex)
.br
.B "struct reloc *preloc;
.br
.B "long count;
.br
.B "long destsex;
.PP
.B "void swap_ranlib(pranlib, count, destsex)
.br
.B "struct ranlib *pranlib;
.br
.B "long count;
.br
.B "long destsex;
.SH DESCRIPTION
.PP
To use these routines, the library
\*Vlibmld.a\*O
must be loaded.
.PP
All
\*Vswap_*\*O
routines that swap headers take a pointer to a header structure to change the
byte's sex. The
\*Vdestsex\*O
argument lets the swap routines decide whether to swap bitfields before
or after swapping the words they occur in. If
\*Vdestsex\*O
equals the hostsex of the machine you are running on, the flip happens
before the swap; otherwise, the flip happens after the swap.
Although
not all routines swap structures containing bitfields, the destsex is
required in the anticipation of future need.
.PP
The
\*Vswap_aux\*O
routine takes a pointer to an aux entry and a
.IR type ,
which is a ST_AUX_* constant in
\*Vcmplrs/stsupport.h.  \*O
The constant specifies
the type of the aux entry to change the sex of.
All other
\*Vswap_*\*O
routines are passed a pointer to an array of structures and a
\*Vcount\*O
of structures to change the byte sex of.  The routines
\*Vswap_word\*O
and
\*Vswap_half\*O
are macros declared in
\*Vsex.h.\*O
Only the include files necessary to describe the structures being swapped
need be included.
.EQ
delim off
.EN
