.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: tparm.3,v $ $Revision: 3.2.4.2 $ (DEC) $Date: 1993/09/15 23:23:20 $
.\"
.TH tparm 3
.SH NAME
\*Ltparm\*O \- Instantiates a string
.SH SYNOPSIS
.PP
.sS
\*L#include <curses.h>\*O

\*Lchar *tparm(\*Vstr\*L, \*Vp1\*L, \*Vp2\*L, ... )\*O
.sE
.SH DESCRIPTION
.PP
.iX "tparm subroutine"
This function instantiates the string \*Lstr\*O
with the parameters p1, p2, ... .
A pointer is returned which points to the result of \*Lstr\*O
with the parameters applied.
.EQ
delim off
.EN
