.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: traceon.3,v $ $Revision: 3.2.4.2 $ (DEC) $Date: 1993/09/15 23:23:39 $
.\"
.TH traceon 3
.SH NAME
\*Ltraceon\*O, \*Ltraceoff\*O \- Enables or disables debug trace output
.SH SYNOPSIS
.PP
.sS
\*L#include <curses.h>\*O

\*Ltraceon()\O

\*Ltraceoff()\*O
.sE
.SH DESCRIPTION
.PP
.iX "traceon subroutine"
These functions turn the debugging trace output on and off
when you use the debug version of the \*Lcurses\*O library
/usr/lib/libdcurses.a.
.EQ
delim off
.EN
