.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: vidattr.3,v $ $Revision: 3.2.4.3 $ (DEC) $Date: 1993/10/15 23:24:56 $
.\"
.TH vidattr 3
.SH NAME
\*Lvidattr\*O, \*Lvidputs\*O \- Outputs a string that sets the terminal display
.SH SYNOPSIS
.PP
.sS
\*L#include <curses.h>\*O

\*Lvidattr(\*Vattrs\*L)

\*Lvidputs(\*Vattrs\*L, \*Vputc\*L)\*O
.sE
.SH DESCRIPTION
.PP
.iX "vidattr subroutine"
.iX "vidputs subroutine"
The \*Lvidattr\*O routine outputs a string that sets the
video attributes \*Lattrs\*O for the terminal.
The characters in the string are passed one at a time
to the routine \*Lputchar\*O.
.PP
The \*Lvidputs\*O routine is similar, except that the string
characters are passed to the routine \*Lputc\*O.
.SH RELATED INFORMATION
.PP
\*Lputc\*O(3)
.EQ
delim off
.EN
