/*
 * *****************************************************************
 * *                                                               *
 * *    Copyright (c) Digital Equipment Corporation, 1991, 1994    *
 * *                                                               *
 * *   All Rights Reserved.  Unpublished rights  reserved  under   *
 * *   the copyright laws of the United States.                    *
 * *                                                               *
 * *   The software contained on this media  is  proprietary  to   *
 * *   and  embodies  the  confidential  technology  of  Digital   *
 * *   Equipment Corporation.  Possession, use,  duplication  or   *
 * *   dissemination of the software and media is authorized only  *
 * *   pursuant to a valid written license from Digital Equipment  *
 * *   Corporation.                                                *
 * *                                                               *
 * *   RESTRICTED RIGHTS LEGEND   Use, duplication, or disclosure  *
 * *   by the U.S. Government is subject to restrictions  as  set  *
 * *   forth in Subparagraph (c)(1)(ii)  of  DFARS  252.227-7013,  *
 * *   or  in  FAR 52.227-19, as applicable.                       *
 * *                                                               *
 * *****************************************************************
 */
/*
 * HISTORY
 */
/****************************************************************************
**                                                                          *
**                       COPYRIGHT (c) 1990, 1991 BY                        *
**              DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.               *
**			     ALL RIGHTS RESERVED                            *
**                                                                          *
**  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED  *
**  ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE  *
**  INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER  *
**  COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY  *
**  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY  *
**  TRANSFERRED.                                                            *
**                                                                          *
**  THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE  *
**  AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT  *
**  CORPORATION.                                                            *
**                                                                          *
**  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR  RELIABILITY  OF  ITS  *
**  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.                 *
**                                                                          *
****************************************************************************/

#include <stdio.h>
#include "sfb.h"

CommandWord RightBitMask(i)
    int i;
{
    CommandWord mask;

    /* Start mask as 0000...1111, with SFBPIXELALIGNMENT 1's. */
    mask = SFBCOPYALL1 >> (SFBCOPYBITS - SFBPIXELALIGNMENT);
    /* Shift to get desired pattern in lowest SFBPIXELALIGNMENT bits. */
    mask >>= ((-(i+1)) & SFBPIXELALIGNMASK);
    /* Or in 1's in high bits. */
    mask |= (SFBCOPYALL1 << SFBPIXELALIGNMENT);
    /* Shift left SFBPIXELALIGNMENT bits if needed. */
    mask <<= ((SFBPIXELALIGNMASK-i) & ~SFBPIXELALIGNMASK);
    /* Junk any high bits that got turned on. */
    mask &= SFBCOPYALL1;
    return mask;
} /* RightBitMask */

#define SHIFTMASK   (~SFBPIXELALIGNMASK & SFBCOPYBITSMASK)

CommandWord LeftBitMask(i)
    int i;
{
    CommandWord mask;
    int shift;

    /* Start mask as 0000...1111, where there are SFBPIXELALIGNMENT 1's. */
    mask = SFBCOPYALL1 >> (SFBCOPYBITS - SFBPIXELALIGNMENT);
    /* Shift to get desired pattern in lowest SFBPIXELALIGNMENT bits. */
    shift = -i & SFBPIXELALIGNMASK;
    mask = (mask >> shift) << shift;
    /* Shift left as needed */
    mask <<= (i-1) & SHIFTMASK;
    /* Or in 1's in low bits. */
    mask |= (SFBCOPYALL1 >> (-i & SHIFTMASK)) >> SFBPIXELALIGNMENT;
    /* Junk any high bits */
    mask &= SFBCOPYALL1;
    return mask;
} /* LeftBitMask */


main() {
    int i;

    printf("/* DO NOT MODIFY.  AUTOMATICALLY GENERATED BY sfbgensfb.c */\n");
    printf("\n");
    printf("#include \"sfb.h\"\n");
    printf("\n");

    printf("/* By assigning a global variable, we can actually get these */\n");
    printf("/* values into registers.  Compiler otherwise keeps loading */\n");
    printf("/* them again and again. */\n");
    printf("CommandWord sfbBusAll1 = SFBBUSALL1;\n");
    printf("CommandWord sfbStippleAll1 = SFBSTIPPLEALL1;\n");
    printf("CommandWord sfbCopyAll1 = SFBCOPYALL1;\n");
    printf("\n");

    printf("CommandWord sfbBackRightMask[2*SFBPIXELALIGNMENT] = {\n");
    for (i = -SFBPIXELALIGNMENT; i < SFBPIXELALIGNMENT; i++) {
	printf("    /* %3d */  0x%08lx,\n", i, RightBitMask(i));
    }
    printf("}; /* sfbBackRightMask */\n");
    printf("\n");
    printf("CommandWord sfbBackLeftMask[SFBCOPYBITS] = {\n");
    for (i = 0; i < SFBCOPYBITS; i++) {
	printf("    /* %3d */  0x%08lx,\n", i, LeftBitMask(i));
    }
    printf("}; /* sfbBackLeftMask */\n");
    printf("\n");
}

