.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: console.7,v $ $Revision: 3.2.4.2 $ (DEC) $Date: 1994/01/19 23:34:26 $
.\"
.TH console 7
.SH NAME
.PP
\*Lconsole\*O \- Console interface
.SH DESCRIPTION
.PP
.iX "console interface"
Return to the monitor by halting the machine from the operating
system or pressing the HALT button on the rear panel.  Enter
\*Lhelp\*O at the prompt to receive a description of valid console
commands.  For example:
.PP
.iS
>>help
.iE
.PP
The \*L/dev/console\*O
device is valid for all operating system accesses to the character
tty device.
.SH FILES
.PP
\*L/dev/console\*O
.SH RELATED INFORMATION
.PP
\*Ltty\*O(7), \*LMAKEDEV\*O(8)
.EQ
delim off
.EN
