.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: banner.1,v $ $Revision: 3.2.2.2 $ (DEC) $Date: 1992/05/05 18:43:02 $
.\"
.\" 
.\" (c) Copyright 1991, OPEN SOFTWARE FOUNDATION, INC.
.\" ALL RIGHTS RESERVED
.\" 
.TH banner 1
.SH NAME
\*Lbanner\*O \- Creates a large banner
.SH SYNOPSIS 
.PP 
.sS
\*Lbanner\*O
\*Vmessage\*O
.sE 
.SH DESCRIPTION
.iX "banner command"
.iX "creating" "banners"
.PP 
The \*Lbanner\*O command prints the specified \*Vmessage\*O in
large letters on the standard output.
.PP 
Each line in the banner output can be up to 10 uppercase or
lowercase characters long.  On output, all characters appear
in uppercase, with the lowercase input characters appearing
smaller than the uppercase input characters.
.SH EXAMPLES
.PP 
.AL 3m 
.LI
To display a one-word banner, enter:
.iS
banner SMILE
\*O\c
.iE
.LI
To display more than one word on a line, enclose the text in
quotes, enter:
.iS
banner "Out to" Lunch
\*O\c
.iE
.PP
This displays \*LOut to\*O on one line, and \*LLunch\*O on the next.
.LE 
.EQ
delim off
.EN
