.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: help.1,v $ $Revision: 3.2.2.3 $ (DEC) $Date: 1993/01/20 11:09:18 $
.\"
.\" 
.\" (c) Copyright 1991, OPEN SOFTWARE FOUNDATION, INC.
.\" ALL RIGHTS RESERVED
.\" 
.TH help 1
.SH NAME
\*Lhelp\*O \- Provides information for new users
.SH SYNOPSIS
.PP
.sS
\*Lhelp\*O
.sE
.SH DESCRIPTION
.iX "help command"
.iX "displaying" "information about the system"
.PP
The \*Lhelp\*O command presents a one-page display of
information for new users.  Information is available for the following
topics:
.ML
.LI
Concatenating or displaying files
.LI
Editing lines interactively
.LI
Sending and receiving mail
.LI
Reading system messages
.LI
Changing password file information
.LI
Identifying current users of the system
.LI
Sending messages to the other users on the system
.LI
Displaying the contents of directories
.LI
Viewing information on the Source Code Control System
.gL "Source Code Control System"
.gL "SCCS"
.LI
Setting terminal modes
.LE
.SH RELATED INFORMATION
.PP
Commands:  \*Lcat\*O(1), \*Lex\*O(1), \*Lfinger\*O(1), \*Lls\*O(1),
\*Lmail\*O(1)/\*Lbinmail\*O(1), \*Lmailx\*O(1)/\*LMail\*O(1),
\*Lpasswd\*O(1)/\*Lchfn\*O(1)/\*Lchsh\*O(1),
\*Lsccshelp\*O(1), \*Ltset\*O(1)/\*Lreset\*O(1), \*Lwho\*O(1), \*Lwrite\*O(1).
.EQ
delim off
.EN
