.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: hostname.1,v $ $Revision: 3.5.5.2 $ (DEC) $Date: 1993/09/30 21:27:57 $
.\"
.\" (c) Copyright 1990, 1991, 1992 OPEN SOFTWARE FOUNDATION, INC. 
.\" ALL RIGHTS RESERVED 
.\" OSF/1 Release 1.0.4
.\"build rmifdef
.TH hostname 1
.SH NAME
\*Lhostname\*O \- Sets or displays the name of the current host system
.SH SYNOPSIS 
.PP 
.sS
\*Lhostname\*O
\*O[\*Vnew_name\*O]
.sE 
.SH DESCRIPTION
.iX "hostname command"
.iX "displaying" "current hostname"
.iX "setting" "current hostname"
.iX "name" "host"
.PP 
The \*Lhostname\*O command sets or
displays the name of the current host system.
.gL "host system"
Only the superuser can set the hostname.
.SH EXAMPLES
.PP 
.AL 3m 
.LI
To display the name of the local host, enter:
.iS
$ hostname
.iE
.oS
host1
\*O\c
.oE
.LI
To change the name of the local host, enter:
.iS
# hostname west
\*O\c
.iE
.LE 
.SH FILES
.PP 
.VL 7m
.LI "\*L/etc/hosts\*O"
Defines the Interface Program name and address of the local host.
.gL "Interface Program"
.LE 
.SH RELATED INFORMATION
.PP 
Commands: \*Lhostid\*O(1).
.PP 
Functions:  \*Lgethostname\*O(2), \*Lsethostname\*O(2).
.EQ
delim off
.EN
