.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: id.1,v $ $Revision: 3.2.5.2 $ (DEC) $Date: 1993/11/14 16:32:18 $
.\"
.\" 
.\" (c) Copyright 1991, OPEN SOFTWARE FOUNDATION, INC.
.\" ALL RIGHTS RESERVED
.\" 
.TH id 1
.SH NAME
\*Lid\*O \- Displays the user's system identity
.SH SYNOPSIS
.PP
.sS
\*Lid\*O
.sE
.SH DESCRIPTION
.iX "id command"
.iX "displaying" "user identity"
.iX "users" "displaying identity"
.iX "groups" "displaying identity"
.iX "user ID"
.iX "group ID"
.PP
The \*Lid\*O command writes a message containing
the user and group IDs and corresponding names of the invoking process
to standard output.  When effective names and IDs do not match the real ones,
the \*Lid\*O command writes both.
.SH EXAMPLES
.PP
To display your user and group IDs, enter:
.oS
id
\*O\c
.oE
.PP
Information similar to the following is displayed:
.oS
uid=200(thomas)  gid=1(staff)
\*O\c
.oE
.SH RELATED INFORMATION
.PP
Commands:  \*Llogname\*O(1).
.PP
Functions:  \*Lgetuid\*O(2).
.EQ
delim off
.EN
