.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: logname.1,v $ $Revision: 3.2.2.4 $ (DEC) $Date: 1992/09/24 17:53:40 $
.\"
.\" 
.\" (c) Copyright 1991, OPEN SOFTWARE FOUNDATION, INC.
.\" ALL RIGHTS RESERVED
.\" 
.TH logname 1
.SH NAME
.PP
\*Llogname\*O \- Displays user login name
.SH SYNOPSIS 
.PP 
.sS
\*Llogname\*O
.sE 
.SH DESCRIPTION
.PP
.iX "logname command"
.iX "displaying" "login name"
.iX "name" "login"
.iX "login" "name"
The \*Llogname\*O command writes to standard output the name you
used to log into the system.  
.\" Begin Digital-specific information CORRECTION
.\" End Digital-specific information CORRECTION
.SH RELATED INFORMATION
.PP 
Commands:  \*Lenv\*O(1)/\*Lprintenv\*O(1), \*Llogin\*O(1).
.PP 
Functions:  \*Lgetlogin\*O(2).
.EQ
delim off
.EN
