.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: pwd.1,v $ $Revision: 3.2.2.2 $ (DEC) $Date: 1992/05/14 13:26:56 $
.\"
.\" 
.\" (c) Copyright 1991, OPEN SOFTWARE FOUNDATION, INC.
.\" ALL RIGHTS RESERVED
.\" 
.TH pwd 1
.SH NAME
\*Lpwd\*O \- Displays the pathname of the current (working) directory
.SH SYNOPSIS 
.PP 
.sS
\*Lpwd\*O
.sE 
.SH DESCRIPTION
.iX "pwd command"
.iX "displaying" "working directory pathname"
.iX "directories" "displaying working pathname"
.iX "pathnames" "working directory"
.PP 
The \*Lpwd\*O command writes to standard output the full pathname
of your current directory, from the root directory.  All directories
are separated by a / (slash).  The root directory is represented by the
first /, and the last directory named is your current directory.
.SH RELATED INFORMATION
.PP 
Commands:  \*Lcd\*O(1), \*Lcsh\*O(1), \*Lksh\*O(1), \*Lsh\*O(1).
.PP 
Functions:  \*Lstat\*O(2).
.EQ
delim off
.EN
