.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: runcord.1,v $ $Revision: 3.2.2.5 $ (DEC) $Date: 1993/01/22 21:16:17 $
.\"
.TH runcord 1
.SH NAME
.PP
\*Lruncord\*O \- invokes cord to rearrange procedures in an executable file to facilitate better cache mapping
.SH SYNOPSIS
.PP
\*Lruncord\*O -\*Lfeedback\*O \*Vfeedback_filename objfile\*O
.nL
[ \*L\-o\*O \*Voutfile\*O ] [ \*Vcord options\*O ]
.SH DESCRIPTION
.PP
.iX "runcord command"
The \*Lruncord\*O command invokes \*Lftoc\*O(1) to read one or more
feedback files produced by the \*L\-feedback\*O
option of the profiler \*Lprof\*O(1) or by
the \*Lfeedback\*O(1) utility and generates a
reorder-file for use with the cache-rearranging program \*Lcord\*O(1).
.PP
The \*Lruncord\*O command
then invokes \*Lcord\*O(1) to rearrange procedures in the executable file
to facilitate better cache mapping.
.PP
Note that the \*Lobjfile\*O is not a regular executable file, but rather
an executable object file
that has been built with the \*L\-d\*O, \*L\-r\*O, and \*L\-z\*O
options passed to the linker, as well as with all runtime options specified.
.SH FLAGS
.PP
In addition to the options for the
\*Vcord\*O
command,
\*Lruncord\*O accepts the following options:
.RS
.TP 30
.BI -feedback " feedback_filename"
specifies the name of the feedback file to read
.TP
.BI -o " outfile"
specifies the name of the output file
.RE
.SH RELATED INFORMATION
.PP
\*Lcord\*O(1), \*Lprof\*O(1), \*Lfeedback\*O(1), \*Lftoc\*O(1)
.PP
\*EProgrammer's Guide\*O
.EQ
delim off
.EN
