.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: true.1,v $ $Revision: 3.2.5.3 $ (DEC) $Date: 1993/11/13 21:39:03 $
.\"
.\" 
.\" (c) Copyright 1991, OPEN SOFTWARE FOUNDATION, INC.
.\" ALL RIGHTS RESERVED
.\" 
.TH true 1
.SH NAME
\*Ltrue\*O, \*Lfalse\*O \- Returns a standard exit value
.SH SYNOPSIS
.PP
.sS
\*Ltrue\*O
.PP
\*Lfalse\*O
.sE
.SH DESCRIPTION
.iX "true command"
.iX "false command"
.iX "returning" "standard exit value"
.iX "exit values"
.PP
The \*Ltrue\*O command returns a 0 (zero) exit value.
The \*Lfalse\*O command returns a nonzero exit value.
These commands are usually used in input to shell commands.
.SH EXAMPLES
.PP
To construct a loop in a shell procedure, enter:
.iS
while true
do
	date
	sleep 60
done
\*O\c
.iE
.PP
This procedure displays the date and time once a minute.  To stop it,
press the Interrupt key sequence.
.SH EXIT VALUES
.PP
The nonzero value returned by \*Lfalse\*O may vary from
system to system.
.SH RELATED INFORMATION
.PP
Commands:  \*Lcsh\*O(1), \*Lksh\*O(1), \*Lsh\*O(1).
.EQ
delim off
.EN
