.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: uusend.1,v $ $Revision: 3.2.2.3 $ (DEC) $Date: 1993/01/26 20:38:06 $
.\"
.\" 
.\" (c) Copyright 1991, OPEN SOFTWARE FOUNDATION, INC.
.\" ALL RIGHTS RESERVED
.\" 
.TH uusend 1
.SH NAME
\*Luusend\*O \- Sends a file to a remote host
.SH SYNOPSIS 
.PP 
.sS
\*Luusend\*O
\*O[\*L-m\*O
\*Vmode\*O]
\*Vlocal_file\*O
\*Vsystem1\*L!\*Vsystem2\*L!
\&...\*L!\*Vremote_file\*O
.sE
.PP
The \*Luusend\*O command sends a file to a given location on a remote system.
.SH "FLAGS"
.PP 
.VL 4m
.LI "\*L-m\*O \*Vmode\*O"
Specifies that the mode of the file on the remote
system be taken from the octal number given. If this flag is
not specified, the mode of the input file is used.
.LE 
.SH "DESCRIPTION"
.PP 
The remote system does not need to be directly connected
to the local system, but a chain of \*Luucp\*O links needs to connect the
two system.
.SH "RELATED INFORMATION"
.PP 
Commands:  \*Lct\*O(1), \*Lcu\*O(1), \*Ltip\*O(1),
\*Luucico\*O(8), \*Luucleanup\*O(8), \*Luucp\*O(1),
\*Luuencode\*O(1)/\*Luudecode\*O(1),
\*Luulog\*O(1), \*Luuname\*O(1), \*Luupick\*O(1), \*Luusched\*O(8),
\*Luustat\*O(1),
\*Luuto\*O(1), \*Luux\*O(1).
.\", \*Luuxqt\*O(8).
.EQ
delim off
.EN
