.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
...\" (c) Copyright 1990, 1991, 1992 OPEN SOFTWARE FOUNDATION, INC.
...\" ALL RIGHTS RESERVED
...\" OSF/1 1.1
.TH whois 1
.SH NAME
.PP
\*Lwhois\*O - Internet username directory service
.SH SYNOPSIS
.PP
.iX "whois command"
.sS
\*Lwhois\*O
\*O[\*L\(hyh\ \*Vserver\*O]
\*Vname\*O
.sE
.PP
The \*Lwhois\*O command looks up user, host, and organization
names in the Network Information Center (NIC) database.
.SH FLAGS
.PP
.VL 4m
.LI "\*L-h \*Vserver\*O"
Specifies a \*Lwhois\*O server other than the default
server \*Lrs.internic.net\*O.
.LE
.SH DESCRIPTION
.PP
The \*Vname\*O argument can specify the following:
.ML
.LI
The name of a registered user
.LI
The name of a registered Internet host
.LI
The name of some other entity recognized by the \*Lwhois\*O server
By default, the \*Lwhois\*O command queries the host
\*Lrs.internic.net\*O.
.LE
.PP
If the \*Vname\*O argument contains any whitespace or special
characters, enclose it in \*L""\*O (double quotes) to prevent
the shell from interpreting it.
.SH EXAMPLES
.PP
To display the NIC database entry for the organization
\*Losf.org\*O, enter:
.iS
whois osf.org
.iE
.oS
Open Software Foundation (OSF-DOM)
11 Cambridge Center
Cambridge, MAS 02142

Domain Name:  OSF.ORG
\&.
\&.
\&.
.oE
.EQ
delim off
.EN
